export enum SyncType {
  Full = 'full',
  Incremental = 'incremental',
}

export enum SyncTrigger {
  Manual = 'manual',
  Schedule = 'schedule',
  Webhook = 'webhook',
}

export enum OnDeleteAction {
  Delete = 'delete',
  MarkDeleted = 'mark_deleted',
}

export enum SyncCategory {
  TICKETING = 'ticketing',
  CRM = 'crm',
  ATS = 'ats',
  FILE_STORAGE = 'file_storage',
  CUSTOM = 'custom',
}

export const SyncTriggerMeta = {
  [SyncTrigger.Manual]: {
    value: SyncTrigger.Manual,
    label: 'Manual',
    description: 'Sync data manually',
  },
  [SyncTrigger.Schedule]: {
    value: SyncTrigger.Schedule,
    label: 'Scheduled',
    description: 'Sync data on a schedule',
  },
  [SyncTrigger.Webhook]: {
    value: SyncTrigger.Webhook,
    label: 'Webhook',
    description: 'Sync data via a webhook',
  },
};

export const OnDeleteActionMeta = {
  [OnDeleteAction.Delete]: {
    value: OnDeleteAction.Delete,
    label: 'Delete',
    description: 'Delete data permanently in NocoDB',
  },
  [OnDeleteAction.MarkDeleted]: {
    value: OnDeleteAction.MarkDeleted,
    label: 'Mark Deleted',
    description: 'Mark data as deleted in NocoDB',
  },
};

export const SyncTypeMeta = {
  [SyncType.Full]: {
    value: SyncType.Full,
    label: 'Full',
    description: 'Sync all data',
  },
  [SyncType.Incremental]: {
    value: SyncType.Incremental,
    label: 'Incremental',
    description: 'Sync only new and updated data',
  },
};

export const SyncCategoryMeta = {
  [SyncCategory.TICKETING]: {
    value: SyncCategory.TICKETING,
    label: 'Ticketing',
    description: 'Sync data from a ticketing system',
    icon: 'ncBookOpen',
  },
  [SyncCategory.ATS]: {
    value: SyncCategory.ATS,
    label: 'ATS',
    description: 'Sync employees, leaves and timesheet.',
    icon: 'ncUsers',
  },
  [SyncCategory.CRM]: {
    value: SyncCategory.CRM,
    label: 'CRM',
    description: 'Sync data from a CRM',
    icon: 'ncUsers',
  },
  [SyncCategory.FILE_STORAGE]: {
    value: SyncCategory.FILE_STORAGE,
    label: 'File Storage',
    description: 'Sync data from a file storage system',
    icon: 'ncFolder',
  },
  [SyncCategory.CUSTOM]: {
    value: SyncCategory.CUSTOM,
    label: 'Custom',
    description: 'Sync data from a dynamic source',
    icon: 'ncDatabase',
  },
};

export enum TARGET_TABLES {
  TICKETING_TICKET = 'ticketing_ticket',
  TICKETING_USER = 'ticketing_user',
  TICKETING_COMMENT = 'ticketing_comment',
  TICKETING_TEAM = 'ticketing_team',
  HRIS_EMPLOYEE = 'hris_employee',

  // one by one will be enabled
  // HRIS_BANK_INFO = 'hris_bank_info',
  // HRIS_BENEFIT = 'hris_benefit',
  // HRIS_COMPANY = 'hris_company',
  // HRIS_DEPENDENT = 'hris_dependent',
  // HRIS_EMPLOYEE_PAYROLL_RUN = 'hris_employee_payroll_run',
  HRIS_EMPLOYMENT = 'hris_employment',
  // HRIS_GROUP = 'hris_group',
  HRIS_LOCATION = 'hris_location',
  // HRIS_PAYROLL_RUN = 'hris_payroll_run',
  // HRIS_TIME_OFF = 'hris_time_off',
  // HRIS_TIME_OFF_BALANCE = 'hris_time_off_balance',
  // HRIS_TIMESHEET_ENTRY = 'hris_timesheet_entry',

  // some not prioritized HRIS tables are commented
  // HRIS_EMPLOYER_BENEFIT = 'hris_employer_benefit',

  FILE_STORAGE_FILE = 'fs_file',
  FILE_STORAGE_FOLDER = 'fs_folder',

  CRM_ACCOUNT = 'crm_account',
  // CRM_ASSOCIATION = 'crm_association',
  // CRM_ASSOCIATION_TYPE = 'crm_association_type',
  CRM_CONTACT = 'crm_contact',
  // CRM_CUSTOM_OBJECT = 'crm_custom_object',
  // CRM_CUSTOM_OBJECT_CLASS = 'crm_custom_object_class',
  // CRM_ENGAGEMENT = 'crm_engagement',
  // CRM_ENGAGEMENT_TYPE = 'crm_engagement_type',
  // CRM_LEAD = 'crm_lead',
  // CRM_NOTE = 'crm_note',
  // CRM_OPPORTUNITY = 'crm_opportunity',
  // CRM_STAGE = 'crm_stage',
  // CRM_TASK = 'crm_task',
  CRM_USER = 'crm_user',
  ATS_APPLICATION = 'ats_application',
  ATS_CANDIDATE = 'ats_candidate',
  ATS_JOB = 'ats_job',
  ATS_JOB_POSTING = 'ats_job_posting',
  ATS_OFFER = 'ats_offer',
  ATS_SCHEDULED_INTERVIEW = 'ats_scheduled_interview',
  ATS_TAG = 'ats_tag',
}

export const TARGET_TABLES_META = {
  [TARGET_TABLES.TICKETING_TICKET]: {
    category: SyncCategory.TICKETING,
    value: TARGET_TABLES.TICKETING_TICKET,
    icon: 'ncBookOpen',
    label: 'Ticket',
    description: 'Sync all ticket data from the source',
    required: true,
  },
  [TARGET_TABLES.TICKETING_USER]: {
    category: SyncCategory.TICKETING,
    value: TARGET_TABLES.TICKETING_USER,
    icon: 'ncUsers',
    label: 'User',
    description: 'Sync all users on tickets from the source',
    required: true,
  },
  [TARGET_TABLES.TICKETING_COMMENT]: {
    category: SyncCategory.TICKETING,
    value: TARGET_TABLES.TICKETING_COMMENT,
    icon: 'ncMessageCircle',
    label: 'Comment',
    description: 'Sync all comments on tickets',
    required: false,
  },
  [TARGET_TABLES.TICKETING_TEAM]: {
    category: SyncCategory.TICKETING,
    value: TARGET_TABLES.TICKETING_TEAM,
    icon: 'ncUsers',
    label: 'Team',
    description: 'Sync all teams from the source',
    required: false,
  },
  [TARGET_TABLES.HRIS_EMPLOYEE]: {
    category: SyncCategory.HRIS,
    value: TARGET_TABLES.HRIS_EMPLOYEE,
    icon: 'ncUsers',
    label: 'HR_Employee',
    description: 'Represents human resources employee data.',
    required: true,
  },
  [TARGET_TABLES.FILE_STORAGE_FILE]: {
    category: SyncCategory.FILE_STORAGE,
    value: TARGET_TABLES.FILE_STORAGE_FILE,
    icon: 'file',
    label: 'FS_File',
    description: 'Represents file storage file metadata.',
    required: false,
  },
  [TARGET_TABLES.FILE_STORAGE_FOLDER]: {
    category: SyncCategory.FILE_STORAGE,
    value: TARGET_TABLES.FILE_STORAGE_FOLDER,
    icon: 'ncFolder',
    label: 'FS_Folder',
    description: 'Represents file storage folder metadata.',
    required: false,
  },
  // [TARGET_TABLES.HRIS_BANK_INFO]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_BANK_INFO,
  //   icon: 'ncDatabase',
  //   label: 'HR_Bank Info',
  //   description: 'Represents human resources bank information data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_BENEFIT]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_BENEFIT,
  //   icon: 'ncDatabase',
  //   label: 'HR_Benefit',
  //   description: 'Represents human resources benefit data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_COMPANY]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_COMPANY,
  //   icon: 'ncDatabase',
  //   label: 'HR_Company',
  //   description: 'Represents human resources company data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_DEPENDENT]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_DEPENDENT,
  //   icon: 'ncUsers',
  //   label: 'HR_Dependent',
  //   description: 'Represents human resources dependent data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_EMPLOYEE_PAYROLL_RUN]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_EMPLOYEE_PAYROLL_RUN,
  //   icon: 'ncDatabase',
  //   label: 'HR_Employee Payroll Run',
  //   description: 'Represents human resources employee payroll run data.',
  //   required: false,
  // },
  [TARGET_TABLES.HRIS_EMPLOYMENT]: {
    category: SyncCategory.HRIS,
    value: TARGET_TABLES.HRIS_EMPLOYMENT,
    icon: 'ncDatabase',
    label: 'HR_Employment',
    description: 'Represents human resources employment data.',
    required: false,
  },
  // [TARGET_TABLES.HRIS_GROUP]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_GROUP,
  //   icon: 'ncUsers',
  //   label: 'HR_Group',
  //   description: 'Represents human resources group data.',
  //   required: false,
  // },
  [TARGET_TABLES.HRIS_LOCATION]: {
    category: SyncCategory.HRIS,
    value: TARGET_TABLES.HRIS_LOCATION,
    icon: 'ncDatabase',
    label: 'HR_Location',
    description: 'Represents human resources location data.',
    required: false,
  },
  // [TARGET_TABLES.HRIS_PAYROLL_RUN]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_PAYROLL_RUN,
  //   icon: 'ncDatabase',
  //   label: 'HR - Payroll Run',
  //   description: 'Represents human resources payroll run data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_TIME_OFF]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_TIME_OFF,
  //   icon: 'ncDatabase',
  //   label: 'HR - Time Off',
  //   description: 'Represents human resources time off data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_TIME_OFF_BALANCE]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_TIME_OFF_BALANCE,
  //   icon: 'ncDatabase',
  //   label: 'HR - Time Off Balance',
  //   description: 'Represents human resources time off balance data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_TIMESHEET_ENTRY]: {
  //   category: SyncCategory.HRIS,
  //   value: TARGET_TABLES.HRIS_TIMESHEET_ENTRY,
  //   icon: 'ncDatabase',
  //   label: 'HR - Timesheet Entry',
  //   description: 'Represents human resources timesheet entry data.',
  //   required: false,
  // },
  // [TARGET_TABLES.HRIS_EMPLOYER_BENEFIT]: {
  //   category: SyncCategory.CUSTOM,
  //   value: TARGET_TABLES.HRIS_EMPLOYER_BENEFIT,
  //   icon: 'ncDatabase',
  //   label: 'HR - Employer Benefit',
  //   description: 'Represents human resources employer benefit data.',
  //   required: false,
  // },

  [TARGET_TABLES.CRM_ACCOUNT]: {
    category: SyncCategory.CRM,
    value: TARGET_TABLES.CRM_ACCOUNT,
    icon: 'ncUsers',
    label: 'CRM_Account',
    description: 'Represents crm account data.',
    required: true,
  },
  // [TARGET_TABLES.CRM_ASSOCIATION]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_ASSOCIATION,
  //   icon: 'link2',
  //   label: 'CRM_Association',
  //   description: 'Represents crm association data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_ASSOCIATION_TYPE]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_ASSOCIATION_TYPE,
  //   icon: 'label',
  //   label: 'CRM_Association_type',
  //   description: 'Represents crm association types data.',
  //   required: false,
  // },
  [TARGET_TABLES.CRM_CONTACT]: {
    category: SyncCategory.CRM,
    value: TARGET_TABLES.CRM_CONTACT,
    icon: 'ncUsers',
    label: 'CRM_Contact',
    description: 'Represents crm contact data.',
    required: true,
  },
  // [TARGET_TABLES.CRM_CUSTOM_OBJECT]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_CUSTOM_OBJECT,
  //   icon: 'box',
  //   label: 'CRM_Custom_Object',
  //   description: 'Represents crm custom object data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_CUSTOM_OBJECT_CLASS]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_CUSTOM_OBJECT_CLASS,
  //   icon: 'layers',
  //   label: 'CRM_Custom_Object_Class',
  //   description: 'Represents crm custom object class data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_ENGAGEMENT]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_ENGAGEMENT,
  //   icon: 'message-square',
  //   label: 'CRM_Engagement',
  //   description: 'Represents crm engagement data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_ENGAGEMENT_TYPE]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_ENGAGEMENT_TYPE,
  //   icon: 'tag',
  //   label: 'CRM_Engagement_Type',
  //   description: 'Represents crm engagement type data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_LEAD]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_LEAD,
  //   icon: 'user-plus',
  //   label: 'CRM_Lead',
  //   description: 'Represents crm lead data.',
  //   required: true,
  // },
  // [TARGET_TABLES.CRM_NOTE]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_NOTE,
  //   icon: 'file-text',
  //   label: 'CRM_Note',
  //   description: 'Represents crm note data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_OPPORTUNITY]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_OPPORTUNITY,
  //   icon: 'trending-up',
  //   label: 'CRM_Opportunity',
  //   description: 'Represents crm opportunity data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_STAGE]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_STAGE,
  //   icon: 'sliders',
  //   label: 'CRM_Stage',
  //   description: 'Represents crm stage data.',
  //   required: false,
  // },
  // [TARGET_TABLES.CRM_TASK]: {
  //   category: SyncCategory.CRM,
  //   value: TARGET_TABLES.CRM_TASK,
  //   icon: 'check-square',
  //   label: 'CRM_Task',
  //   description: 'Represents crm task data.',
  //   required: false,
  // },
  [TARGET_TABLES.CRM_USER]: {
    category: SyncCategory.CRM,
    value: TARGET_TABLES.CRM_USER,
    icon: 'user',
    label: 'CRM_User',
    description: 'Represents crm user data.',
    required: true,
  [TARGET_TABLES.ATS_APPLICATION]: {
    category: SyncCategory.ATS,
    value: TARGET_TABLES.ATS_APPLICATION,
    icon: 'ncUserPlus',
    label: 'ATS_Application',
    description: 'Represents recruiting job application data.',
    required: false,
  },
  [TARGET_TABLES.ATS_CANDIDATE]: {
    category: SyncCategory.ATS,
    value: TARGET_TABLES.ATS_CANDIDATE,
    icon: 'ncUsers',
    label: 'ATS_Candidate',
    description: 'Represents recruiting candidate data.',
    required: true,
  },
  [TARGET_TABLES.ATS_JOB]: {
    category: SyncCategory.ATS,
    value: TARGET_TABLES.ATS_JOB,
    icon: 'ncDatabase',
    label: 'ncFileText',
    description: 'Represents jobs to fill data.',
    required: true,
  },
  [TARGET_TABLES.ATS_JOB_POSTING]: {
    category: SyncCategory.ATS,
    value: TARGET_TABLES.ATS_JOB_POSTING,
    icon: 'ncFileText',
    label: 'ATS_Job_Posting',
    description: 'Represents posted jobs data.',
    required: false,
  },
  [TARGET_TABLES.ATS_OFFER]: {
    category: SyncCategory.ATS,
    value: TARGET_TABLES.ATS_OFFER,
    icon: 'ncFilePlus',
    label: 'ATS_Offer',
    description: 'Represents offering data.',
    required: false,
  },
  [TARGET_TABLES.ATS_SCHEDULED_INTERVIEW]: {
    category: SyncCategory.ATS,
    value: TARGET_TABLES.ATS_SCHEDULED_INTERVIEW,
    icon: 'calendar',
    label: 'ATS_Scheduled_Interview',
    description: 'Represents schedule of interview data.',
    required: false,
  },
  [TARGET_TABLES.ATS_TAG]: {
    category: SyncCategory.ATS,
    value: TARGET_TABLES.ATS_TAG,
    icon: 'label',
    label: 'ATS_Tag',
    description: 'Represents tags of some other table data.',
    required: false,
  },
};
