packages:
  - 'packages/nocodb-sdk'
  - 'packages/nc-gui'
  - 'packages/nocodb'
  - 'packages/nc-knex-dialects/knex-snowflake'
  - 'packages/nc-knex-dialects/knex-databricks'
  - 'packages/nc-sql-executor'
  - 'tests/playwright'
  - 'packages/nc-mail-templates'
  - 'packages/nc-secret-cli'
