packages:
  - 'packages/nocodb-sdk'
  - 'packages/nocodb-sdk-v2'
  - 'packages/nc-gui'
  - 'packages/nocodb'
  - 'packages/nc-knex-dialects/knex-snowflake'
  - 'packages/nc-knex-dialects/knex-databricks'
  - 'packages/nc-sql-executor'
  - 'tests/playwright'
  - 'packages/nc-secret-mgr'
  - 'packages/nc-integration-scaffolder'