import { UITypes, TARGET_TABLES, TARGET_TABLES_META } from 'nocodb-sdk';
import { SyncSchema, SyncRecord, SyncValue } from './types';

export const SCHEMA_HRIS: SyncSchema = {
  [TARGET_TABLES.HRIS_BANK_INFO]: {
    title: TARGET_TABLES_META.hris_bank_info.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Account Number', uidt: UITypes.SingleLineText },
      { title: 'Routing Number', uidt: UITypes.SingleLineText },
      { title: 'Bank Name', uidt: UITypes.SingleLineText },
      { title: 'Account Type', uidt: UITypes.SingleSelect },
      { title: 'Remote Created At', uidt: UITypes.DateTime },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Bank Infos',
      },
    ],
  },
  [TARGET_TABLES.HRIS_BENEFIT]: {
    title: TARGET_TABLES_META.hris_benefit.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Provider Name', uidt: UITypes.SingleLineText },
      { title: 'Benefit Plan Type', uidt: UITypes.SingleSelect },
      { title: 'Employee Contribution', uidt: UITypes.Currency },
      { title: 'Company Contribution', uidt: UITypes.Currency },
      { title: 'Start Date', uidt: UITypes.Date },
      { title: 'End Date', uidt: UITypes.Date },
      { title: 'Employer Benefit', uidt: UITypes.SingleLineText },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Benefits',
      },
    ],
  },
  [TARGET_TABLES.HRIS_COMPANY]: {
    title: TARGET_TABLES_META.hris_company.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Legal Name', uidt: UITypes.SingleLineText, pv: true },
      { title: 'Display Name', uidt: UITypes.SingleLineText, pv: true },
      { title: 'Eins', uidt: UITypes.MultiSelect },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [],
  },
  [TARGET_TABLES.HRIS_DEPENDENT]: {
    title: TARGET_TABLES_META.hris_dependent.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'First Name', uidt: UITypes.SingleLineText },
      { title: 'Middle Name', uidt: UITypes.SingleLineText },
      { title: 'Last Name', uidt: UITypes.SingleLineText },
      { title: 'Relationship', uidt: UITypes.SingleSelect },
      { title: 'Date Of Birth', uidt: UITypes.Date },
      { title: 'Gender', uidt: UITypes.SingleSelect },
      { title: 'Phone Number', uidt: UITypes.PhoneNumber },
      { title: 'Home Location', uidt: UITypes.SingleLineText },
      { title: 'Is Student', uidt: UITypes.Checkbox },
      { title: 'Ssn', uidt: UITypes.SingleLineText },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Dependents',
      },
    ],
  },
  [TARGET_TABLES.HRIS_EMPLOYEE]: {
    title: TARGET_TABLES_META.hris_employee.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Employee Number', uidt: UITypes.SingleLineText },
      { title: 'Company', uidt: UITypes.SingleLineText },
      { title: 'First Name', uidt: UITypes.SingleLineText },
      { title: 'Last Name', uidt: UITypes.SingleLineText },
      { title: 'Preferred Name', uidt: UITypes.SingleLineText },
      { title: 'Display Full Name', uidt: UITypes.SingleLineText },
      { title: 'Username', uidt: UITypes.SingleLineText },
      { title: 'Groups', uidt: UITypes.MultiSelect },
      { title: 'Work Email', uidt: UITypes.Email },
      { title: 'Personal Email', uidt: UITypes.Email },
      { title: 'Mobile Phone Number', uidt: UITypes.PhoneNumber },
      { title: 'Employments', uidt: UITypes.MultiSelect },
      { title: 'Home Location', uidt: UITypes.SingleLineText },
      { title: 'Work Location', uidt: UITypes.SingleLineText },
      { title: 'Team', uidt: UITypes.SingleLineText },
      { title: 'Pay Group', uidt: UITypes.SingleLineText },
      { title: 'Ssn', uidt: UITypes.SingleLineText },
      { title: 'Gender', uidt: UITypes.SingleSelect },
      { title: 'Ethnicity', uidt: UITypes.SingleSelect },
      { title: 'Marital Status', uidt: UITypes.SingleSelect },
      { title: 'Date Of Birth', uidt: UITypes.Date },
      { title: 'Hire Date', uidt: UITypes.Date },
      { title: 'Start Date', uidt: UITypes.Date },
      { title: 'Remote Created At', uidt: UITypes.DateTime },
      { title: 'Employment Status', uidt: UITypes.SingleSelect },
      { title: 'Termination Date', uidt: UITypes.Date },
      { title: 'Avatar', uidt: UITypes.URL },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Manager',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Managed Employees',
      },
    ],
  },
  [TARGET_TABLES.HRIS_EMPLOYEE_PAYROLL_RUN]: {
    title: TARGET_TABLES_META.hris_employee_payroll_run.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Payroll Run', uidt: UITypes.SingleLineText },
      { title: 'Gross Pay', uidt: UITypes.Currency },
      { title: 'Net Pay', uidt: UITypes.Currency },
      { title: 'Start Date', uidt: UITypes.Date },
      { title: 'End Date', uidt: UITypes.Date },
      { title: 'Check Date', uidt: UITypes.Date },
      { title: 'Earnings', uidt: UITypes.JSON },
      { title: 'Deductions', uidt: UITypes.JSON },
      { title: 'Taxes', uidt: UITypes.JSON },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Payroll Runs',
      },
    ],
  },
  [TARGET_TABLES.HRIS_EMPLOYMENT]: {
    title: TARGET_TABLES_META.hris_employment.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Job Title', uidt: UITypes.SingleLineText },
      { title: 'Pay Rate', uidt: UITypes.Currency },
      { title: 'Pay Period', uidt: UITypes.SingleSelect },
      { title: 'Pay Frequency', uidt: UITypes.SingleSelect },
      { title: 'Pay Currency', uidt: UITypes.SingleSelect },
      { title: 'Pay Group', uidt: UITypes.SingleLineText },
      { title: 'Flsa Status', uidt: UITypes.SingleSelect },
      { title: 'Effective Date', uidt: UITypes.Date },
      { title: 'Employment Type', uidt: UITypes.SingleSelect },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [],
  },
  [TARGET_TABLES.HRIS_GROUP]: {
    title: TARGET_TABLES_META.hris_group.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Parent Group', uidt: UITypes.SingleLineText },
      { title: 'Name', uidt: UITypes.SingleLineText, pv: true },
      { title: 'Type', uidt: UITypes.SingleSelect },
      { title: 'Is Commonly Used As Team', uidt: UITypes.Checkbox },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [],
  },
  [TARGET_TABLES.HRIS_LOCATION]: {
    title: TARGET_TABLES_META.hris_location.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Name', uidt: UITypes.SingleLineText, pv: true },
      { title: 'Phone Number', uidt: UITypes.PhoneNumber },
      { title: 'Street 1', uidt: UITypes.SingleLineText },
      { title: 'Street 2', uidt: UITypes.SingleLineText },
      { title: 'City', uidt: UITypes.SingleLineText },
      { title: 'State', uidt: UITypes.SingleLineText },
      { title: 'Zip Code', uidt: UITypes.SingleLineText },
      { title: 'Country', uidt: UITypes.SingleSelect },
      { title: 'Location Type', uidt: UITypes.SingleSelect },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Employments',
      },
    ],
  },
  [TARGET_TABLES.HRIS_PAY_GROUP]: {
    title: TARGET_TABLES_META.hris_pay_group.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Pay Group Name', uidt: UITypes.SingleLineText, pv: true },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [],
  },
  [TARGET_TABLES.HRIS_PAYROLL_RUN]: {
    title: TARGET_TABLES_META.hris_payroll_run.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Run State', uidt: UITypes.SingleSelect },
      { title: 'Run Type', uidt: UITypes.SingleSelect },
      { title: 'Start Date', uidt: UITypes.Date },
      { title: 'End Date', uidt: UITypes.Date },
      { title: 'Check Date', uidt: UITypes.Date },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [],
  },
  [TARGET_TABLES.HRIS_TIME_OFF]: {
    title: TARGET_TABLES_META.hris_time_off.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Approver', uidt: UITypes.SingleLineText },
      { title: 'Status', uidt: UITypes.SingleSelect },
      { title: 'Employee Note', uidt: UITypes.LongText },
      { title: 'Units', uidt: UITypes.SingleSelect },
      { title: 'Amount', uidt: UITypes.Decimal },
      { title: 'Request Type', uidt: UITypes.SingleSelect },
      { title: 'Start Time', uidt: UITypes.DateTime },
      { title: 'End Time', uidt: UITypes.DateTime },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Time Off',
      },
    ],
  },
  [TARGET_TABLES.HRIS_TIME_OFF_BALANCE]: {
    title: TARGET_TABLES_META.hris_time_off_balance.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Balance', uidt: UITypes.Decimal },
      { title: 'Used', uidt: UITypes.Decimal },
      { title: 'Policy Type', uidt: UITypes.SingleSelect },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Time Off Balances',
      },
    ],
  },
  [TARGET_TABLES.HRIS_TIMESHEET_ENTRY]: {
    title: TARGET_TABLES_META.hris_timesheet_entry.label,
    columns: [
      { title: 'Remote Id', uidt: UITypes.SingleLineText },
      { title: 'Created At', uidt: UITypes.DateTime },
      { title: 'Modified At', uidt: UITypes.DateTime },
      { title: 'Hours Worked', uidt: UITypes.Decimal },
      { title: 'Start Time', uidt: UITypes.DateTime },
      { title: 'End Time', uidt: UITypes.DateTime },
      { title: 'Remote Data', uidt: UITypes.JSON },
    ],
    relations: [
      {
        columnTitle: 'Employee',
        relatedTable: TARGET_TABLES.HRIS_EMPLOYEE,
        relatedTableColumnTitle: 'Timesheet Entries',
      },
    ],
  },
};
