/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ClaritySuccessLine: typeof import('~icons/clarity/success-line')['default']
    LogosGoogleGmail: typeof import('~icons/logos/google-gmail')['default']
    MaterialSymbolsKeyboardArrowDownRounded: typeof import('~icons/material-symbols/keyboard-arrow-down-rounded')['default']
    MaterialSymbolsKeyboardReturn: typeof import('~icons/material-symbols/keyboard-return')['default']
    MaterialSymbolsRocketLaunchOutline: typeof import('~icons/material-symbols/rocket-launch-outline')['default']
    MaterialSymbolsTranslate: typeof import('~icons/material-symbols/translate')['default']
    MaterialSymbolsWarning: typeof import('~icons/material-symbols/warning')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    MdiAccountCircleOutline: typeof import('~icons/mdi/account-circle-outline')['default']
    MdiAccountSupervisorOutline: typeof import('~icons/mdi/account-supervisor-outline')['default']
    MdiAppleKeyboardShift: typeof import('~icons/mdi/apple-keyboard-shift')['default']
    MdiBookOpenBlankVariant: typeof import('~icons/mdi/book-open-blank-variant')['default']
    MdiCircleMedium: typeof import('~icons/mdi/circle-medium')['default']
    MdiLinkVariant: typeof import('~icons/mdi/link-variant')['default']
    MdiLogin: typeof import('~icons/mdi/login')['default']
    MdiLogout: typeof import('~icons/mdi/logout')['default']
    MdiMapMarkerOutline: typeof import('~icons/mdi/map-marker-outline')['default']
    MdiShieldKeyOutline: typeof import('~icons/mdi/shield-key-outline')['default']
    MdiStarOutline: typeof import('~icons/mdi/star-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
