import {
  AuditOperationSubTypes,
  AuditOperationTypes,
  UITypes,
} from 'nocodb-sdk';
import {
  _wherePk,
  BaseModelSqlv2 as BaseModelSqlv2CE,
  extractCondition,
  extractFilterFromXwhere,
  extractSortsObject,
  getListArgs,
  populatePk,
} from 'src/db/BaseModelSqlv2';
import DOMPurify from 'isomorphic-dompurify';
import type { Column, Model } from '~/models';
import { Audit, Source, View } from '~/models';
import { getSingleQueryReadFn } from '~/services/data-opt/helpers';
import { canUseOptimisedQuery } from '~/utils';
import { extractProps } from '~/helpers/extractProps';
import { HANDLE_STATS } from '~/services/update-stats.service';
import Noco from '~/Noco';

/**
 * Base class for models
 *
 * @class
 * @classdesc Base class for models
 */
class BaseModelSqlv2 extends BaseModelSqlv2CE {
  public schema?: string;

  constructor({
    dbDriver,
    model,
    viewId,
    schema,
  }: {
    [key: string]: any;
    model: Model;
    schema?: string;
  }) {
    super({ dbDriver, model, viewId });
    this.schema = schema;
  }

  public getTnPath(tb: { table_name: string } | string, alias?: string) {
    const tn = typeof tb === 'string' ? tb : tb.table_name;
    const schema = (this.dbDriver as any).searchPath?.();
    if (this.isPg && this.schema) {
      return `${this.schema}.${tn}${alias ? ` as ${alias}` : ``}`;
    } else if (this.isMssql && schema) {
      return this.dbDriver.raw(`??.??${alias ? ' as ??' : ''}`, [
        schema,
        tn,
        ...(alias ? [alias] : []),
      ]);
    } else if (this.isSnowflake) {
      return `${[
        this.dbDriver.client.config.connection.database,
        this.dbDriver.client.config.connection.schema,
        tn,
      ].join('.')}${alias ? ` as ${alias}` : ``}`;
    } else {
      return `${tn}${alias ? ` as ${alias}` : ``}`;
    }
  }

  async insert(data, trx?, cookie?, disableOptimization = false) {
    try {
      await populatePk(this.model, data);

      // todo: filter based on view
      const insertObj = await this.model.mapAliasToColumn(
        data,
        this.clientMeta,
        this.dbDriver,
      );

      await this.validate(insertObj);

      if ('beforeInsert' in this) {
        await this.beforeInsert(insertObj, trx, cookie);
      }

      await this.prepareAttachmentData(insertObj);

      await this.model.getColumns();
      let response;
      // const driver = trx ? trx : this.dbDriver;

      const query = this.dbDriver(this.tnPath).insert(insertObj);
      if ((this.isPg || this.isMssql) && this.model.primaryKey) {
        query.returning(
          `${this.model.primaryKey.column_name} as ${this.model.primaryKey.title}`,
        );
        response = await this.execAndParse(query);
      }

      const ai = this.model.columns.find((c) => c.ai);

      let ag: Column;
      if (!ai) ag = this.model.columns.find((c) => c.meta?.ag);

      const source = await Source.get(this.model.source_id);
      const view = this.viewId ? await View.get(this.viewId) : null;

      // handle if autogenerated primary key is used
      if (ag) {
        if (!response) await this.execAndParse(query);
        response = await ((await canUseOptimisedQuery({
          source,
          disableOptimization,
        }))
          ? getSingleQueryReadFn(source)({
              model: this.model,
              view,
              id: data[ag.title],
              params: {},
              source,
              getHiddenColumn: true,
            })
          : this.readByPk(
              data[ag.title],
              false,
              {},
              { ignoreView: true, getHiddenColumn: true },
            ));
      } else if (
        !response ||
        (typeof response?.[0] !== 'object' && response?.[0] !== null)
      ) {
        let id;
        if (response?.length) {
          id = response[0];
        } else {
          const res = await this.execAndParse(query);
          id = res?.id ?? res[0]?.insertId;
        }

        if (ai) {
          if (this.isSqlite) {
            // sqlite doesnt return id after insert
            id = (
              await this.dbDriver(this.tnPath)
                .select(ai.column_name)
                .max(ai.column_name, { as: 'id' })
            )[0].id;
          } else if (this.isSnowflake) {
            id = (
              (await this.dbDriver(this.tnPath).max(ai.column_name, {
                as: 'id',
              })) as any
            )[0].id;
          }
          response = await this.readByPk(
            id,
            false,
            {},
            { ignoreView: true, getHiddenColumn: true },
          );
        } else {
          response = data;
        }
      } else if (ai) {
        const id = Array.isArray(response)
          ? response?.[0]?.[ai.title]
          : response?.[ai.title];
        response = (await canUseOptimisedQuery({
          source,
          disableOptimization,
        }))
          ? await getSingleQueryReadFn(source)({
              model: this.model,
              view,
              id,
              params: {},
              source,
              getHiddenColumn: true,
            })
          : await this.readByPk(
              id,
              false,
              {},
              { ignoreView: true, getHiddenColumn: true },
            );
      }

      await this.afterInsert(response, trx, cookie);
      return Array.isArray(response) ? response[0] : response;
    } catch (e) {
      console.log(e);
      await this.errorInsert(e, data, trx, cookie);
      throw e;
    }
  }

  async updateByPk(id, data, trx?, cookie?, disableOptimization = false) {
    try {
      const updateObj = await this.model.mapAliasToColumn(
        data,
        this.clientMeta,
        this.dbDriver,
      );

      await this.validate(data);

      await this.beforeUpdate(data, trx, cookie);

      const view = await View.get(this.viewId);
      const source = await Source.get(this.model.source_id);
      const prevData = (await canUseOptimisedQuery({
        source,
        disableOptimization,
      }))
        ? await getSingleQueryReadFn(source)({
            model: this.model,
            view,
            id,
            params: {},
            source,
            getHiddenColumn: true,
          })
        : await this.readByPk(
            id,
            false,
            {},
            { ignoreView: true, getHiddenColumn: true },
          );

      const query = this.dbDriver(this.tnPath)
        .update(updateObj)
        .where(await this._wherePk(id));

      await this.execAndParse(query);

      // const newData = await this.readByPk(id, false, {}, { ignoreView: true, getHiddenColumn: true });

      // const prevData = await this.readByPk(id);

      const newData = (await canUseOptimisedQuery({
        source,
        disableOptimization,
      }))
        ? await getSingleQueryReadFn(source)({
            model: this.model,
            view,
            id,
            params: {},
            source,
            getHiddenColumn: true,
          })
        : await this.readByPk(
            id,
            false,
            {},
            { ignoreView: true, getHiddenColumn: true },
          );
      await this.afterUpdate(prevData, newData, trx, cookie, updateObj);
      return newData;
    } catch (e) {
      console.log(e);
      await this.errorUpdate(e, data, trx, cookie);
      throw e;
    }
  }

  prepareAttachmentData(data) {
    if (this.model.columns.some((c) => c.uidt === UITypes.Attachment)) {
      for (const column of this.model.columns) {
        if (column.uidt === UITypes.Attachment) {
          if (data[column.column_name]) {
            if (Array.isArray(data[column.column_name])) {
              for (let attachment of data[column.column_name]) {
                attachment = extractProps(attachment, [
                  'url',
                  'path',
                  'title',
                  'mimetype',
                  'size',
                  'icon',
                ]);
              }
            }
          }
        }
      }
    }
  }

  public async afterInsert(data: any, _trx: any, req): Promise<void> {
    await this.handleHooks('after.insert', null, data, req);
    const id = this._extractPksValues(data);
    await Audit.insert({
      fk_model_id: this.model.id,
      row_id: id,
      op_type: AuditOperationTypes.DATA,
      op_sub_type: AuditOperationSubTypes.INSERT,
      description: DOMPurify.sanitize(
        `Record with ID ${id} has been inserted into Table ${this.model.title}`,
      ),
      // details: JSON.stringify(data),
      ip: req?.clientIp,
      user: req?.user?.email,
    });

    Noco.eventEmitter.emit(HANDLE_STATS, {
      fk_model_id: this.model.id,
    });
  }

  public async afterBulkInsert(data: any[], _trx: any, req): Promise<void> {
    await this.handleHooks('after.bulkInsert', null, data, req);

    await Audit.insert({
      fk_model_id: this.model.id,
      op_type: AuditOperationTypes.DATA,
      op_sub_type: AuditOperationSubTypes.BULK_INSERT,
      description: DOMPurify.sanitize(
        `${data.length} ${
          data.length > 1 ? 'records have' : 'record has'
        } been bulk inserted in ${this.model.title}`,
      ),
      // details: JSON.stringify(data),
      ip: req?.clientIp,
      user: req?.user?.email,
    });

    Noco.eventEmitter.emit(HANDLE_STATS, {
      fk_model_id: this.model.id,
    });
  }

  public async afterDelete(data: any, _trx: any, req): Promise<void> {
    const id = req?.params?.id;
    await Audit.insert({
      fk_model_id: this.model.id,
      row_id: id,
      op_type: AuditOperationTypes.DATA,
      op_sub_type: AuditOperationSubTypes.DELETE,
      description: DOMPurify.sanitize(
        `Record with ID ${id} has been deleted in Table ${this.model.title}`,
      ),
      // details: JSON.stringify(data),
      ip: req?.clientIp,
      user: req?.user?.email,
    });
    await this.handleHooks('after.delete', null, data, req);
    Noco.eventEmitter.emit(HANDLE_STATS, {
      fk_model_id: this.model.id,
    });
  }

  public async afterBulkDelete(
    data: any,
    _trx: any,
    req,
    isBulkAllOperation = false,
  ): Promise<void> {
    let noOfDeletedRecords = data;
    if (!isBulkAllOperation) {
      noOfDeletedRecords = data.length;
      await this.handleHooks('after.bulkDelete', null, data, req);
    }

    await Audit.insert({
      fk_model_id: this.model.id,
      op_type: AuditOperationTypes.DATA,
      op_sub_type: AuditOperationSubTypes.BULK_DELETE,
      description: DOMPurify.sanitize(
        `${noOfDeletedRecords} ${
          noOfDeletedRecords > 1 ? 'records have' : 'record has'
        } been bulk deleted in ${this.model.title}`,
      ),
      // details: JSON.stringify(data),
      ip: req?.clientIp,
      user: req?.user?.email,
    });
    Noco.eventEmitter.emit(HANDLE_STATS, {
      fk_model_id: this.model.id,
    });
  }
}

export {
  BaseModelSqlv2,
  _wherePk,
  extractCondition,
  extractFilterFromXwhere,
  extractSortsObject,
  getListArgs,
};
