import { OperationRegistry } from '~/command-registry/_registry';
import { makeReplayReq } from '~/command-registry/_replay-context';
import {
  TableCreateContract,
  TableUpdateContract,
  TableDeleteContract,
} from '../operations/tables.operations';
import type { TablesService } from 'src/ee/services/tables.service';

interface SandboxColumn {
  id?: string;
  cn?: string;
  title?: string;
}

export function registerTableHandlers(svc: TablesService): void {
  OperationRegistry.register(
    TableCreateContract,
    async (ctx, params, meta) => {
      const req = makeReplayReq(meta.originalReq, meta.createdBy);

      // Thread sandbox column IDs + default-view ID into the production-side
      // table create so columns and the default grid view keep stable IDs
      // across the merge boundary (sorts/filters reference these by id).
      const extra = (meta.extra ?? {}) as {
        sandboxColumns?: SandboxColumn[];
        sandboxDefaultViewId?: string;
      };

      const replayParams = { ...params } as any;
      let colIdMap: Record<string, string> | undefined;
      if (extra.sandboxColumns?.length && replayParams.table) {
        colIdMap = {};
        for (const c of extra.sandboxColumns) {
          if (!c.id) continue;
          if (c.title) colIdMap[c.title] = c.id;
          if (c.cn) colIdMap[c.cn] = c.id;
        }
        replayParams.table = {
          ...replayParams.table,
          _sandboxColumnIds: colIdMap,
        };
      }
      if (extra.sandboxDefaultViewId && replayParams.table) {
        replayParams.table = {
          ...replayParams.table,
          _sandboxDefaultViewId: extra.sandboxDefaultViewId,
        };
      }

      // System columns (created by Column.bulkInsert, regenerated by CE
      // repopulateCreateTableSystemColumns) need the map on additionalContext.
      const replayCtx = colIdMap
        ? {
            ...ctx,
            additionalContext: {
              ...ctx.additionalContext,
              sandboxColumnIds: colIdMap,
            },
          }
        : ctx;

      return svc.tableCreate(replayCtx, { ...replayParams, req } as any);
    },
  );

  OperationRegistry.register(
    TableUpdateContract,
    async (ctx, params, meta) => {
      const req = makeReplayReq(meta.originalReq, meta.createdBy);
      return svc.tableUpdate(ctx, { ...params, req } as any);
    },
  );

  OperationRegistry.register(
    TableDeleteContract,
    async (ctx, params, meta) => {
      const req = makeReplayReq(meta.originalReq, meta.createdBy);
      return svc.tableDelete(ctx, { ...params, req } as any);
    },
  );
}
