import {
  NocoSDK,
  TriggerActivationType,
  TriggerTestMode,
  WorkflowNodeCategory,
  WorkflowNodeIntegration,
} from '@noco-integrations/core';
import type {
  WorkflowActivationContext,
  WorkflowActivationState,
  WorkflowNodeConfig,
  WorkflowNodeDefinition,
  WorkflowNodeLog,
  WorkflowNodeResult,
  WorkflowNodeRunContext,
} from '@noco-integrations/core';

interface WebhookTriggerConfig extends WorkflowNodeConfig {
  triggerId?: string;
}

export class WebhookTriggerNode extends WorkflowNodeIntegration<WebhookTriggerConfig> {
  public async definition(): Promise<WorkflowNodeDefinition> {
    return {
      id: 'core.trigger.webhook',
      title: 'When webhook received',
      description: 'Trigger workflow when a webhook request is received',
      icon: 'ncWebhook',
      category: WorkflowNodeCategory.TRIGGER,
      activationType: TriggerActivationType.WEBHOOK,
      testModes: [TriggerTestMode.LISTEN_WEBHOOK],
      ports: [{ id: 'output', direction: 'output', order: 0 }],
      documentation:
        'https://nocodb.com/docs/workflows/nodes/trigger-nodes/webhook',
      form: [],
      keywords: [
        'webhook',
        'http',
        'api',
        'trigger',
        'request',
        'post',
        'endpoint',
        'url',
      ],
    };
  }

  public async validate(_config: WebhookTriggerConfig) {
    return { valid: true, errors: [] };
  }

  /**
   * Called when workflow is published - returns activation state
   * The webhook URL is generated by workflows.service based on triggerId
   */
  public async onActivateHook(
    context: WorkflowActivationContext,
  ): Promise<WorkflowActivationState> {
    return {
      activatedAt: new Date().toISOString(),
      workflowId: context.workflowId,
      nodeId: context.nodeId,
    };
  }

  /**
   * Called when workflow is unpublished - no cleanup needed
   */
  public async onDeactivateHook(): Promise<void> {
    // No external cleanup needed for generic webhooks
  }

  public async run(ctx: WorkflowNodeRunContext): Promise<WorkflowNodeResult> {
    const logs: WorkflowNodeLog[] = [];
    const startTime = Date.now();

    try {
      const webhookData = (ctx.inputs as any)?.webhook || ctx.inputs;

      const body = webhookData?.body || {};
      const headers = webhookData?.headers || {};
      const query = webhookData?.query || {};
      const method = webhookData?.method || 'POST';

      logs.push({
        level: 'info',
        message: `Webhook received: ${method} request`,
        ts: Date.now(),
        data: {
          method,
          hasBody: Object.keys(body).length > 0,
          hasQuery: Object.keys(query).length > 0,
        },
      });

      return {
        outputs: {
          request: {
            body,
            headers,
            query,
            method,
          },
          trigger: {
            type: 'webhook-received',
            timestamp: new Date().toISOString(),
          },
        },
        status: 'success',
        logs,
        metrics: {
          executionTimeMs: Date.now() - startTime,
        },
      };
    } catch (error: any) {
      logs.push({
        level: 'error',
        message: `Webhook trigger failed: ${error.message}`,
        ts: Date.now(),
        data: error.stack,
      });

      return {
        outputs: {},
        status: 'error',
        error: {
          message: error.message || 'Webhook trigger failed',
          code: error.code,
        },
        logs,
        metrics: {
          executionTimeMs: Date.now() - startTime,
        },
      };
    }
  }

  public async generateOutputVariables(): Promise<
    NocoSDK.VariableDefinition[]
  > {
    return [
      {
        key: 'trigger',
        name: 'Trigger',
        type: NocoSDK.VariableType.Object,
        groupKey: NocoSDK.VariableGroupKey.Meta,
        extra: {
          description: 'Trigger information',
          icon: 'cellJson',
        },
        children: [
          {
            key: 'trigger.type',
            name: 'Type',
            type: NocoSDK.VariableType.String,
            groupKey: NocoSDK.VariableGroupKey.Meta,
            extra: {
              description: 'Type of trigger',
              icon: 'cellText',
            },
          },
          {
            key: 'trigger.timestamp',
            name: 'Timestamp',
            type: NocoSDK.VariableType.DateTime,
            groupKey: NocoSDK.VariableGroupKey.Meta,
            extra: {
              description: 'When the webhook was received',
              icon: 'cellDatetime',
            },
          },
        ],
      },
      {
        key: 'request',
        name: 'Request',
        type: NocoSDK.VariableType.Object,
        groupKey: NocoSDK.VariableGroupKey.Meta,
        extra: {
          description: 'Request Information',
          icon: 'ncGlobe',
        },
        children: [
          {
            key: 'request.body',
            name: 'Body',
            type: NocoSDK.VariableType.Object,
            groupKey: NocoSDK.VariableGroupKey.Fields,
            extra: {
              description: 'Request body (JSON)',
              icon: 'cellJson',
            },
          },
          {
            key: 'request.headers',
            name: 'Headers',
            type: NocoSDK.VariableType.Object,
            groupKey: NocoSDK.VariableGroupKey.Meta,
            extra: {
              description: 'Request headers',
              icon: 'cellJson',
            },
          },
          {
            key: 'request.query',
            name: 'Query Parameters',
            type: NocoSDK.VariableType.Object,
            groupKey: NocoSDK.VariableGroupKey.Meta,
            extra: {
              description: 'URL query parameters',
              icon: 'cellJson',
            },
          },
          {
            key: 'request.method',
            name: 'Method',
            type: NocoSDK.VariableType.String,
            groupKey: NocoSDK.VariableGroupKey.Meta,
            extra: {
              description: 'HTTP method (GET, POST, etc.)',
              icon: 'cellText',
            },
          },
        ],
      },
    ];
  }
}
