import type { Dirent } from 'node:fs'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join, relative, resolve } from 'node:path'
import { addTypeTemplate, defineNuxtModule, updateTemplates, useLogger } from '@nuxt/kit'

/**
 * Generates `NcTourAnchorId` — the union of every `data-tour="..."` in the
 * codebase — so `defineTour` autocompletes anchors and rejects typos, with no
 * hand-maintained list. Also writes `tours/anchors.catalog.md` for authors.
 */

/** Directories scanned for `data-tour` attributes, relative to nc-gui root. */
const SCAN_DIRS = ['components', 'ee/components', 'pages', 'ee/pages', 'layouts', 'ee/layouts']

/** Single files worth scanning outside those directories. */
const SCAN_FILES = ['app.vue']

const ATTR_RE = /data-tour\s*=\s*"([^"]+)"/g

const TYPES_FILENAME = 'types/nc-tour-anchors.d.ts'

/**
 * Recurses by hand rather than `readdir({ recursive: true })` — the @types/node
 * this workspace resolves is too old to type that overload.
 */
async function findVueFiles(dir: string): Promise<string[]> {
  let entries: Dirent[]

  try {
    entries = (await readdir(dir, { withFileTypes: true })) as Dirent[]
  } catch {
    return []
  }

  const found = await Promise.all(
    entries.map(async (entry): Promise<string[]> => {
      const full = join(dir, entry.name)

      if (entry.isDirectory()) {
        // `ee/` has its own explicit scan root.
        if (entry.name === 'node_modules' || entry.name === 'ee') return []

        return findVueFiles(full)
      }

      return entry.isFile() && entry.name.endsWith('.vue') ? [full] : []
    }),
  )

  return found.flat()
}

export interface AnchorUsage {
  anchor: string
  /** `file:line` occurrences, repo-relative. */
  locations: string[]
}

export async function collectAnchors(rootDir: string): Promise<AnchorUsage[]> {
  const nested = await Promise.all(SCAN_DIRS.map((dir) => findVueFiles(resolve(rootDir, dir))))

  const files = [...nested.flat(), ...SCAN_FILES.map((f) => resolve(rootDir, f))]

  const byAnchor = new Map<string, string[]>()

  await Promise.all(
    files.map(async (file) => {
      const source = await readFile(file, 'utf8').catch(() => '')

      // Cheap pre-filter: most files have no anchors at all.
      if (!source.includes('data-tour')) return

      source.split('\n').forEach((line, i) => {
        for (const match of line.matchAll(ATTR_RE)) {
          const anchor = match[1]?.trim()

          // Skip bound attributes (`:data-tour="expr"` produces a dynamic value
          // we can't resolve statically).
          if (!anchor || anchor.includes('{') || anchor.includes('$')) continue

          const at = `${relative(rootDir, file)}:${i + 1}`
          const existing = byAnchor.get(anchor)

          if (existing) existing.push(at)
          else byAnchor.set(anchor, [at])
        }
      })
    }),
  )

  return Array.from(byAnchor.entries())
    .map(([anchor, locations]) => ({ anchor, locations: locations.sort() }))
    .sort((a, b) => a.anchor.localeCompare(b.anchor))
}

function renderTypes(anchors: AnchorUsage[]): string {
  // Falling back to `string` keeps the build green if the scan finds nothing.
  const union = anchors.length ? anchors.map(({ anchor }) => `'${anchor}'`).join('\n  | ') : 'string'

  return `// Generated by modules/tour-anchors.ts — do not edit.
// Add \`data-tour="..."\` to an element and it appears here automatically.

declare global {
  /** Every \`data-tour\` value present in the codebase. */
  type NcTourAnchorId =
  | ${union}
}

export {}
`
}

function renderCatalog(anchors: AnchorUsage[]): string {
  // A list rather than a table: table cells can't hold newlines, so multiple
  // locations would need `<br>`, and this file is mostly read as raw text.
  const body = anchors
    .map(({ anchor, locations }) => [`- \`${anchor}\``, ...locations.map((l) => `    - ${l}`)].join('\n'))
    .join('\n')

  return `# Tour anchor catalog

Generated by \`modules/tour-anchors.ts\` — do not edit.

Every element a tour can point at. Use these values for \`anchor:\` in a tour
definition (see \`tours/README.md\`). To add one, put \`data-tour="my-thing"\` on
the element; it appears here on the next build.

An anchor listed in two files is usually a CE component and its \`ee/\` override.
Both need the attribute, or it fails to render in one edition.

${body || '_No anchors found._'}
`
}

export default defineNuxtModule({
  meta: {
    name: 'nc-tour-anchors',
    configKey: 'tourAnchors',
  },

  async setup(_options, nuxt) {
    const logger = useLogger('nc-tour-anchors')

    // In the EE build `srcDir` is packages/nc-gui/ee, but anchors live in both
    // the CE root and ee/. Scan from the CE root either way.
    const rootDir = nuxt.options.srcDir.replace(/[/\\]ee[/\\]?$/, '')

    let anchors: AnchorUsage[] = []

    async function scan() {
      anchors = await collectAnchors(rootDir)

      await writeFile(resolve(rootDir, 'tours/anchors.catalog.md'), renderCatalog(anchors), 'utf8')

      return anchors
    }

    await scan()

    logger.info(`found ${anchors.length} tour anchor${anchors.length === 1 ? '' : 's'}`)

    addTypeTemplate({
      filename: TYPES_FILENAME,
      getContents: () => renderTypes(anchors),
    })

    // Keep the union live while authoring, without a dev-server restart.
    nuxt.hook('builder:watch', async (_event, path) => {
      if (!path.endsWith('.vue')) return

      const before = anchors.map((a) => a.anchor).join()

      await scan()

      if (anchors.map((a) => a.anchor).join() === before) return

      logger.info(`tour anchors changed (${anchors.length}) — regenerating types`)

      // Regenerate only this template. `builder:generateApp` rebuilds the whole
      // .nuxt app, which is heavy per keystroke and clobbers artefacts the dev
      // server owns — vite-plugin-pwa's `dev-sw-dist/sw.js` among them.
      await updateTemplates({ filter: (template) => template.filename === TYPES_FILENAME })
    })
  },
})
