import MdiCheckBold from '~icons/mdi/check-bold'
import MdiCropSquare from '~icons/mdi/crop-square'
import MdiCheckCircleOutline from '~icons/mdi/check-circle-outline'
import MdiCheckboxBlankCircleOutline from '~icons/mdi/checkbox-blank-circle-outline'
import MdiStar from '~icons/mdi/star'
import MdiStarOutline from '~icons/mdi/star-outline'
import MdiHeart from '~icons/mdi/heart'
import MdiHeartOutline from '~icons/mdi/heart-outline'
import MdiMoonFull from '~icons/mdi/moon-full'
import MdiMoonNew from '~icons/mdi/moon-new'
import MdiThumbUp from '~icons/mdi/thumb-up'
import MdiThumbUpOutline from '~icons/mdi/thumb-up-outline'
import MdiFlag from '~icons/mdi/flag'
import MdiFlagOutline from '~icons/mdi/flag-outline'
import MdiTableLarge from '~icons/mdi/table-large'
import MdiEyeCircleOutline from '~icons/mdi/eye-circle-outline'
import MdiAccountGroup from '~icons/mdi/account-group'
import PhTableThin from '~icons/ph/TableThin'

import PhLockIcon from '~icons/ph/lock-key-thin'
import PhAccountIcon from '~icons/ph/user'
import PhUsersThreeThin from '~icons/ph/users-three-thin'
import PhDownloadThin from '~icons/ph/arrow-line-down-thin'
import PhUploadThin from '~icons/ph/arrow-line-up-thin'
import PhHookThin from '~icons/ph/anchor-thin'
import PhTreeThin from '~icons/ph/tree-structure-thin'
import PhPlusThin from '~icons/ph/plus-thin'
import PhSearchThin from '~icons/ph/magnifying-glass-thin'
import PhCopySimpleThin from '~icons/ph/copy-simple-thin'
import PhClipboardThin from '~icons/ph/clipboard-text-thin'
import PhGearThin from '~icons/ph/gear-thin'
import PhImageThin from '~icons/ph/image-thin'
import PhHardDriveThin from '~icons/ph/hard-drives-thin'
import PhBookThin from '~icons/ph/book-bookmark-thin'
import PhCaretDownLight from '~icons/ph/caret-down-light'
import PhDotsThreeOutlineVerticalThin from '~icons/ph/dots-three-outline-vertical-thin'
import PhExcelThin from '~icons/ph/microsoft-excel-logo-thin'
import PhCsvThin from '~icons/ph/file-csv-thin'
import PhBracketsCurlyThin from '~icons/ph/brackets-curly-thin'
import PhTrashThin from '~icons/ph/trash-thin'
import PhPencilSimpleThin from '~icons/ph/pencil-simple-thin'
import PhLinkSimpleThin from '~icons/ph/link-simple-thin'
import PhListMagnifyingGlassThin from '~icons/ph/list-magnifying-glass-thin'
import PhStringIcon from '~icons/ph/text-aa-thin'
import PhTextAreaIcon from '~icons/ph/text-align-left-thin'
import FilePhoneIcon from '~icons/ph/phone-call-thin'
import KeyIcon from '~icons/ph/key-thin'
import ClockIcon from '~icons/ph/alarm-thin'
import WebIcon from '~icons/ph/planet-thin'
import BooleanIcon from '~icons/ph/check-square-thin'
import CalendarIcon from '~icons/ph/calendar-blank-thin'
import SingleSelectIcon from '~icons/ph/caret-circle-down-thin'
import MultiSelectIcon from '~icons/ph/list-bullets-thin'
import DatetimeIcon from '~icons/ph/calendar-thin'
import GeoDataIcon from '~icons/ph/map-pin-thin'
import RatingIcon from '~icons/ph/star-thin'
import GenericIcon from '~icons/ph/square-thin'
import NumericIcon from '~icons/ph/number-square-one-thin'
import EmailIcon from '~icons/ph/envelope-thin'
import CurrencyIcon from '~icons/ph/currency-circle-dollar-thin'
import PercentIcon from '~icons/ph/percent-thin'
import DecimalIcon from '~icons/mdi/decimal'
import SpecificDBTypeIcon from '~icons/ph/database-thin'
import DurationIcon from '~icons/ph/clock-clockwise-thin'
import PhFunctiontone from '~icons/ph/function-thin'
import PhQrCodeThin from '~icons/ph/qr-code-thin'
import PhBarcodeThin from '~icons/ph/barcode-thin'
import PhCalculatorThin from '~icons/ph/calculator-thin'
import PhEyeSlashThin from '~icons/ph/eye-slash-thin'
import PhEyeThin from '~icons/ph/eye-thin'
import PhExpandThin from '~icons/ph/arrows-out-simple-thin'
import PhLifebuoyThin from '~icons/ph/lifebuoy-thin'
import PhCheckThin from '~icons/ph/check-thin'
import PhFolderLockThin from '~icons/ph/folder-simple-lock-thin'
import MdiDatabaseSync from '~icons/mdi/database-sync'
import PhWarningThin from '~icons/ph/warning-thin'
import HMIcon from '~icons/mdi/table-arrow-right'
import BTIcon from '~icons/mdi/table-arrow-left'
import MMIcon from '~icons/mdi/table-network'

export const iconMap = {
  'mdi-check-bold': MdiCheckBold,
  'mdi-crop-square': MdiCropSquare,
  'mdi-check-circle-outline': MdiCheckCircleOutline,
  'mdi-checkbox-blank-circle-outline': MdiCheckboxBlankCircleOutline,
  'mdi-star': MdiStar,
  'mdi-star-outline': MdiStarOutline,
  'mdi-heart': MdiHeart,
  'mdi-heart-outline': MdiHeartOutline,
  'mdi-moon-full': MdiMoonFull,
  'mdi-moon-new': MdiMoonNew,
  'mdi-thumb-up': MdiThumbUp,
  'mdi-thumb-up-outline': MdiThumbUpOutline,
  'mdi-flag': MdiFlag,
  'mdi-flag-outline': MdiFlagOutline,
  'mdi-table-large': PhTableThin,
  'mdi-eye-circle-outline': PhEyeThin,
  'mdi-account-group': PhUsersThreeThin,

  'lock-icon': PhLockIcon,
  'account-icon': PhAccountIcon,
  'users-icon': PhUsersThreeThin,
  'download': PhDownloadThin,
  'upload': PhUploadThin,
  'hook': PhHookThin,
  'erd': PhTreeThin,
  'plus': PhPlusThin,
  'search': PhSearchThin,
  'copy': PhCopySimpleThin,
  'clipboard': PhClipboardThin,
  'settings': PhGearThin,
  'image': PhImageThin,
  'datasource': PhHardDriveThin,
  'book': PhBookThin,
  'arrow-down': PhCaretDownLight,
  'three-dot-vertical': PhDotsThreeOutlineVerticalThin,
  'table': PhTableThin,
  'excel': PhExcelThin,
  'csv': PhCsvThin,
  'code': PhBracketsCurlyThin,
  'delete': PhTrashThin,
  'edit': PhPencilSimpleThin,
  'link': PhLinkSimpleThin,
  'lookup': PhListMagnifyingGlassThin,
  'text': PhStringIcon,
  'long-text': PhTextAreaIcon,
  'clock': ClockIcon,
  'web': WebIcon,
  'boolean': BooleanIcon,
  'calendar': CalendarIcon,
  'single-select': SingleSelectIcon,
  'multi-select': MultiSelectIcon,
  'datetime': DatetimeIcon,
  'geo-data': GeoDataIcon,
  'rating': RatingIcon,
  'generic': GenericIcon,
  'numeric': NumericIcon,
  'email': EmailIcon,
  'currency': CurrencyIcon,
  'percent': PercentIcon,
  'decimal': DecimalIcon,
  'specific-db-type': SpecificDBTypeIcon,
  'duration': DurationIcon,
  'file-phone': FilePhoneIcon,
  'formula': PhFunctiontone,
  'key': KeyIcon,
  'json': PhBracketsCurlyThin,
  'qr-code': PhQrCodeThin,
  'bar-code': PhBarcodeThin,
  'calculator': PhCalculatorThin,
  'rollup': PhLifebuoyThin,
  'eye': PhEyeThin,
  'eye-slash': PhEyeSlashThin,
  'expand': PhExpandThin,
  'check': PhCheckThin,
  'acl': PhFolderLockThin,
  'sync': MdiDatabaseSync,
  'warning': PhWarningThin,

  'mm': MMIcon,
  'hm': HMIcon,
  'bt': BTIcon,
} as const

export const getMdiIcon = (type: string): any => {
  switch (type) {
    case 'mdi-check-bold':
      return MdiCheckBold
    case 'mdi-crop-square':
      return MdiCropSquare
    case 'mdi-check-circle-outline':
      return MdiCheckCircleOutline
    case 'mdi-checkbox-blank-circle-outline':
      return MdiCheckboxBlankCircleOutline
    case 'mdi-star':
      return MdiStar
    case 'mdi-star-outline':
      return MdiStarOutline
    case 'mdi-heart':
      return MdiHeart
    case 'mdi-heart-outline':
      return MdiHeartOutline
    case 'mdi-moon-full':
      return MdiMoonFull
    case 'mdi-moon-new':
      return MdiMoonNew
    case 'mdi-thumb-up':
      return MdiThumbUp
    case 'mdi-thumb-up-outline':
      return MdiThumbUpOutline
    case 'mdi-flag':
      return MdiFlag
    case 'mdi-flag-outline':
      return MdiFlagOutline
    case 'mdi-table-large':
      return MdiTableLarge
    case 'mdi-eye-circle-outline':
      return MdiEyeCircleOutline
    case 'mdi-account-group':
      return MdiAccountGroup
  }
}

export const emojiIcons = [
  'grinning-face',
  'grinning-face-with-big-eyes',
  'grinning-face-with-smiling-eyes',
  'beaming-face-with-smiling-eyes',
  'grinning-squinting-face',
  'grinning-face-with-sweat',
  'rolling-on-the-floor-laughing',
  'face-with-tears-of-joy',
  'slightly-smiling-face',
  'upside-down-face',
  'winking-face',
  'smiling-face-with-smiling-eyes',
  'smiling-face-with-halo',
  'smiling-face-with-heart-eyes',
  'face-blowing-a-kiss',
  'kissing-face',
  'smiling-face',
  'kissing-face-with-closed-eyes',
  'kissing-face-with-smiling-eyes',
  'face-savoring-food',
  'face-with-tongue',
  'winking-face-with-tongue',
  'squinting-face-with-tongue',
  'money-mouth-face',
  'hugging-face',
  'thinking-face',
  'zipper-mouth-face',
  'neutral-face',
  'expressionless-face',
  'face-without-mouth',
  'smirking-face',
  'unamused-face',
  'face-with-rolling-eyes',
  'grimacing-face',
  'lying-face',
  'relieved-face',
  'pensive-face',
  'sleepy-face',
  'drooling-face',
  'sleeping-face',
  'face-with-medical-mask',
  'face-with-thermometer',
  'face-with-head-bandage',
  'nauseated-face',
  'sneezing-face',
  'dizzy-face',
  'cowboy-hat-face',
  'smiling-face-with-sunglasses',
  'nerd-face',
  'confused-face',
  'worried-face',
  'slightly-frowning-face',
  'frowning-face',
  'face-with-open-mouth',
  'hushed-face',
  'astonished-face',
  'flushed-face',
  'frowning-face-with-open-mouth',
  'anguished-face',
  'fearful-face',
  'anxious-face-with-sweat',
  'sad-but-relieved-face',
  'crying-face',
  'loudly-crying-face',
  'face-screaming-in-fear',
  'confounded-face',
  'persevering-face',
  'disappointed-face',
  'downcast-face-with-sweat',
  'weary-face',
  'tired-face',
  'face-with-steam-from-nose',
  'pouting-face',
  'angry-face',
  'smiling-face-with-horns',
  'angry-face-with-horns',
  'skull',
  'skull-and-crossbones',
  'pile-of-poo',
  'clown-face',
  'ogre',
  'goblin',
  'ghost',
  'alien',
  'alien-monster',
  'see-no-evil-monkey',
  'hear-no-evil-monkey',
  'speak-no-evil-monkey',
  'kiss-mark',
  'love-letter',
  'heart-with-arrow',
  'heart-with-ribbon',
  'sparkling-heart',
  'growing-heart',
  'beating-heart',
  'revolving-hearts',
  'two-hearts',
  'heart-decoration',
  'broken-heart',
  'red-heart',
  'yellow-heart',
  'green-heart',
  'blue-heart',
  'purple-heart',
  'black-heart',
  'hundred-points',
  'anger-symbol',
  'collision',
  'dizzy',
  'sweat-droplets',
  'dashing-away',
  'hole',
  'bomb',
  'speech-balloon',
  'eye-in-speech-bubble',
  'left-speech-bubble',
  'right-anger-bubble',
  'thought-balloon',
  'zzz',
  'waving-hand',
  'waving-hand-light-skin-tone',
  'waving-hand-medium-light-skin-tone',
  'waving-hand-medium-skin-tone',
  'waving-hand-medium-dark-skin-tone',
  'waving-hand-dark-skin-tone',
  'raised-back-of-hand',
  'raised-back-of-hand-light-skin-tone',
  'raised-back-of-hand-medium-light-skin-tone',
  'raised-back-of-hand-medium-skin-tone',
  'raised-back-of-hand-medium-dark-skin-tone',
  'raised-back-of-hand-dark-skin-tone',
  'hand-with-fingers-splayed',
  'hand-with-fingers-splayed-light-skin-tone',
  'hand-with-fingers-splayed-medium-light-skin-tone',
  'hand-with-fingers-splayed-medium-skin-tone',
  'hand-with-fingers-splayed-medium-dark-skin-tone',
  'hand-with-fingers-splayed-dark-skin-tone',
  'raised-hand',
  'raised-hand-light-skin-tone',
  'raised-hand-medium-light-skin-tone',
  'raised-hand-medium-skin-tone',
  'raised-hand-medium-dark-skin-tone',
  'raised-hand-dark-skin-tone',
  'vulcan-salute',
  'vulcan-salute-light-skin-tone',
  'vulcan-salute-medium-light-skin-tone',
  'vulcan-salute-medium-skin-tone',
  'vulcan-salute-medium-dark-skin-tone',
  'vulcan-salute-dark-skin-tone',
  'ok-hand',
  'ok-hand-light-skin-tone',
  'ok-hand-medium-light-skin-tone',
  'ok-hand-medium-skin-tone',
  'ok-hand-medium-dark-skin-tone',
  'ok-hand-dark-skin-tone',
  'victory-hand',
  'victory-hand-light-skin-tone',
  'victory-hand-medium-light-skin-tone',
  'victory-hand-medium-skin-tone',
  'victory-hand-medium-dark-skin-tone',
  'victory-hand-dark-skin-tone',
  'crossed-fingers',
  'crossed-fingers-light-skin-tone',
  'crossed-fingers-medium-light-skin-tone',
  'crossed-fingers-medium-skin-tone',
  'crossed-fingers-medium-dark-skin-tone',
  'crossed-fingers-dark-skin-tone',
  'sign-of-the-horns',
  'sign-of-the-horns-light-skin-tone',
  'sign-of-the-horns-medium-light-skin-tone',
  'sign-of-the-horns-medium-skin-tone',
  'sign-of-the-horns-medium-dark-skin-tone',
  'sign-of-the-horns-dark-skin-tone',
  'call-me-hand',
  'call-me-hand-light-skin-tone',
  'call-me-hand-medium-light-skin-tone',
  'call-me-hand-medium-skin-tone',
  'call-me-hand-medium-dark-skin-tone',
  'call-me-hand-dark-skin-tone',
  'backhand-index-pointing-left',
  'backhand-index-pointing-left-light-skin-tone',
  'backhand-index-pointing-left-medium-light-skin-tone',
  'backhand-index-pointing-left-medium-skin-tone',
  'backhand-index-pointing-left-medium-dark-skin-tone',
  'backhand-index-pointing-left-dark-skin-tone',
  'backhand-index-pointing-right',
  'backhand-index-pointing-right-light-skin-tone',
  'backhand-index-pointing-right-medium-light-skin-tone',
  'backhand-index-pointing-right-medium-skin-tone',
  'backhand-index-pointing-right-medium-dark-skin-tone',
  'backhand-index-pointing-right-dark-skin-tone',
  'backhand-index-pointing-up',
  'backhand-index-pointing-up-light-skin-tone',
  'backhand-index-pointing-up-medium-light-skin-tone',
  'backhand-index-pointing-up-medium-skin-tone',
  'backhand-index-pointing-up-medium-dark-skin-tone',
  'backhand-index-pointing-up-dark-skin-tone',
  'middle-finger',
  'middle-finger-light-skin-tone',
  'middle-finger-medium-light-skin-tone',
  'middle-finger-medium-skin-tone',
  'middle-finger-medium-dark-skin-tone',
  'middle-finger-dark-skin-tone',
  'backhand-index-pointing-down',
  'backhand-index-pointing-down-light-skin-tone',
  'backhand-index-pointing-down-medium-light-skin-tone',
  'backhand-index-pointing-down-medium-skin-tone',
  'backhand-index-pointing-down-medium-dark-skin-tone',
  'backhand-index-pointing-down-dark-skin-tone',
  'index-pointing-up',
  'index-pointing-up-light-skin-tone',
  'index-pointing-up-medium-light-skin-tone',
  'index-pointing-up-medium-skin-tone',
  'index-pointing-up-medium-dark-skin-tone',
  'index-pointing-up-dark-skin-tone',
  'thumbs-up',
  'thumbs-up-light-skin-tone',
  'thumbs-up-medium-light-skin-tone',
  'thumbs-up-medium-skin-tone',
  'thumbs-up-medium-dark-skin-tone',
  'thumbs-up-dark-skin-tone',
  'thumbs-down',
  'thumbs-down-light-skin-tone',
  'thumbs-down-medium-light-skin-tone',
  'thumbs-down-medium-skin-tone',
  'thumbs-down-medium-dark-skin-tone',
  'thumbs-down-dark-skin-tone',
  'raised-fist',
  'raised-fist-light-skin-tone',
  'raised-fist-medium-light-skin-tone',
  'raised-fist-medium-skin-tone',
  'raised-fist-medium-dark-skin-tone',
  'raised-fist-dark-skin-tone',
  'oncoming-fist',
  'oncoming-fist-light-skin-tone',
  'oncoming-fist-medium-light-skin-tone',
  'oncoming-fist-medium-skin-tone',
  'oncoming-fist-medium-dark-skin-tone',
  'oncoming-fist-dark-skin-tone',
  'left-facing-fist',
  'left-facing-fist-light-skin-tone',
  'left-facing-fist-medium-light-skin-tone',
  'left-facing-fist-medium-skin-tone',
  'left-facing-fist-medium-dark-skin-tone',
  'left-facing-fist-dark-skin-tone',
  'right-facing-fist',
  'right-facing-fist-light-skin-tone',
  'right-facing-fist-medium-light-skin-tone',
  'right-facing-fist-medium-skin-tone',
  'right-facing-fist-medium-dark-skin-tone',
  'right-facing-fist-dark-skin-tone',
  'clapping-hands',
  'clapping-hands-light-skin-tone',
  'clapping-hands-medium-light-skin-tone',
  'clapping-hands-medium-skin-tone',
  'clapping-hands-medium-dark-skin-tone',
  'clapping-hands-dark-skin-tone',
  'raising-hands',
  'raising-hands-light-skin-tone',
  'raising-hands-medium-light-skin-tone',
  'raising-hands-medium-skin-tone',
  'raising-hands-medium-dark-skin-tone',
  'raising-hands-dark-skin-tone',
  'open-hands',
  'open-hands-light-skin-tone',
  'open-hands-medium-light-skin-tone',
  'open-hands-medium-skin-tone',
  'open-hands-medium-dark-skin-tone',
  'open-hands-dark-skin-tone',
  'handshake',
  'handshake-light-skin-tone',
  'handshake-medium-light-skin-tone',
  'handshake-medium-skin-tone',
  'handshake-medium-dark-skin-tone',
  'handshake-dark-skin-tone',
  'folded-hands',
  'folded-hands-light-skin-tone',
  'folded-hands-medium-light-skin-tone',
  'folded-hands-medium-skin-tone',
  'folded-hands-medium-dark-skin-tone',
  'folded-hands-dark-skin-tone',
  'writing-hand',
  'writing-hand-light-skin-tone',
  'writing-hand-medium-light-skin-tone',
  'writing-hand-medium-skin-tone',
  'writing-hand-medium-dark-skin-tone',
  'writing-hand-dark-skin-tone',
  'nail-polish',
  'nail-polish-light-skin-tone',
  'nail-polish-medium-light-skin-tone',
  'nail-polish-medium-skin-tone',
  'nail-polish-medium-dark-skin-tone',
  'nail-polish-dark-skin-tone',
  'selfie',
  'selfie-light-skin-tone',
  'selfie-medium-light-skin-tone',
  'selfie-medium-skin-tone',
  'selfie-medium-dark-skin-tone',
  'selfie-dark-skin-tone',
  'flexed-biceps',
  'flexed-biceps-light-skin-tone',
  'flexed-biceps-medium-light-skin-tone',
  'flexed-biceps-medium-skin-tone',
  'flexed-biceps-medium-dark-skin-tone',
  'flexed-biceps-dark-skin-tone',
  'ear',
  'ear-light-skin-tone',
  'ear-medium-light-skin-tone',
  'ear-medium-skin-tone',
  'ear-medium-dark-skin-tone',
  'ear-dark-skin-tone',
  'nose',
  'nose-light-skin-tone',
  'nose-medium-light-skin-tone',
  'nose-medium-skin-tone',
  'nose-medium-dark-skin-tone',
  'nose-dark-skin-tone',
  'eyes',
  'eye',
  'tongue',
  'mouth',
  'baby',
  'baby-light-skin-tone',
  'baby-medium-light-skin-tone',
  'baby-medium-skin-tone',
  'baby-medium-dark-skin-tone',
  'baby-dark-skin-tone',
  'boy',
  'boy-light-skin-tone',
  'boy-medium-light-skin-tone',
  'boy-medium-skin-tone',
  'boy-medium-dark-skin-tone',
  'boy-dark-skin-tone',
  'girl',
  'girl-light-skin-tone',
  'girl-medium-light-skin-tone',
  'girl-medium-skin-tone',
  'girl-medium-dark-skin-tone',
  'girl-dark-skin-tone',
  'man',
  'man-light-skin-tone',
  'man-medium-light-skin-tone',
  'man-medium-skin-tone',
  'man-medium-dark-skin-tone',
  'man-dark-skin-tone',
  'woman',
  'woman-light-skin-tone',
  'woman-medium-light-skin-tone',
  'woman-medium-skin-tone',
  'woman-medium-dark-skin-tone',
  'woman-dark-skin-tone',
  'old-man',
  'old-man-light-skin-tone',
  'old-man-medium-light-skin-tone',
  'old-man-medium-skin-tone',
  'old-man-medium-dark-skin-tone',
  'old-man-dark-skin-tone',
  'old-woman',
  'old-woman-light-skin-tone',
  'old-woman-medium-light-skin-tone',
  'old-woman-medium-skin-tone',
  'old-woman-medium-dark-skin-tone',
  'old-woman-dark-skin-tone',
  'person-frowning',
  'person-frowning-light-skin-tone',
  'person-frowning-medium-light-skin-tone',
  'person-frowning-medium-skin-tone',
  'person-frowning-medium-dark-skin-tone',
  'person-frowning-dark-skin-tone',
  'person-pouting',
  'person-pouting-light-skin-tone',
  'person-pouting-medium-light-skin-tone',
  'person-pouting-medium-skin-tone',
  'person-pouting-medium-dark-skin-tone',
  'person-pouting-dark-skin-tone',
  'person-gesturing-no',
  'person-gesturing-no-light-skin-tone',
  'person-gesturing-no-medium-light-skin-tone',
  'person-gesturing-no-medium-skin-tone',
  'person-gesturing-no-medium-dark-skin-tone',
  'person-gesturing-no-dark-skin-tone',
  'person-gesturing-ok',
  'person-gesturing-ok-light-skin-tone',
  'person-gesturing-ok-medium-light-skin-tone',
  'person-gesturing-ok-medium-skin-tone',
  'person-gesturing-ok-medium-dark-skin-tone',
  'person-gesturing-ok-dark-skin-tone',
  'person-tipping-hand',
  'person-tipping-hand-light-skin-tone',
  'person-tipping-hand-medium-light-skin-tone',
  'person-tipping-hand-medium-skin-tone',
  'person-tipping-hand-medium-dark-skin-tone',
  'person-tipping-hand-dark-skin-tone',
  'person-raising-hand',
  'person-raising-hand-light-skin-tone',
  'person-raising-hand-medium-light-skin-tone',
  'person-raising-hand-medium-skin-tone',
  'person-raising-hand-medium-dark-skin-tone',
  'person-raising-hand-dark-skin-tone',
  'person-bowing',
  'person-bowing-light-skin-tone',
  'person-bowing-medium-light-skin-tone',
  'person-bowing-medium-skin-tone',
  'person-bowing-medium-dark-skin-tone',
  'person-bowing-dark-skin-tone',
  'person-facepalming',
  'person-facepalming-light-skin-tone',
  'person-facepalming-medium-light-skin-tone',
  'person-facepalming-medium-skin-tone',
  'person-facepalming-medium-dark-skin-tone',
  'person-facepalming-dark-skin-tone',
  'person-shrugging',
  'person-shrugging-light-skin-tone',
  'person-shrugging-medium-light-skin-tone',
  'person-shrugging-medium-skin-tone',
  'person-shrugging-medium-dark-skin-tone',
  'person-shrugging-dark-skin-tone',
  'police-officer',
  'police-officer-light-skin-tone',
  'police-officer-medium-light-skin-tone',
  'police-officer-medium-skin-tone',
  'police-officer-medium-dark-skin-tone',
  'police-officer-dark-skin-tone',
  'detective',
  'detective-light-skin-tone',
  'detective-medium-light-skin-tone',
  'detective-medium-skin-tone',
  'detective-medium-dark-skin-tone',
  'detective-dark-skin-tone',
  'guard',
  'guard-light-skin-tone',
  'guard-medium-light-skin-tone',
  'guard-medium-skin-tone',
  'guard-medium-dark-skin-tone',
  'guard-dark-skin-tone',
  'construction-worker',
  'construction-worker-light-skin-tone',
  'construction-worker-medium-light-skin-tone',
  'construction-worker-medium-skin-tone',
  'construction-worker-medium-dark-skin-tone',
  'construction-worker-dark-skin-tone',
  'prince',
  'prince-light-skin-tone',
  'prince-medium-light-skin-tone',
  'prince-medium-skin-tone',
  'prince-medium-dark-skin-tone',
  'prince-dark-skin-tone',
  'princess',
  'princess-light-skin-tone',
  'princess-medium-light-skin-tone',
  'princess-medium-skin-tone',
  'princess-medium-dark-skin-tone',
  'princess-dark-skin-tone',
  'person-wearing-turban',
  'person-wearing-turban-light-skin-tone',
  'person-wearing-turban-medium-light-skin-tone',
  'person-wearing-turban-medium-skin-tone',
  'person-wearing-turban-medium-dark-skin-tone',
  'person-wearing-turban-dark-skin-tone',
  'man-in-tuxedo',
  'man-in-tuxedo-light-skin-tone',
  'man-in-tuxedo-medium-light-skin-tone',
  'man-in-tuxedo-medium-skin-tone',
  'man-in-tuxedo-medium-dark-skin-tone',
  'man-in-tuxedo-dark-skin-tone',
  'pregnant-woman',
  'pregnant-woman-light-skin-tone',
  'pregnant-woman-medium-light-skin-tone',
  'pregnant-woman-medium-skin-tone',
  'pregnant-woman-medium-dark-skin-tone',
  'pregnant-woman-dark-skin-tone',
  'baby-angel',
  'baby-angel-light-skin-tone',
  'baby-angel-medium-light-skin-tone',
  'baby-angel-medium-skin-tone',
  'baby-angel-medium-dark-skin-tone',
  'baby-angel-dark-skin-tone',
  'santa-claus',
  'santa-claus-light-skin-tone',
  'santa-claus-medium-light-skin-tone',
  'santa-claus-medium-skin-tone',
  'santa-claus-medium-dark-skin-tone',
  'santa-claus-dark-skin-tone',
  'mrs-claus',
  'mrs-claus-light-skin-tone',
  'mrs-claus-medium-light-skin-tone',
  'mrs-claus-medium-skin-tone',
  'mrs-claus-medium-dark-skin-tone',
  'mrs-claus-dark-skin-tone',
  'person-getting-massage',
  'person-getting-massage-light-skin-tone',
  'person-getting-massage-medium-light-skin-tone',
  'person-getting-massage-medium-skin-tone',
  'person-getting-massage-medium-dark-skin-tone',
  'person-getting-massage-dark-skin-tone',
  'person-getting-haircut',
  'person-getting-haircut-light-skin-tone',
  'person-getting-haircut-medium-light-skin-tone',
  'person-getting-haircut-medium-skin-tone',
  'person-getting-haircut-medium-dark-skin-tone',
  'person-getting-haircut-dark-skin-tone',
  'person-walking',
  'person-walking-light-skin-tone',
  'person-walking-medium-light-skin-tone',
  'person-walking-medium-skin-tone',
  'person-walking-medium-dark-skin-tone',
  'person-walking-dark-skin-tone',
  'person-running',
  'person-running-light-skin-tone',
  'person-running-medium-light-skin-tone',
  'person-running-medium-skin-tone',
  'person-running-medium-dark-skin-tone',
  'person-running-dark-skin-tone',
  'woman-dancing',
  'woman-dancing-light-skin-tone',
  'woman-dancing-medium-light-skin-tone',
  'woman-dancing-medium-skin-tone',
  'woman-dancing-medium-dark-skin-tone',
  'woman-dancing-dark-skin-tone',
  'man-dancing',
  'man-dancing-light-skin-tone',
  'man-dancing-medium-light-skin-tone',
  'man-dancing-medium-skin-tone',
  'man-dancing-medium-dark-skin-tone',
  'man-dancing-dark-skin-tone',
  'people-with-bunny-ears',
  'person-fencing',
  'horse-racing',
  'horse-racing-light-skin-tone',
  'horse-racing-medium-light-skin-tone',
  'horse-racing-medium-skin-tone',
  'horse-racing-medium-dark-skin-tone',
  'horse-racing-dark-skin-tone',
  'skier',
  'snowboarder',
  'person-golfing',
  'person-surfing',
  'person-surfing-light-skin-tone',
  'person-surfing-medium-light-skin-tone',
  'person-surfing-medium-skin-tone',
  'person-surfing-medium-dark-skin-tone',
  'person-surfing-dark-skin-tone',
  'person-rowing-boat',
  'person-rowing-boat-light-skin-tone',
  'person-rowing-boat-medium-light-skin-tone',
  'person-rowing-boat-medium-skin-tone',
  'person-rowing-boat-medium-dark-skin-tone',
  'person-rowing-boat-dark-skin-tone',
  'person-swimming',
  'person-swimming-light-skin-tone',
  'person-swimming-medium-light-skin-tone',
  'person-swimming-medium-skin-tone',
  'person-swimming-medium-dark-skin-tone',
  'person-swimming-dark-skin-tone',
  'person-bouncing-ball',
  'person-bouncing-ball-light-skin-tone',
  'person-bouncing-ball-medium-light-skin-tone',
  'person-bouncing-ball-medium-skin-tone',
  'person-bouncing-ball-medium-dark-skin-tone',
  'person-bouncing-ball-dark-skin-tone',
  'person-lifting-weights',
  'person-lifting-weights-light-skin-tone',
  'person-lifting-weights-medium-light-skin-tone',
  'person-lifting-weights-medium-skin-tone',
  'person-lifting-weights-medium-dark-skin-tone',
  'person-lifting-weights-dark-skin-tone',
  'person-biking',
  'person-biking-light-skin-tone',
  'person-biking-medium-light-skin-tone',
  'person-biking-medium-skin-tone',
  'person-biking-medium-dark-skin-tone',
  'person-biking-dark-skin-tone',
  'person-mountain-biking',
  'person-mountain-biking-light-skin-tone',
  'person-mountain-biking-medium-light-skin-tone',
  'person-mountain-biking-medium-skin-tone',
  'person-mountain-biking-medium-dark-skin-tone',
  'person-mountain-biking-dark-skin-tone',
  'person-cartwheeling',
  'person-cartwheeling-light-skin-tone',
  'person-cartwheeling-medium-light-skin-tone',
  'person-cartwheeling-medium-skin-tone',
  'person-cartwheeling-medium-dark-skin-tone',
  'person-cartwheeling-dark-skin-tone',
  'people-wrestling',
  'person-playing-water-polo',
  'person-playing-water-polo-light-skin-tone',
  'person-playing-water-polo-medium-light-skin-tone',
  'person-playing-water-polo-medium-skin-tone',
  'person-playing-water-polo-medium-dark-skin-tone',
  'person-playing-water-polo-dark-skin-tone',
  'person-playing-handball',
  'person-playing-handball-light-skin-tone',
  'person-playing-handball-medium-light-skin-tone',
  'person-playing-handball-medium-skin-tone',
  'person-playing-handball-medium-dark-skin-tone',
  'person-playing-handball-dark-skin-tone',
  'person-juggling',
  'person-juggling-light-skin-tone',
  'person-juggling-medium-light-skin-tone',
  'person-juggling-medium-skin-tone',
  'person-juggling-medium-dark-skin-tone',
  'person-juggling-dark-skin-tone',
  'person-taking-bath',
  'person-taking-bath-light-skin-tone',
  'person-taking-bath-medium-light-skin-tone',
  'person-taking-bath-medium-skin-tone',
  'person-taking-bath-medium-dark-skin-tone',
  'person-taking-bath-dark-skin-tone',
  'person-in-bed',
  'kiss',
  'kiss-man-man',
  'kiss-woman-woman',
  'couple-with-heart',
  'couple-with-heart-man-man',
  'couple-with-heart-woman-woman',
  'family',
  'family-man-woman-girl',
  'family-man-woman-girl-boy',
  'family-man-woman-boy-boy',
  'family-man-woman-girl-girl',
  'family-man-man-boy',
  'family-man-man-girl',
  'family-man-man-girl-boy',
  'family-man-man-boy-boy',
  'family-man-man-girl-girl',
  'family-woman-woman-boy',
  'family-woman-woman-girl',
  'family-woman-woman-girl-boy',
  'family-woman-woman-boy-boy',
  'family-woman-woman-girl-girl',
  'speaking-head',
  'bust-in-silhouette',
  'busts-in-silhouette',
  'footprints',
  'light-skin-tone',
  'medium-light-skin-tone',
  'medium-skin-tone',
  'medium-dark-skin-tone',
  'dark-skin-tone',
  'monkey-face',
  'monkey',
  'gorilla',
  'dog-face',
  'dog',
  'poodle',
  'wolf',
  'fox',
  'cat-face',
  'cat',
  'tiger-face',
  'tiger',
  'leopard',
  'horse-face',
  'horse',
  'deer',
  'cow-face',
  'ox',
  'water-buffalo',
  'cow',
  'pig-face',
  'pig',
  'boar',
  'pig-nose',
  'ram',
  'ewe',
  'goat',
  'camel',
  'two-hump-camel',
  'elephant',
  'rhinoceros',
  'mouse-face',
  'mouse',
  'rat',
  'rabbit-face',
  'rabbit',
  'chipmunk',
  'bat',
  'koala',
  'paw-prints',
  'turkey',
  'chicken',
  'rooster',
  'hatching-chick',
  'baby-chick',
  'front-facing-baby-chick',
  'bird',
  'penguin',
  'dove',
  'eagle',
  'duck',
  'owl',
  'crocodile',
  'turtle',
  'lizard',
  'snake',
  'dragon-face',
  'dragon',
  'spouting-whale',
  'whale',
  'dolphin',
  'fish',
  'tropical-fish',
  'blowfish',
  'shark',
  'octopus',
  'spiral-shell',
  'snail',
  'butterfly',
  'bug',
  'ant',
  'honeybee',
  'lady-beetle',
  'spider',
  'spider-web',
  'scorpion',
  'bouquet',
  'cherry-blossom',
  'white-flower',
  'rosette',
  'rose',
  'wilted-flower',
  'hibiscus',
  'sunflower',
  'blossom',
  'tulip',
  'seedling',
  'evergreen-tree',
  'deciduous-tree',
  'palm-tree',
  'cactus',
  'sheaf-of-rice',
  'herb',
  'shamrock',
  'four-leaf-clover',
  'maple-leaf',
  'fallen-leaf',
  'leaf-fluttering-in-wind',
  'grapes',
  'melon',
  'watermelon',
  'tangerine',
  'lemon',
  'banana',
  'pineapple',
  'red-apple',
  'green-apple',
  'pear',
  'peach',
  'cherries',
  'strawberry',
  'kiwi-fruit',
  'tomato',
  'avocado',
  'eggplant',
  'potato',
  'carrot',
  'ear-of-corn',
  'hot-pepper',
  'cucumber',
  'mushroom',
  'peanuts',
  'chestnut',
  'bread',
  'croissant',
  'baguette-bread',
  'pancakes',
  'cheese-wedge',
  'meat-on-bone',
  'poultry-leg',
  'bacon',
  'hamburger',
  'french-fries',
  'pizza',
  'hot-dog',
  'taco',
  'burrito',
  'stuffed-flatbread',
  'egg',
  'cooking',
  'shallow-pan-of-food',
  'pot-of-food',
  'green-salad',
  'popcorn',
  'bento-box',
  'rice-cracker',
  'rice-ball',
  'cooked-rice',
  'curry-rice',
  'steaming-bowl',
  'spaghetti',
  'roasted-sweet-potato',
  'oden',
  'sushi',
  'fried-shrimp',
  'fish-cake-with-swirl',
  'dango',
  'crab',
  'shrimp',
  'squid',
  'soft-ice-cream',
  'shaved-ice',
  'ice-cream',
  'doughnut',
  'cookie',
  'birthday-cake',
  'shortcake',
  'chocolate-bar',
  'candy',
  'lollipop',
  'custard',
  'honey-pot',
  'baby-bottle',
  'glass-of-milk',
  'hot-beverage',
  'teacup-without-handle',
  'sake',
  'bottle-with-popping-cork',
  'wine-glass',
  'cocktail-glass',
  'tropical-drink',
  'beer-mug',
  'clinking-beer-mugs',
  'clinking-glasses',
  'tumbler-glass',
  'fork-and-knife-with-plate',
  'fork-and-knife',
  'spoon',
  'kitchen-knife',
  'amphora',
  'globe-showing-europe-africa',
  'globe-showing-americas',
  'globe-showing-asia-australia',
  'globe-with-meridians',
  'world-map',
  'map-of-japan',
  'snow-capped-mountain',
  'mountain',
  'volcano',
  'mount-fuji',
  'camping',
  'beach-with-umbrella',
  'desert',
  'desert-island',
  'national-park',
  'stadium',
  'classical-building',
  'building-construction',
  'houses',
  'derelict-house',
  'house',
  'house-with-garden',
  'office-building',
  'japanese-post-office',
  'post-office',
  'hospital',
  'bank',
  'hotel',
  'love-hotel',
  'convenience-store',
  'school',
  'department-store',
  'factory',
  'japanese-castle',
  'castle',
  'wedding',
  'tokyo-tower',
  'statue-of-liberty',
  'church',
  'mosque',
  'synagogue',
  'shinto-shrine',
  'kaaba',
  'fountain',
  'tent',
  'foggy',
  'night-with-stars',
  'cityscape',
  'sunrise-over-mountains',
  'sunrise',
  'cityscape-at-dusk',
  'sunset',
  'bridge-at-night',
  'hot-springs',
  'carousel-horse',
  'ferris-wheel',
  'roller-coaster',
  'barber-pole',
  'circus-tent',
  'locomotive',
  'railway-car',
  'high-speed-train',
  'bullet-train',
  'train',
  'metro',
  'light-rail',
  'station',
  'tram',
  'monorail',
  'mountain-railway',
  'tram-car',
  'bus',
  'oncoming-bus',
  'trolleybus',
  'minibus',
  'ambulance',
  'fire-engine',
  'police-car',
  'oncoming-police-car',
  'taxi',
  'oncoming-taxi',
  'automobile',
  'oncoming-automobile',
  'sport-utility-vehicle',
  'delivery-truck',
  'articulated-lorry',
  'tractor',
  'racing-car',
  'motorcycle',
  'motor-scooter',
  'bicycle',
  'kick-scooter',
  'bus-stop',
  'motorway',
  'railway-track',
  'oil-drum',
  'fuel-pump',
  'police-car-light',
  'horizontal-traffic-light',
  'vertical-traffic-light',
  'stop-sign',
  'construction',
  'anchor',
  'sailboat',
  'canoe',
  'speedboat',
  'passenger-ship',
  'ferry',
  'motor-boat',
  'ship',
  'airplane',
  'small-airplane',
  'airplane-departure',
  'airplane-arrival',
  'seat',
  'helicopter',
  'suspension-railway',
  'mountain-cableway',
  'aerial-tramway',
  'satellite',
  'rocket',
  'bellhop-bell',
  'hourglass-done',
  'hourglass-not-done',
  'watch',
  'alarm-clock',
  'stopwatch',
  'timer-clock',
  'mantelpiece-clock',
  'twelve-oclock',
  'twelve-thirty',
  'one-oclock',
  'one-thirty',
  'two-thirty',
  'three-oclock',
  'three-thirty',
  'four-oclock',
  'four-thirty',
  'five-oclock',
  'five-thirty',
  'six-oclock',
  'six-thirty',
  'seven-oclock',
  'seven-thirty',
  'eight-oclock',
  'eight-thirty',
  'nine-oclock',
  'nine-thirty',
  'ten-oclock',
  'ten-thirty',
  'eleven-oclock',
  'eleven-thirty',
  'new-moon',
  'waxing-crescent-moon',
  'first-quarter-moon',
  'waxing-gibbous-moon',
  'full-moon',
  'waning-gibbous-moon',
  'last-quarter-moon',
  'waning-crescent-moon',
  'crescent-moon',
  'new-moon-face',
  'first-quarter-moon-face',
  'last-quarter-moon-face',
  'thermometer',
  'sun',
  'full-moon-face',
  'sun-with-face',
  'star',
  'glowing-star',
  'shooting-star',
  'milky-way',
  'cloud',
  'sun-behind-cloud',
  'cloud-with-lightning-and-rain',
  'sun-behind-small-cloud',
  'sun-behind-large-cloud',
  'sun-behind-rain-cloud',
  'cloud-with-rain',
  'cloud-with-snow',
  'cloud-with-lightning',
  'tornado',
  'fog',
  'wind-face',
  'cyclone',
  'rainbow',
  'closed-umbrella',
  'umbrella',
  'umbrella-with-rain-drops',
  'umbrella-on-ground',
  'high-voltage',
  'snowflake',
  'snowman',
  'snowman-without-snow',
  'comet',
  'fire',
  'droplet',
  'water-wave',
  'jack-o-lantern',
  'christmas-tree',
  'fireworks',
  'sparkler',
  'sparkles',
  'balloon',
  'party-popper',
  'confetti-ball',
  'tanabata-tree',
  'pine-decoration',
  'japanese-dolls',
  'carp-streamer',
  'wind-chime',
  'moon-viewing-ceremony',
  'ribbon',
  'wrapped-gift',
  'reminder-ribbon',
  'admission-tickets',
  'ticket',
  'military-medal',
  'trophy',
  'sports-medal',
  '1st-place-medal',
  '2nd-place-medal',
  '3rd-place-medal',
  'soccer-ball',
  'baseball',
  'basketball',
  'volleyball',
  'american-football',
  'rugby-football',
  'tennis',
  'bowling',
  'cricket-game',
  'field-hockey',
  'ice-hockey',
  'ping-pong',
  'badminton',
  'boxing-glove',
  'martial-arts-uniform',
  'goal-net',
  'flag-in-hole',
  'ice-skate',
  'fishing-pole',
  'running-shirt',
  'skis',
  'direct-hit',
  'pool-8-ball',
  'crystal-ball',
  'video-game',
  'joystick',
  'slot-machine',
  'game-die',
  'spade-suit',
  'heart-suit',
  'diamond-suit',
  'club-suit',
  'joker',
  'mahjong-red-dragon',
  'flower-playing-cards',
  'performing-arts',
  'framed-picture',
  'artist-palette',
  'glasses',
  'sunglasses',
  'necktie',
  't-shirt',
  'jeans',
  'dress',
  'kimono',
  'bikini',
  'womans-clothes',
  'purse',
  'handbag',
  'clutch-bag',
  'shopping-bags',
  'backpack',
  'mans-shoe',
  'running-shoe',
  'high-heeled-shoe',
  'womans-sandal',
  'womans-boot',
  'crown',
  'womans-hat',
  'top-hat',
  'graduation-cap',
  'rescue-workers-helmet',
  'prayer-beads',
  'lipstick',
  'ring',
  'gem-stone',
  'muted-speaker',
  'speaker-low-volume',
  'speaker-medium-volume',
  'speaker-high-volume',
  'loudspeaker',
  'megaphone',
  'postal-horn',
  'bell',
  'bell-with-slash',
  'musical-score',
  'musical-note',
  'musical-notes',
  'studio-microphone',
  'level-slider',
  'control-knobs',
  'microphone',
  'headphone',
  'radio',
  'saxophone',
  'guitar',
  'musical-keyboard',
  'trumpet',
  'violin',
  'drum',
  'mobile-phone',
  'mobile-phone-with-arrow',
  'telephone',
  'telephone-receiver',
  'pager',
  'fax-machine',
  'battery',
  'electric-plug',
  'desktop-computer',
  'printer',
  'keyboard',
  'computer-mouse',
  'trackball',
  'computer-disk',
  'floppy-disk',
  'optical-disk',
  'dvd',
  'movie-camera',
  'film-frames',
  'film-projector',
  'clapper-board',
  'television',
  'camera',
  'camera-with-flash',
  'video-camera',
  'videocassette',
  'magnifying-glass-tilted-left',
  'magnifying-glass-tilted-right',
  'candle',
  'light-bulb',
  'flashlight',
  'red-paper-lantern',
  'notebook-with-decorative-cover',
  'closed-book',
  'open-book',
  'green-book',
  'blue-book',
  'orange-book',
  'books',
  'notebook',
  'ledger',
  'page-with-curl',
  'scroll',
  'page-facing-up',
  'newspaper',
  'rolled-up-newspaper',
  'bookmark-tabs',
  'bookmark',
  'label',
  'money-bag',
  'yen-banknote',
  'dollar-banknote',
  'euro-banknote',
  'pound-banknote',
  'money-with-wings',
  'credit-card',
  'chart-increasing-with-yen',
  'envelope',
  'e-mail',
  'incoming-envelope',
  'envelope-with-arrow',
  'outbox-tray',
  'inbox-tray',
  'package',
  'closed-mailbox-with-raised-flag',
  'closed-mailbox-with-lowered-flag',
  'open-mailbox-with-raised-flag',
  'open-mailbox-with-lowered-flag',
  'postbox',
  'ballot-box-with-ballot',
  'pencil',
  'black-nib',
  'fountain-pen',
  'pen',
  'paintbrush',
  'crayon',
  'memo',
  'briefcase',
  'file-folder',
  'open-file-folder',
  'card-index-dividers',
  'calendar',
  'tear-off-calendar',
  'spiral-notepad',
  'spiral-calendar',
  'card-index',
  'chart-increasing',
  'chart-decreasing',
  'bar-chart',
  'clipboard',
  'pushpin',
  'round-pushpin',
  'paperclip',
  'linked-paperclips',
  'straight-ruler',
  'triangular-ruler',
  'scissors',
  'card-file-box',
  'file-cabinet',
  'wastebasket',
  'locked',
  'unlocked',
  'locked-with-pen',
  'locked-with-key',
  'key',
  'old-key',
  'hammer',
  'pick',
  'hammer-and-pick',
  'hammer-and-wrench',
  'dagger',
  'crossed-swords',
  'pistol',
  'bow-and-arrow',
  'shield',
  'wrench',
  'nut-and-bolt',
  'gear',
  'clamp',
  'balance-scale',
  'link',
  'chains',
  'alembic',
  'microscope',
  'telescope',
  'satellite-antenna',
  'syringe',
  'pill',
  'door',
  'bed',
  'couch-and-lamp',
  'toilet',
  'shower',
  'bathtub',
  'shopping-cart',
  'cigarette',
  'coffin',
  'funeral-urn',
  'moai',
  'atm-sign',
  'litter-in-bin-sign',
  'potable-water',
  'wheelchair-symbol',
  'mens-room',
  'womens-room',
  'restroom',
  'baby-symbol',
  'water-closet',
  'passport-control',
  'customs',
  'baggage-claim',
  'left-luggage',
  'warning',
  'children-crossing',
  'no-entry',
  'prohibited',
  'no-bicycles',
  'no-smoking',
  'no-littering',
  'non-potable-water',
  'no-pedestrians',
  'no-mobile-phones',
  'no-one-under-eighteen',
  'radioactive',
  'biohazard',
  'up-arrow',
  'up-right-arrow',
  'right-arrow',
  'down-right-arrow',
  'down-arrow',
  'down-left-arrow',
  'left-arrow',
  'up-left-arrow',
  'up-down-arrow',
  'left-right-arrow',
  'right-arrow-curving-left',
  'left-arrow-curving-right',
  'right-arrow-curving-up',
  'right-arrow-curving-down',
  'clockwise-vertical-arrows',
  'counterclockwise-arrows-button',
  'back-arrow',
  'end-arrow',
  'on-arrow',
  'soon-arrow',
  'top-arrow',
  'place-of-worship',
  'atom-symbol',
  'om',
  'star-of-david',
  'wheel-of-dharma',
  'yin-yang',
  'latin-cross',
  'orthodox-cross',
  'star-and-crescent',
  'peace-symbol',
  'menorah',
  'dotted-six-pointed-star',
  'aries',
  'taurus',
  'gemini',
  'cancer',
  'leo',
  'virgo',
  'libra',
  'scorpio',
  'sagittarius',
  'capricorn',
  'aquarius',
  'pisces',
  'ophiuchus',
  'shuffle-tracks-button',
  'repeat-button',
  'repeat-single-button',
  'play-button',
  'fast-forward-button',
  'next-track-button',
  'play-or-pause-button',
  'reverse-button',
  'fast-reverse-button',
  'last-track-button',
  'upwards-button',
  'fast-up-button',
  'downwards-button',
  'fast-down-button',
  'pause-button',
  'stop-button',
  'record-button',
  'eject-button',
  'cinema',
  'dim-button',
  'bright-button',
  'antenna-bars',
  'vibration-mode',
  'mobile-phone-off',
  'double-exclamation-mark',
  'exclamation-question-mark',
  'question-mark',
  'white-question-mark',
  'white-exclamation-mark',
  'exclamation-mark',
  'wavy-dash',
  'currency-exchange',
  'heavy-dollar-sign',
  'recycling-symbol',
  'fleur-de-lis',
  'trident-emblem',
  'name-badge',
  'japanese-symbol-for-beginner',
  'cross-mark',
  'cross-mark-button',
  'curly-loop',
  'double-curly-loop',
  'part-alternation-mark',
  'eight-spoked-asterisk',
  'eight-pointed-star',
  'sparkle',
  'copyright',
  'registered',
  'trade-mark',
  'keycap-asterisk',
  'keycap-10',
  'input-latin-uppercase',
  'input-latin-lowercase',
  'input-numbers',
  'input-symbols',
  'input-latin-letters',
  'cl-button',
  'cool-button',
  'free-button',
  'information',
  'id-button',
  'circled-m',
  'new-button',
  'ng-button',
  'ok-button',
  'p-button',
  'sos-button',
  'vs-button',
  'japanese-here-button',
  'japanese-service-charge-button',
  'japanese-monthly-amount-button',
  'japanese-not-free-of-charge-button',
  'japanese-reserved-button',
  'japanese-bargain-button',
  'japanese-discount-button',
  'japanese-free-of-charge-button',
  'japanese-prohibited-button',
  'japanese-acceptable-button',
  'japanese-application-button',
  'japanese-passing-grade-button',
  'japanese-vacancy-button',
  'japanese-congratulations-button',
  'japanese-secret-button',
  'japanese-open-for-business-button',
  'japanese-no-vacancy-button',
  'black-circle',
  'white-circle',
  'black-large-square',
  'white-large-square',
  'black-medium-square',
  'white-medium-square',
  'black-medium-small-square',
  'white-medium-small-square',
  'black-small-square',
  'white-small-square',
  'large-orange-diamond',
  'large-blue-diamond',
  'small-orange-diamond',
  'small-blue-diamond',
  'red-triangle-pointed-up',
  'red-triangle-pointed-down',
  'diamond-with-a-dot',
  'radio-button',
  'white-square-button',
  'black-square-button',
  'flag-england',
  'flag-scotland',
  'digit-zero',
  'asterisk',
  'digit-nine',
  'digit-one',
  'digit-two',
  'digit-three',
  'digit-four',
  'digit-five',
  'digit-six',
  'digit-seven',
  'digit-eight',
]
