export default {
  ID: {},
  ForeignKey: {},
  SingleLineText: { w: '150px' },
  LongText: { w: '400px' },
  Attachment: { w: '400px' },
  Checkbox: { w: '100px' },
  MultiSelect: { w: '200px' },
  SingleSelect: { w: '200px' },
  Collaborator: {},
  Date: {},
  Year: {},
  Time: {},
  PhoneNumber: {},
  Email: {},
  URL: {},
  Number: {},
  Decimal: {},
  Currency: {},
  Percent: {},
  Duration: {},
  Rating: {},
  Formula: {},
  Rollup: {},
  Count: {},
  DateTime: {},
  CreateTime: {},
  LastModifiedTime: {},
  AutoNumber: {},
  Barcode: {},
  Button: {},
  LinkToAnotherRecord: { w: '400px' },
  Lookup: { w: '400px' }
}
