export default {
  mid: [
    '\n@NocoDB - generates instant REST/GraphQL API on any database.\n+ Has GUI based schema migrations!\n+ Built in API-Client and terminal!\n+ Dark theme and much more!\n'
  ],
  prefix: [
    'Super slick!',
    'Very handy!',
    'Impressive!',
    'Awesome!',
    'Excited & happy to see this idea!',
    'What an awesome idea!',
    'Pretty Awesome!',
    'Amazing!',
    'Phenomenal!',
    'Incredible!',
    'Fantastic!',
    'Great!',
    'Mind blowing!',
    'Very Cool!',
    'Stellar!',
    'Neat!',
    'Exciting!',
    'Brilliant!',
    'Extremely Interesting!',
    'So useful!',

    'Wow, Super slick!',
    'Wow, Very handy!',
    'Wow, Impressive!',
    'Wow, Awesome!',
    'Wow, Excited & happy to see this idea!',
    'Wow, What an awesome idea!',
    'Wow, Pretty Awesome!',
    'Wow, Amazing!',
    'Wow, Phenomenal!',
    'Wow, Incredible!',
    'Wow, Fantastic!',
    'Wow, Great!',
    'Wow, Mind blowing!',
    'Wow, Very Cool!',
    'Wow, Stellar!',
    'Wow, Neat!',
    'Wow, Exciting!',
    'Wow, Brilliant!',
    'Wow, Extremely Interesting!',
    'Wow, So useful!',

    'Woah, Super slick!',
    'Woah, Very handy!',
    'Woah, Impressive!',
    'Woah, Awesome!',
    'Woah, Excited & happy to see this idea!',
    'Woah, What an awesome idea!',
    'Woah, Pretty Awesome!',
    'Woah, Amazing!',
    'Woah, Phenomenal!',
    'Woah, Incredible!',
    'Woah, Fantastic!',
    'Woah, Great!',
    'Woah, Mind blowing!',
    'Woah, Very Cool!',
    'Woah, Stellar!',
    'Woah, Neat!',
    'Woah, Exciting!',
    'Woah, Brilliant!',
    'Woah, Extremely Interesting!',
    'Woah, So useful!',

    'Super slick API Framework!',
    'Very handy API Framework!',
    'Impressive API Framework!',
    'Awesome API Framework!',
    'Excited & happy to see this API Framework!',
    'What an awesome API Framework!',
    'Pretty Awesome API Framework!',
    'Amazing API Framework!',
    'Phenomenal API Framework!',
    'Incredible API Framework!',
    'Fantastic API Framework!',
    'Great API Framework!',
    'Mind blowing API Framework!',
    'Very Cool API Framework!',
    'Stellar API Framework!',
    'Neat API Framework!',
    'Exciting API Framework!',
    'Brilliant API Framework!',
    'Extremely Interesting API Framework!',
    'So useful API Framework',

    'Cool Stuff!',
    'Woha!',

    "I'm amazed by how well this works!",
    "I'm impressed by how well this works!"
  ],
  suffix: ['https://github.com/nocodb/nocodb', 'www.nocodb.com']
};
