import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  // nc_base_users_v2
  await knex.schema.createTable('nc_base_users_v2', (table) => {
    table.string('base_id', 20).notNullable()
    table.string('fk_user_id', 20).notNullable()
    table.text('roles')
    table.boolean('starred')
    table.boolean('pinned')
    table.string('group', 255)
    table.string('color', 255)
    table.float('order')
    table.float('hidden')
    table.datetime('opened_date', { useTz: false })
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('invited_by', 20)
    table.primary(['base_id', 'fk_user_id'])
    table.index('base_id', 'nc_base_users_v2_base_id_index')
    table.index('fk_user_id', 'nc_project_users_v2_fk_user_id_index')
    table.index('invited_by', 'nc_base_users_v2_invited_by_index')
  })

  // nc_bases_v2
  await knex.schema.createTable('nc_bases_v2', (table) => {
    table.string('id', 128).primary()
    table.string('title', 255)
    table.string('prefix', 255)
    table.string('status', 255)
    table.text('description')
    table.text('meta')
    table.string('color', 255)
    table.string('uuid', 255)
    table.string('password', 255)
    table.string('roles', 255)
    table.boolean('deleted').defaultTo(false)
    table.boolean('is_meta')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
  })

  // nc_calendar_view_columns_v2
  await knex.schema.createTable('nc_calendar_view_columns_v2', (table) => {
    table.string('id', 20).primary()
    table.string('base_id', 20)
    table.string('source_id', 20)
    table.string('fk_view_id', 20)
    table.string('fk_column_id', 20)
    table.boolean('show')
    table.boolean('bold')
    table.boolean('underline')
    table.boolean('italic')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('base_id', 'nc_calendar_view_columns_v2_base_id_index')
    table.index(['fk_view_id', 'fk_column_id'], 'nc_calendar_view_columns_v2_fk_view_id_fk_column_id_index')
  })

  // nc_calendar_view_range_v2
  await knex.schema.createTable('nc_calendar_view_range_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_view_id', 20)
    table.string('fk_to_column_id', 20)
    table.string('label', 40)
    table.string('fk_from_column_id', 20)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('base_id', 20)
    table.index('base_id', 'nc_calendar_view_range_v2_base_id_index')
  })

  // nc_calendar_view_v2
  await knex.schema.createTable('nc_calendar_view_v2', (table) => {
    table.string('fk_view_id', 20).primary()
    table.string('base_id', 20)
    table.string('source_id', 20)
    table.string('title', 255)
    table.string('fk_cover_image_col_id', 20)
    table.text('meta')
    table.datetime('created_at', { useTz: false })
    table.datetime('updated_at', { useTz: false })
    table.index('base_id', 'nc_calendar_view_v2_base_id_index')
  })

  // nc_col_barcode_v2
  await knex.schema.createTable('nc_col_barcode_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_column_id', 20)
    table.string('fk_barcode_value_column_id', 20)
    table.string('barcode_format', 15)
    table.boolean('deleted')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('base_id', 20)
    table.index('base_id', 'nc_col_barcode_v2_base_id_index')
    table.index('fk_column_id', 'nc_col_barcode_v2_fk_column_id_index')
  })

  // nc_col_button_v2
  await knex.schema.createTable('nc_col_button_v2', (table) => {
    table.string('id', 20).primary()
    table.string('base_id', 20)
    table.string('type', 255)
    table.text('label')
    table.string('theme', 255)
    table.string('color', 255)
    table.string('icon', 255)
    table.text('formula')
    table.text('formula_raw')
    table.string('error', 255)
    table.text('parsed_tree')
    table.string('fk_webhook_id', 20)
    table.string('fk_column_id', 20)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('fk_integration_id', 20)
    table.string('model', 255)
    table.text('output_column_ids')
    table.string('fk_workspace_id', 20)
    table.index(['base_id', 'fk_workspace_id'], 'nc_col_button_context')
    table.index('fk_column_id', 'nc_col_button_v2_fk_column_id_index')
  })

  // nc_col_formula_v2
  await knex.schema.createTable('nc_col_formula_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_column_id', 20)
    table.text('formula').notNullable()
    table.text('formula_raw')
    table.text('error')
    table.boolean('deleted')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('parsed_tree')
    table.string('base_id', 20)
    table.index('base_id', 'nc_col_formula_v2_base_id_index')
    table.index('fk_column_id', 'nc_col_formula_v2_fk_column_id_index')
  })

  // nc_col_long_text_v2
  await knex.schema.createTable('nc_col_long_text_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_workspace_id', 20)
    table.string('base_id', 20)
    table.string('fk_model_id', 20)
    table.string('fk_column_id', 20)
    table.string('fk_integration_id', 20)
    table.string('model', 255)
    table.text('prompt')
    table.text('prompt_raw')
    table.text('error')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index(['base_id', 'fk_workspace_id'], 'nc_col_long_text_context')
    table.index('fk_column_id', 'nc_col_long_text_v2_fk_column_id_index')
  })

  // nc_col_lookup_v2
  await knex.schema.createTable('nc_col_lookup_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_column_id', 20)
    table.string('fk_relation_column_id', 20)
    table.string('fk_lookup_column_id', 20)
    table.boolean('deleted')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('base_id', 20)
    table.index('base_id', 'nc_col_lookup_v2_base_id_index')
    table.index('fk_column_id', 'nc_col_lookup_v2_fk_column_id_index')
    table.index('fk_lookup_column_id', 'nc_col_lookup_v2_fk_lookup_column_id_index')
    table.index('fk_relation_column_id', 'nc_col_lookup_v2_fk_relation_column_id_index')
  })

  // nc_col_qrcode_v2
  await knex.schema.createTable('nc_col_qrcode_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_column_id', 20)
    table.string('fk_qr_value_column_id', 20)
    table.boolean('deleted')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('base_id', 20)
    table.index('base_id', 'nc_col_qrcode_v2_base_id_index')
    table.index('fk_column_id', 'nc_col_qrcode_v2_fk_column_id_index')
  })

  // nc_col_relations_v2
  await knex.schema.createTable('nc_col_relations_v2', (table) => {
    table.string('id', 20).primary()
    table.string('ref_db_alias', 255)
    table.string('type', 255)
    table.boolean('virtual')
    table.string('db_type', 255)
    table.string('fk_column_id', 20)
    table.string('fk_related_model_id', 20)
    table.string('fk_child_column_id', 20)
    table.string('fk_parent_column_id', 20)
    table.string('fk_mm_model_id', 20)
    table.string('fk_mm_child_column_id', 20)
    table.string('fk_mm_parent_column_id', 20)
    table.string('ur', 255)
    table.string('dr', 255)
    table.string('fk_index_name', 255)
    table.boolean('deleted')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('fk_target_view_id', 20)
    table.string('base_id', 20)
    table.index('base_id', 'nc_col_relations_v2_base_id_index')
    table.index('fk_column_id', 'nc_col_relations_v2_fk_column_id_index')
    table.index('fk_child_column_id', 'nc_col_relations_v2_fk_child_column_id_index')
    table.index('fk_parent_column_id', 'nc_col_relations_v2_fk_parent_column_id_index')
    table.index('fk_mm_model_id', 'nc_col_relations_v2_fk_mm_model_id_index')
    table.index('fk_mm_child_column_id', 'nc_col_relations_v2_fk_mm_child_column_id_index')
    table.index('fk_mm_parent_column_id', 'nc_col_relations_v2_fk_mm_parent_column_id_index')
    table.index('fk_related_model_id', 'nc_col_relations_v2_fk_related_model_id_index')
    table.index('fk_target_view_id', 'nc_col_relations_v2_fk_target_view_id_index')
  })

  // nc_col_rollup_v2
  await knex.schema.createTable('nc_col_rollup_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_column_id', 20)
    table.string('fk_relation_column_id', 20)
    table.string('fk_rollup_column_id', 20)
    table.string('rollup_function', 255)
    table.boolean('deleted')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('base_id', 20)
    table.index('base_id', 'nc_col_rollup_v2_base_id_index')
    table.index('fk_column_id', 'nc_col_rollup_v2_fk_column_id_index')
    table.index('fk_relation_column_id', 'nc_col_rollup_v2_fk_relation_column_id_index')
    table.index('fk_rollup_column_id', 'nc_col_rollup_v2_fk_rollup_column_id_index')
  })

  // nc_col_select_options_v2
  await knex.schema.createTable('nc_col_select_options_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_column_id', 20)
    table.string('title', 255)
    table.string('color', 255)
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('base_id', 20)
    table.index('base_id', 'nc_col_select_options_v2_base_id_index')
    table.index('fk_column_id', 'nc_col_select_options_v2_fk_column_id_index')
  })

  // nc_columns_v2
  await knex.schema.createTable('nc_columns_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_model_id', 20)
    table.string('title', 255)
    table.string('column_name', 255)
    table.string('uidt', 255)
    table.string('dt', 255)
    table.string('np', 255)
    table.string('ns', 255)
    table.string('clen', 255)
    table.string('cop', 255)
    table.boolean('pk')
    table.boolean('pv')
    table.boolean('rqd')
    table.boolean('un')
    table.text('ct')
    table.boolean('ai')
    table.boolean('unique')
    table.text('cdf')
    table.text('cc')
    table.string('csn', 255)
    table.string('dtx', 255)
    table.text('dtxp')
    table.string('dtxs', 255)
    table.boolean('au')
    table.text('validate')
    table.boolean('virtual')
    table.boolean('deleted')
    table.boolean('system').defaultTo(false)
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('meta')
    table.text('description')
    table.boolean('readonly').defaultTo(false)
    table.string('custom_index_name', 64)
    table.index('base_id', 'nc_columns_v2_base_id_index')
    table.index('fk_model_id', 'nc_columns_v2_fk_model_id_index')
  })

  // nc_data_reflection
  await knex.schema.createTable('nc_data_reflection', (table) => {
    table.string('id', 20).primary()
    table.string('fk_workspace_id', 20)
    table.string('username', 255)
    table.string('password', 255)
    table.string('database', 255)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('fk_workspace_id', 'nc_data_reflection_fk_workspace_id_index')
  })

  // nc_disabled_models_for_role_v2
  await knex.schema.createTable('nc_disabled_models_for_role_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_view_id', 20)
    table.string('role', 45)
    table.boolean('disabled').defaultTo(true)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
  })

  // nc_extensions
  await knex.schema.createTable('nc_extensions', (table) => {
    table.string('id', 20).primary()
    table.string('base_id', 20)
    table.string('fk_user_id', 20)
    table.string('extension_id', 255)
    table.string('title', 255)
    table.text('kv_store')
    table.text('meta')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('base_id', 'nc_extensions_base_id_index')
  })

  // nc_filter_exp_v2
  await knex.schema.createTable('nc_filter_exp_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_view_id', 20)
    table.string('fk_hook_id', 20)
    table.string('fk_column_id', 20)
    table.string('fk_parent_id', 20)
    table.string('logical_op', 255)
    table.string('comparison_op', 255)
    table.text('value')
    table.boolean('is_group')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('comparison_sub_op', 255)
    table.string('fk_link_col_id', 20)
    table.string('fk_value_col_id', 20)
    table.string('fk_parent_column_id', 20)
    table.index('base_id', 'nc_filter_exp_v2_base_id_index')
    table.index('fk_column_id', 'nc_filter_exp_v2_fk_column_id_index')
    table.index('fk_hook_id', 'nc_filter_exp_v2_fk_hook_id_index')
    table.index('fk_link_col_id', 'nc_filter_exp_v2_fk_link_col_id_index')
    table.index('fk_value_col_id', 'nc_filter_exp_v2_fk_value_col_id_index')
    table.index('fk_parent_id', 'nc_filter_exp_v2_fk_parent_id_index')
    table.index('fk_parent_column_id', 'nc_filter_exp_v2_fk_parent_column_id_index')
    table.index('fk_view_id', 'nc_filter_exp_v2_fk_view_id_index')
  })

  // nc_form_view_columns_v2
  await knex.schema.createTable('nc_form_view_columns_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_view_id', 20)
    table.string('fk_column_id', 20)
    table.string('uuid', 255)
    table.text('label')
    table.text('help')
    table.text('description')
    table.boolean('required')
    table.boolean('show')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('meta')
    table.boolean('enable_scanner')
    table.index('base_id', 'nc_form_view_columns_v2_base_id_index')
    table.index('fk_column_id', 'nc_form_view_columns_v2_fk_column_id_index')
    table.index(['fk_view_id', 'fk_column_id'], 'nc_form_view_columns_v2_fk_view_id_fk_column_id_index')
    table.index('fk_view_id', 'nc_form_view_columns_v2_fk_view_id_index')
  })

  // nc_form_view_v2
  await knex.schema.createTable('nc_form_view_v2', (table) => {
    table.string('fk_view_id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('heading', 255)
    table.text('subheading')
    table.text('success_msg')
    table.text('redirect_url')
    table.string('redirect_after_secs', 255)
    table.string('email', 255)
    table.boolean('submit_another_form')
    table.boolean('show_blank_form')
    table.string('uuid', 255)
    table.text('banner_image_url')
    table.text('logo_url')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('meta')
    table.index('base_id', 'nc_form_view_v2_base_id_index')
    table.index('fk_view_id', 'nc_form_view_v2_fk_view_id_index')
  })

  // nc_gallery_view_columns_v2
  await knex.schema.createTable('nc_gallery_view_columns_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_view_id', 20)
    table.string('fk_column_id', 20)
    table.string('uuid', 255)
    table.string('label', 255)
    table.string('help', 255)
    table.boolean('show')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('base_id', 'nc_gallery_view_columns_v2_base_id_index')
    table.index('fk_column_id', 'nc_gallery_view_columns_v2_fk_column_id_index')
    table.index(['fk_view_id', 'fk_column_id'], 'nc_gallery_view_columns_v2_fk_view_id_fk_column_id_index')
    table.index('fk_view_id', 'nc_gallery_view_columns_v2_fk_view_id_index')
  })

  // nc_gallery_view_v2
  await knex.schema.createTable('nc_gallery_view_v2', (table) => {
    table.string('fk_view_id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.boolean('next_enabled')
    table.boolean('prev_enabled')
    table.integer('cover_image_idx')
    table.string('fk_cover_image_col_id', 20)
    table.string('cover_image', 255)
    table.string('restrict_types', 255)
    table.string('restrict_size', 255)
    table.string('restrict_number', 255)
    table.boolean('public')
    table.string('dimensions', 255)
    table.string('responsive_columns', 255)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('meta')
    table.index('base_id', 'nc_gallery_view_v2_base_id_index')
    table.index('fk_view_id', 'nc_gallery_view_v2_fk_view_id_index')
  })

  // nc_grid_view_columns_v2
  await knex.schema.createTable('nc_grid_view_columns_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_view_id', 20)
    table.string('fk_column_id', 20)
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('uuid', 255)
    table.string('label', 255)
    table.string('help', 255)
    table.string('width', 255).defaultTo('200px')
    table.boolean('show')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.boolean('group_by')
    table.float('group_by_order')
    table.string('group_by_sort', 255)
    table.string('aggregation', 30)
    table.index('base_id', 'nc_grid_view_columns_v2_base_id_index')
    table.index('fk_column_id', 'nc_grid_view_columns_v2_fk_column_id_index')
    table.index(['fk_view_id', 'fk_column_id'], 'nc_grid_view_columns_v2_fk_view_id_fk_column_id_index')
    table.index('fk_view_id', 'nc_grid_view_columns_v2_fk_view_id_index')
  })

  // nc_grid_view_v2
  await knex.schema.createTable('nc_grid_view_v2', (table) => {
    table.string('fk_view_id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('uuid', 255)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('meta')
    table.integer('row_height')
    table.index('base_id', 'nc_grid_view_v2_base_id_index')
    table.index('fk_view_id', 'nc_grid_view_v2_fk_view_id_index')
  })

  // nc_hooks_v2
  await knex.schema.createTable('nc_hooks_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_model_id', 20)
    table.string('title', 255)
    table.string('description', 255)
    table.string('env', 255).defaultTo('all')
    table.string('type', 255)
    table.string('event', 255)
    table.string('operation', 255)
    table.boolean('async').defaultTo(false)
    table.boolean('payload').defaultTo(true)
    table.text('url')
    table.text('headers')
    table.boolean('condition').defaultTo(false)
    table.text('notification')
    table.integer('retries').defaultTo(0)
    table.integer('retry_interval').defaultTo(60000)
    table.integer('timeout').defaultTo(60000)
    table.boolean('active').defaultTo(true)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('version', 255)
    table.index('base_id', 'nc_hooks_v2_base_id_index')
    table.index('fk_model_id', 'nc_hooks_v2_fk_model_id_index')
  })

  // nc_integrations_v2
  await knex.schema.createTable('nc_integrations_v2', (table) => {
    table.string('id', 20).primary()
    table.string('title', 128)
    table.text('config')
    table.text('meta')
    table.string('type', 20)
    table.string('sub_type', 20)
    table.boolean('is_private').defaultTo(false)
    table.boolean('deleted').defaultTo(false)
    table.string('created_by', 20)
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.boolean('is_default').defaultTo(false)
    table.boolean('is_encrypted').defaultTo(false)
    table.index('created_by', 'nc_integrations_v2_created_by_index')
    table.index('type', 'nc_integrations_v2_type_index')
  })

  // nc_jobs
  await knex.schema.createTable('nc_jobs', (table) => {
    table.string('id', 20).primary()
    table.string('job', 255)
    table.string('status', 20)
    table.text('result')
    table.string('fk_user_id', 20)
    table.string('fk_workspace_id', 20)
    table.string('base_id', 20)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index(['base_id', 'fk_workspace_id'], 'nc_jobs_context')
  })

  // nc_kanban_view_columns_v2
  await knex.schema.createTable('nc_kanban_view_columns_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_view_id', 20)
    table.string('fk_column_id', 20)
    table.string('uuid', 255)
    table.string('label', 255)
    table.string('help', 255)
    table.boolean('show')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('base_id', 'nc_kanban_view_columns_v2_base_id_index')
    table.index('fk_column_id', 'nc_kanban_view_columns_v2_fk_column_id_index')
    table.index(['fk_view_id', 'fk_column_id'], 'nc_kanban_view_columns_v2_fk_view_id_fk_column_id_index')
    table.index('fk_view_id', 'nc_kanban_view_columns_v2_fk_view_id_index')
  })

  // nc_kanban_view_v2
  await knex.schema.createTable('nc_kanban_view_v2', (table) => {
    table.string('fk_view_id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.boolean('show')
    table.float('order')
    table.string('uuid', 255)
    table.string('title', 255)
    table.boolean('public')
    table.string('password', 255)
    table.boolean('show_all_fields')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.string('fk_grp_col_id', 20)
    table.string('fk_cover_image_col_id', 20)
    table.text('meta')
    table.index('base_id', 'nc_kanban_view_v2_base_id_index')
    table.index('fk_grp_col_id', 'nc_kanban_view_v2_fk_grp_col_id_index')
    table.index('fk_view_id', 'nc_kanban_view_v2_fk_view_id_index')
  })

  // nc_map_view_columns_v2
  await knex.schema.createTable('nc_map_view_columns_v2', (table) => {
    table.string('id', 20).primary()
    table.string('base_id', 20)
    table.string('project_id', 128)
    table.string('fk_view_id', 20)
    table.string('fk_column_id', 20)
    table.string('uuid', 255)
    table.string('label', 255)
    table.string('help', 255)
    table.boolean('show')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('base_id', 'nc_map_view_columns_v2_base_id_index')
    table.index('fk_column_id', 'nc_map_view_columns_v2_fk_column_id_index')
    table.index(['fk_view_id', 'fk_column_id'], 'nc_map_view_columns_v2_fk_view_id_fk_column_id_index')
    table.index('fk_view_id', 'nc_map_view_columns_v2_fk_view_id_index')
  })

  // nc_map_view_v2
  await knex.schema.createTable('nc_map_view_v2', (table) => {
    table.string('fk_view_id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('uuid', 255)
    table.string('title', 255)
    table.string('fk_geo_data_col_id', 20)
    table.text('meta')
    table.datetime('created_at', { useTz: false })
    table.datetime('updated_at', { useTz: false })
    table.index('base_id', 'nc_map_view_v2_base_id_index')
    table.index('fk_geo_data_col_id', 'nc_map_view_v2_fk_geo_data_col_id_index')
    table.index('fk_view_id', 'nc_map_view_v2_fk_view_id_index')
  })

  // nc_models_v2
  await knex.schema.createTable('nc_models_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('table_name', 255)
    table.string('title', 255)
    table.string('type', 255).defaultTo('table')
    table.text('meta')
    table.text('schema')
    table.boolean('enabled').defaultTo(true)
    table.boolean('mm').defaultTo(false)
    table.string('tags', 255)
    table.boolean('pinned')
    table.boolean('deleted')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('description')
    table.boolean('synced').defaultTo(false)
    table.index('base_id', 'nc_models_v2_base_id_index')
  })

  // nc_shared_bases
  await knex.schema.createTable('nc_shared_bases', (table) => {
    table.increments('id').primary()
    table.string('project_id', 255)
    table.string('db_alias', 255)
    table.string('roles', 255).defaultTo('viewer')
    table.string('shared_base_id', 255)
    table.boolean('enabled').defaultTo(true)
    table.string('password', 255)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
  })

  // nc_shared_views_v2
  await knex.schema.createTable('nc_shared_views_v2', (table) => {
    table.string('id', 20).primary()
    table.string('fk_view_id', 20)
    table.text('meta')
    table.text('query_params')
    table.string('view_id', 255)
    table.boolean('show_all_fields')
    table.boolean('allow_copy')
    table.string('password', 255)
    table.boolean('deleted')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('fk_view_id', 'nc_shared_views_v2_fk_view_id_index')
  })

  // nc_sort_v2
  await knex.schema.createTable('nc_sort_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_view_id', 20)
    table.string('fk_column_id', 20)
    table.string('direction', 255).defaultTo('false')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index('base_id', 'nc_sort_v2_base_id_index')
    table.index('fk_column_id', 'nc_sort_v2_fk_column_id_index')
    table.index('fk_view_id', 'nc_sort_v2_fk_view_id_index')
  })

  // nc_sources_v2
  await knex.schema.createTable('nc_sources_v2', (table) => {
    table.string('id', 20).primary()
    table.string('base_id', 20)
    table.string('alias', 255)
    table.text('config')
    table.text('meta')
    table.boolean('is_meta')
    table.string('type', 255)
    table.string('inflection_column', 255)
    table.string('inflection_table', 255)
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.boolean('enabled').defaultTo(true)
    table.float('order')
    table.string('description', 255)
    table.string('erd_uuid', 255)
    table.boolean('deleted').defaultTo(false)
    table.boolean('is_schema_readonly').defaultTo(false)
    table.boolean('is_data_readonly').defaultTo(false)
    table.string('fk_integration_id', 20)
    table.boolean('is_local').defaultTo(false)
    table.boolean('is_encrypted').defaultTo(false)
    table.index('base_id', 'nc_sources_v2_base_id_index')
    table.index('fk_integration_id', 'nc_sources_v2_fk_integration_id_index')
  })

  // nc_sync_configs
  await knex.schema.createTable('nc_sync_configs', (table) => {
    table.string('id', 20).primary()
    table.string('fk_workspace_id', 20)
    table.string('base_id', 20)
    table.string('fk_integration_id', 20)
    table.string('fk_model_id', 20)
    table.string('sync_type', 255)
    table.string('sync_trigger', 255)
    table.string('sync_trigger_cron', 255)
    table.string('sync_trigger_secret', 255)
    table.string('sync_job_id', 255)
    table.datetime('last_sync_at', { useTz: false })
    table.datetime('next_sync_at', { useTz: false })
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.index(['base_id', 'fk_workspace_id'], 'nc_sync_configs_context')
    table.index(['fk_model_id', 'fk_integration_id'], 'sync_configs_integration_model')
  })

  // nc_views_v2
  await knex.schema.createTable('nc_views_v2', (table) => {
    table.string('id', 20).primary()
    table.string('source_id', 20)
    table.string('base_id', 20)
    table.string('fk_model_id', 20)
    table.string('title', 255)
    table.integer('type')
    table.boolean('is_default')
    table.boolean('show_system_fields')
    table.string('lock_type', 255).defaultTo('collaborative')
    table.string('uuid', 255)
    table.string('password', 255)
    table.boolean('show')
    table.float('order')
    table.datetime('created_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.datetime('updated_at', { useTz: false }).defaultTo(knex.fn.now()).notNullable()
    table.text('meta')
    table.text('description')
    table.string('created_by', 20)
    table.string('owned_by', 20)
    table.index('base_id', 'nc_views_v2_base_id_index')
    table.index('fk_model_id', 'nc_views_v2_fk_model_id_index')
    table.index('created_by', 'nc_views_v2_created_by_index')
    table.index('owned_by', 'nc_views_v2_owned_by_index')
  })

  // sync_metadata
  await knex.schema.createTable('sync_metadata', (table) => {
    table.string('workspace_id', 50).notNullable()
    table.string('base_id', 50).notNullable()
    table.string('last_event_id', 50)
    table.datetime('last_sync_timestamp', { useTz: false })
    table.primary(['workspace_id', 'base_id'])
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('sync_metadata')
  await knex.schema.dropTableIfExists('nc_views_v2')
  await knex.schema.dropTableIfExists('nc_sync_configs')
  await knex.schema.dropTableIfExists('nc_sources_v2')
  await knex.schema.dropTableIfExists('nc_sort_v2')
  await knex.schema.dropTableIfExists('nc_shared_views_v2')
  await knex.schema.dropTableIfExists('nc_shared_bases')
  await knex.schema.dropTableIfExists('nc_models_v2')
  await knex.schema.dropTableIfExists('nc_map_view_v2')
  await knex.schema.dropTableIfExists('nc_map_view_columns_v2')
  await knex.schema.dropTableIfExists('nc_kanban_view_v2')
  await knex.schema.dropTableIfExists('nc_kanban_view_columns_v2')
  await knex.schema.dropTableIfExists('nc_jobs')
  await knex.schema.dropTableIfExists('nc_integrations_v2')
  await knex.schema.dropTableIfExists('nc_hooks_v2')
  await knex.schema.dropTableIfExists('nc_grid_view_v2')
  await knex.schema.dropTableIfExists('nc_grid_view_columns_v2')
  await knex.schema.dropTableIfExists('nc_gallery_view_v2')
  await knex.schema.dropTableIfExists('nc_gallery_view_columns_v2')
  await knex.schema.dropTableIfExists('nc_form_view_v2')
  await knex.schema.dropTableIfExists('nc_form_view_columns_v2')
  await knex.schema.dropTableIfExists('nc_filter_exp_v2')
  await knex.schema.dropTableIfExists('nc_extensions')
  await knex.schema.dropTableIfExists('nc_disabled_models_for_role_v2')
  await knex.schema.dropTableIfExists('nc_data_reflection')
  await knex.schema.dropTableIfExists('nc_columns_v2')
  await knex.schema.dropTableIfExists('nc_col_select_options_v2')
  await knex.schema.dropTableIfExists('nc_col_rollup_v2')
  await knex.schema.dropTableIfExists('nc_col_relations_v2')
  await knex.schema.dropTableIfExists('nc_col_qrcode_v2')
  await knex.schema.dropTableIfExists('nc_col_lookup_v2')
  await knex.schema.dropTableIfExists('nc_col_long_text_v2')
  await knex.schema.dropTableIfExists('nc_col_formula_v2')
  await knex.schema.dropTableIfExists('nc_col_button_v2')
  await knex.schema.dropTableIfExists('nc_col_barcode_v2')
  await knex.schema.dropTableIfExists('nc_calendar_view_v2')
  await knex.schema.dropTableIfExists('nc_calendar_view_range_v2')
  await knex.schema.dropTableIfExists('nc_calendar_view_columns_v2')
  await knex.schema.dropTableIfExists('nc_bases_v2')
  await knex.schema.dropTableIfExists('nc_base_users_v2')
}
