import { UITypes } from 'nocodb-sdk';
import { createTable } from '../../factory/table';
import { createBulkRows } from '../../factory/row';

const data = {
  Customers: [
    {
      CustomerId: 1,
      StoreId: 1,
      FirstName: 'MARY',
      LastName: 'SMITH',
      Email: 'MARY.SMITH@sakilacustomer.org',
      AddressId: 5,
      Active: 1,
    },
    {
      CustomerId: 2,
      StoreId: 1,
      FirstName: 'PATRICIA',
      LastName: 'JOHNSON',
      Email: 'PATRICIA.JOHNSON@sakilacustomer.org',
      AddressId: 6,
      Active: 1,
    },
    {
      CustomerId: 3,
      StoreId: 1,
      FirstName: 'LINDA',
      LastName: 'WILLIAMS',
      Email: 'LINDA.WILLIAMS@sakilacustomer.org',
      AddressId: 7,
      Active: 1,
    },
    {
      CustomerId: 4,
      StoreId: 2,
      FirstName: 'BARBARA',
      LastName: 'JONES',
      Email: 'BARBARA.JONES@sakilacustomer.org',
      AddressId: 8,
      Active: 1,
    },
    {
      CustomerId: 5,
      StoreId: 1,
      FirstName: 'ELIZABETH',
      LastName: 'BROWN',
      Email: 'ELIZABETH.BROWN@sakilacustomer.org',
      AddressId: 9,
      Active: 1,
    },
    {
      CustomerId: 6,
      StoreId: 2,
      FirstName: 'JENNIFER',
      LastName: 'DAVIS',
      Email: 'JENNIFER.DAVIS@sakilacustomer.org',
      AddressId: 10,
      Active: 1,
    },
    {
      CustomerId: 7,
      StoreId: 1,
      FirstName: 'MARIA',
      LastName: 'MILLER',
      Email: 'MARIA.MILLER@sakilacustomer.org',
      AddressId: 11,
      Active: 1,
    },
    {
      CustomerId: 8,
      StoreId: 2,
      FirstName: 'SUSAN',
      LastName: 'WILSON',
      Email: 'SUSAN.WILSON@sakilacustomer.org',
      AddressId: 12,
      Active: 1,
    },
    {
      CustomerId: 9,
      StoreId: 2,
      FirstName: 'MARGARET',
      LastName: 'MOORE',
      Email: 'MARGARET.MOORE@sakilacustomer.org',
      AddressId: 13,
      Active: 1,
    },
    {
      CustomerId: 10,
      StoreId: 1,
      FirstName: 'DOROTHY',
      LastName: 'TAYLOR',
      Email: 'DOROTHY.TAYLOR@sakilacustomer.org',
      AddressId: 14,
      Active: 1,
    },
    {
      CustomerId: 11,
      StoreId: 2,
      FirstName: 'LISA',
      LastName: 'ANDERSON',
      Email: 'LISA.ANDERSON@sakilacustomer.org',
      AddressId: 15,
      Active: 1,
    },
    {
      CustomerId: 12,
      StoreId: 1,
      FirstName: 'NANCY',
      LastName: 'THOMAS',
      Email: 'NANCY.THOMAS@sakilacustomer.org',
      AddressId: 16,
      Active: 1,
    },
    {
      CustomerId: 13,
      StoreId: 2,
      FirstName: 'KAREN',
      LastName: 'JACKSON',
      Email: 'KAREN.JACKSON@sakilacustomer.org',
      AddressId: 17,
      Active: 1,
    },
    {
      CustomerId: 14,
      StoreId: 2,
      FirstName: 'BETTY',
      LastName: 'WHITE',
      Email: 'BETTY.WHITE@sakilacustomer.org',
      AddressId: 18,
      Active: 1,
    },
    {
      CustomerId: 15,
      StoreId: 1,
      FirstName: 'HELEN',
      LastName: 'HARRIS',
      Email: 'HELEN.HARRIS@sakilacustomer.org',
      AddressId: 19,
      Active: 1,
    },
    {
      CustomerId: 16,
      StoreId: 2,
      FirstName: 'SANDRA',
      LastName: 'MARTIN',
      Email: 'SANDRA.MARTIN@sakilacustomer.org',
      AddressId: 20,
      Active: 0,
    },
    {
      CustomerId: 17,
      StoreId: 1,
      FirstName: 'DONNA',
      LastName: 'THOMPSON',
      Email: 'DONNA.THOMPSON@sakilacustomer.org',
      AddressId: 21,
      Active: 1,
    },
    {
      CustomerId: 18,
      StoreId: 2,
      FirstName: 'CAROL',
      LastName: 'GARCIA',
      Email: 'CAROL.GARCIA@sakilacustomer.org',
      AddressId: 22,
      Active: 1,
    },
    {
      CustomerId: 19,
      StoreId: 1,
      FirstName: 'RUTH',
      LastName: 'MARTINEZ',
      Email: 'RUTH.MARTINEZ@sakilacustomer.org',
      AddressId: 23,
      Active: 1,
    },
    {
      CustomerId: 20,
      StoreId: 2,
      FirstName: 'SHARON',
      LastName: 'ROBINSON',
      Email: 'SHARON.ROBINSON@sakilacustomer.org',
      AddressId: 24,
      Active: 1,
    },
    {
      CustomerId: 21,
      StoreId: 1,
      FirstName: 'MICHELLE',
      LastName: 'CLARK',
      Email: 'MICHELLE.CLARK@sakilacustomer.org',
      AddressId: 25,
      Active: 1,
    },
    {
      CustomerId: 22,
      StoreId: 1,
      FirstName: 'LAURA',
      LastName: 'RODRIGUEZ',
      Email: 'LAURA.RODRIGUEZ@sakilacustomer.org',
      AddressId: 26,
      Active: 1,
    },
    {
      CustomerId: 23,
      StoreId: 2,
      FirstName: 'SARAH',
      LastName: 'LEWIS',
      Email: 'SARAH.LEWIS@sakilacustomer.org',
      AddressId: 27,
      Active: 1,
    },
    {
      CustomerId: 24,
      StoreId: 2,
      FirstName: 'KIMBERLY',
      LastName: 'LEE',
      Email: 'KIMBERLY.LEE@sakilacustomer.org',
      AddressId: 28,
      Active: 1,
    },
    {
      CustomerId: 25,
      StoreId: 1,
      FirstName: 'DEBORAH',
      LastName: 'WALKER',
      Email: 'DEBORAH.WALKER@sakilacustomer.org',
      AddressId: 29,
      Active: 1,
    },
    {
      CustomerId: 26,
      StoreId: 2,
      FirstName: 'JESSICA',
      LastName: 'HALL',
      Email: 'JESSICA.HALL@sakilacustomer.org',
      AddressId: 30,
      Active: 1,
    },
    {
      CustomerId: 27,
      StoreId: 2,
      FirstName: 'SHIRLEY',
      LastName: 'ALLEN',
      Email: 'SHIRLEY.ALLEN@sakilacustomer.org',
      AddressId: 31,
      Active: 1,
    },
    {
      CustomerId: 28,
      StoreId: 1,
      FirstName: 'CYNTHIA',
      LastName: 'YOUNG',
      Email: 'CYNTHIA.YOUNG@sakilacustomer.org',
      AddressId: 32,
      Active: 1,
    },
    {
      CustomerId: 29,
      StoreId: 2,
      FirstName: 'ANGELA',
      LastName: 'HERNANDEZ',
      Email: 'ANGELA.HERNANDEZ@sakilacustomer.org',
      AddressId: 33,
      Active: 1,
    },
    {
      CustomerId: 30,
      StoreId: 1,
      FirstName: 'MELISSA',
      LastName: 'KING',
      Email: 'MELISSA.KING@sakilacustomer.org',
      AddressId: 34,
      Active: 1,
    },
  ],
  Films: [
    {
      FilmId: 1,
      Title: 'ACADEMY DINOSAUR',
      Description:
        'A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 0.99,
      Length: 86,
      ReplacementCost: 20.99,
      Rating: 'PG',
      SpecialFeatures: 'Deleted Scenes,Behind the Scenes',
    },
    {
      FilmId: 2,
      Title: 'ACE GOLDFINGER',
      Description:
        'A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 4.99,
      Length: 48,
      ReplacementCost: 12.99,
      Rating: 'G',
      SpecialFeatures: 'Trailers,Deleted Scenes',
    },
    {
      FilmId: 3,
      Title: 'ADAPTATION HOLES',
      Description:
        'A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 7,
      RentalRate: 2.99,
      Length: 50,
      ReplacementCost: 18.99,
      Rating: 'NC-17',
      SpecialFeatures: 'Trailers,Deleted Scenes',
    },
    {
      FilmId: 4,
      Title: 'AFFAIR PREJUDICE',
      Description:
        'A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 5,
      RentalRate: 2.99,
      Length: 117,
      ReplacementCost: 26.99,
      Rating: 'G',
      SpecialFeatures: 'Commentaries,Behind the Scenes',
    },
    {
      FilmId: 5,
      Title: 'AFRICAN EGG',
      Description:
        'A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 2.99,
      Length: 130,
      ReplacementCost: 22.99,
      Rating: 'G',
      SpecialFeatures: 'Deleted Scenes',
    },
    {
      FilmId: 6,
      Title: 'AGENT TRUMAN',
      Description:
        'A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 2.99,
      Length: 169,
      ReplacementCost: 17.99,
      Rating: 'PG',
      SpecialFeatures: 'Deleted Scenes',
    },
    {
      FilmId: 7,
      Title: 'AIRPLANE SIERRA',
      Description:
        'A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 4.99,
      Length: 62,
      ReplacementCost: 28.99,
      Rating: 'PG-13',
      SpecialFeatures: 'Trailers,Deleted Scenes',
    },
    {
      FilmId: 8,
      Title: 'AIRPORT POLLOCK',
      Description:
        'A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 4.99,
      Length: 54,
      ReplacementCost: 15.99,
      Rating: 'R',
      SpecialFeatures: 'Trailers',
    },
    {
      FilmId: 9,
      Title: 'ALABAMA DEVIL',
      Description:
        'A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 2.99,
      Length: 114,
      ReplacementCost: 21.99,
      Rating: 'PG-13',
      SpecialFeatures: 'Trailers,Deleted Scenes',
    },
    {
      FilmId: 10,
      Title: 'ALADDIN CALENDAR',
      Description:
        'A Action-Packed Tale of a Man And a Lumberjack who must Reach a Feminist in Ancient China',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 4.99,
      Length: 63,
      ReplacementCost: 24.99,
      Rating: 'NC-17',
      SpecialFeatures: 'Trailers,Deleted Scenes',
    },
    {
      FilmId: 11,
      Title: 'ALAMO VIDEOTAPE',
      Description:
        'A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 0.99,
      Length: 126,
      ReplacementCost: 16.99,
      Rating: 'G',
      SpecialFeatures: 'Commentaries,Behind the Scenes',
    },
    {
      FilmId: 12,
      Title: 'ALASKA PHANTOM',
      Description:
        'A Fanciful Saga of a Hunter And a Pastry Chef who must Vanquish a Boy in Australia',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 0.99,
      Length: 136,
      ReplacementCost: 22.99,
      Rating: 'PG',
      SpecialFeatures: 'Commentaries,Deleted Scenes',
    },
    {
      FilmId: 13,
      Title: 'ALI FOREVER',
      Description:
        'A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 4,
      RentalRate: 4.99,
      Length: 150,
      ReplacementCost: 21.99,
      Rating: 'PG',
      SpecialFeatures: 'Deleted Scenes,Behind the Scenes',
    },
    {
      FilmId: 14,
      Title: 'ALICE FANTASIA',
      Description:
        'A Emotional Drama of a A Shark And a Database Administrator who must Vanquish a Pioneer in Soviet Georgia',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 0.99,
      Length: 94,
      ReplacementCost: 23.99,
      Rating: 'NC-17',
      SpecialFeatures: 'Trailers,Deleted Scenes,Behind the Scenes',
    },
    {
      FilmId: 15,
      Title: 'ALIEN CENTER',
      Description:
        'A Brilliant Drama of a Cat And a Mad Scientist who must Battle a Feminist in A MySQL Convention',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 5,
      RentalRate: 2.99,
      Length: 46,
      ReplacementCost: 10.99,
      Rating: 'NC-17',
      SpecialFeatures: 'Trailers,Commentaries,Behind the Scenes',
    },
    {
      FilmId: 16,
      Title: 'ALLEY EVOLUTION',
      Description:
        'A Fast-Paced Drama of a Robot And a Composer who must Battle a Astronaut in New Orleans',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 2.99,
      Length: 180,
      ReplacementCost: 23.99,
      Rating: 'NC-17',
      SpecialFeatures: 'Trailers,Commentaries',
    },
    {
      FilmId: 17,
      Title: 'ALONE TRIP',
      Description:
        'A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 0.99,
      Length: 82,
      ReplacementCost: 14.99,
      Rating: 'R',
      SpecialFeatures: 'Trailers,Behind the Scenes',
    },
    {
      FilmId: 18,
      Title: 'ALTER VICTORY',
      Description:
        'A Thoughtful Drama of a Composer And a Feminist who must Meet a Secret Agent in The Canadian Rockies',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 0.99,
      Length: 57,
      ReplacementCost: 27.99,
      Rating: 'PG-13',
      SpecialFeatures: 'Trailers,Behind the Scenes',
    },
    {
      FilmId: 19,
      Title: 'AMADEUS HOLY',
      Description:
        'A Emotional Display of a Pioneer And a Technical Writer who must Battle a Man in A Baloon',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 0.99,
      Length: 113,
      ReplacementCost: 20.99,
      Rating: 'PG',
      SpecialFeatures: 'Commentaries,Deleted Scenes,Behind the Scenes',
    },
    {
      FilmId: 20,
      Title: 'AMELIE HELLFIGHTERS',
      Description:
        'A Boring Drama of a Woman And a Squirrel who must Conquer a Student in A Baloon',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 4,
      RentalRate: 4.99,
      Length: 79,
      ReplacementCost: 23.99,
      Rating: 'R',
      SpecialFeatures: 'Commentaries,Deleted Scenes,Behind the Scenes',
    },
    {
      FilmId: 21,
      Title: 'AMERICAN CIRCUS',
      Description:
        'A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 4.99,
      Length: 129,
      ReplacementCost: 17.99,
      Rating: 'R',
      SpecialFeatures: 'Commentaries,Behind the Scenes',
    },
    {
      FilmId: 22,
      Title: 'AMISTAD MIDSUMMER',
      Description:
        'A Emotional Character Study of a Dentist And a Crocodile who must Meet a Sumo Wrestler in California',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 2.99,
      Length: 85,
      ReplacementCost: 10.99,
      Rating: 'G',
      SpecialFeatures: 'Commentaries,Behind the Scenes',
    },
    {
      FilmId: 23,
      Title: 'ANACONDA CONFESSIONS',
      Description:
        'A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 0.99,
      Length: 92,
      ReplacementCost: 9.99,
      Rating: 'R',
      SpecialFeatures: 'Trailers,Deleted Scenes',
    },
    {
      FilmId: 24,
      Title: 'ANALYZE HOOSIERS',
      Description:
        'A Thoughtful Display of a Explorer And a Pastry Chef who must Overcome a Feminist in The Sahara Desert',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 6,
      RentalRate: 2.99,
      Length: 181,
      ReplacementCost: 19.99,
      Rating: 'R',
      SpecialFeatures: 'Trailers,Behind the Scenes',
    },
    {
      FilmId: 25,
      Title: 'ANGELS LIFE',
      Description:
        'A Thoughtful Display of a Woman And a Astronaut who must Battle a Robot in Berlin',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 2.99,
      Length: 74,
      ReplacementCost: 15.99,
      Rating: 'G',
      SpecialFeatures: 'Trailers',
    },
    {
      FilmId: 26,
      Title: 'ANNIE IDENTITY',
      Description:
        'A Amazing Panorama of a Pastry Chef And a Boat who must Escape a Woman in An Abandoned Amusement Park',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 3,
      RentalRate: 0.99,
      Length: 86,
      ReplacementCost: 15.99,
      Rating: 'G',
      SpecialFeatures: 'Commentaries,Deleted Scenes',
    },
    {
      FilmId: 27,
      Title: 'ANONYMOUS HUMAN',
      Description:
        'A Amazing Reflection of a Database Administrator And a Astronaut who must Outrace a Database Administrator in A Shark Tank',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 7,
      RentalRate: 0.99,
      Length: 179,
      ReplacementCost: 12.99,
      Rating: 'NC-17',
      SpecialFeatures: 'Deleted Scenes,Behind the Scenes',
    },
    {
      FilmId: 28,
      Title: 'ANTHEM LUKE',
      Description:
        'A Touching Panorama of a Waitress And a Woman who must Outrace a Dog in An Abandoned Amusement Park',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 5,
      RentalRate: 4.99,
      Length: 91,
      ReplacementCost: 16.99,
      Rating: 'PG-13',
      SpecialFeatures: 'Deleted Scenes,Behind the Scenes',
    },
    {
      FilmId: 29,
      Title: 'ANTITRUST TOMATOES',
      Description:
        'A Fateful Yarn of a Womanizer And a Feminist who must Succumb a Database Administrator in Ancient India',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 5,
      RentalRate: 2.99,
      Length: 168,
      ReplacementCost: 11.99,
      Rating: 'NC-17',
      SpecialFeatures: 'Trailers,Commentaries,Deleted Scenes',
    },
    {
      FilmId: 30,
      Title: 'ANYTHING SAVANNAH',
      Description:
        'A Epic Story of a Pastry Chef And a Woman who must Chase a Feminist in An Abandoned Fun House',
      ReleaseYear: 2006,
      LanguageId: 1,
      OriginalLanguageId: null,
      RentalDuration: 4,
      RentalRate: 2.99,
      Length: 82,
      ReplacementCost: 27.99,
      Rating: 'R',
      SpecialFeatures: 'Trailers,Deleted Scenes,Behind the Scenes',
    },
  ],
};

export const initCustomerTable = async (context: any, base: any) => {
  const customerTable = await createTable(context, base, {
    title: 'Customer',
    table_name: 'customer',
    columns: [
      {
        title: 'CustomerId',
        column_name: 'customer_id',
        uidt: UITypes.ID,
      },
      {
        title: 'StoreId',
        column_name: 'store_id',
        uidt: UITypes.Number,
      },
      {
        title: 'FirstName',
        column_name: 'first_name',
        uidt: UITypes.SingleLineText,
      },
      {
        title: 'LastName',
        column_name: 'last_name',
        uidt: UITypes.SingleLineText,
      },
      {
        title: 'Email',
        column_name: 'email',
        uidt: UITypes.Email,
      },
      {
        title: 'AddressId',
        column_name: 'address_id',
        uidt: UITypes.Number,
      },
      {
        title: 'Active',
        column_name: 'active',
        uidt: UITypes.Checkbox,
      },
    ],
  });

  await createBulkRows(context, {
    base: base,
    table: customerTable,
    values: data.Customers,
  });

  return customerTable;
};

export const initFilmTable = async (context: any, base: any) => {
  const filmTable = await createTable(context, base, {
    title: 'Film',
    table_name: 'film',
    columns: [
      {
        title: 'FilmId',
        column_name: 'film_id',
        uidt: UITypes.ID,
      },
      {
        title: 'Title',
        column_name: 'title',
        uidt: UITypes.SingleLineText,
      },
      {
        title: 'Description',
        column_name: 'description',
        uidt: UITypes.LongText,
      },
      {
        title: 'ReleaseYear',
        column_name: 'release_year',
        uidt: UITypes.SingleLineText,
      },
      {
        title: 'LanguageId',
        column_name: 'language_id',
        uidt: UITypes.Number,
      },
      {
        title: 'OriginalLanguageId',
        column_name: 'original_language_id',
        uidt: UITypes.Number,
      },
      {
        title: 'RentalDuration',
        column_name: 'rental_duration',
        uidt: UITypes.Number,
      },
      {
        title: 'RentalRate',
        column_name: 'rental_rate',
        uidt: UITypes.Decimal,
      },
      {
        title: 'Length',
        column_name: 'length',
        uidt: UITypes.Number,
      },
      {
        title: 'ReplacementCost',
        column_name: 'replacement_cost',
        uidt: UITypes.Decimal,
      },
      {
        title: 'Rating',
        column_name: 'rating',
        uidt: UITypes.SingleSelect,
        dtxp: "'G','PG','PG-13','R','NC-17'",
      },
      {
        title: 'SpecialFeatures',
        column_name: 'special_features',
        uidt: UITypes.SingleLineText,
      },
      {
        title: 'LastUpdate',
        column_name: 'last_update',
        uidt: UITypes.DateTime,
      },
    ],
  });

  await createBulkRows(context, {
    base: base,
    table: filmTable,
    values: data.Films,
  });

  return filmTable;
};
