import { UITypes } from 'nocodb-sdk';
import { createTable } from '../../factory/table';
import { createBulkRows } from '../../factory/row';

const data = {
  Customers: [
    {
      CustomerId: 1,
      StoreId: 1,
      FirstName: 'MARY',
      LastName: 'SMITH',
      Email: 'MARY.SMITH@sakilacustomer.org',
      AddressId: 5,
      Active: 1,
    },
    {
      CustomerId: 2,
      StoreId: 1,
      FirstName: 'PATRICIA',
      LastName: 'JOHNSON',
      Email: 'PATRICIA.JOHNSON@sakilacustomer.org',
      AddressId: 6,
      Active: 1,
    },
    {
      CustomerId: 3,
      StoreId: 1,
      FirstName: 'LINDA',
      LastName: 'WILLIAMS',
      Email: 'LINDA.WILLIAMS@sakilacustomer.org',
      AddressId: 7,
      Active: 1,
    },
    {
      CustomerId: 4,
      StoreId: 2,
      FirstName: 'BARBARA',
      LastName: 'JONES',
      Email: 'BARBARA.JONES@sakilacustomer.org',
      AddressId: 8,
      Active: 1,
    },
    {
      CustomerId: 5,
      StoreId: 1,
      FirstName: 'ELIZABETH',
      LastName: 'BROWN',
      Email: 'ELIZABETH.BROWN@sakilacustomer.org',
      AddressId: 9,
      Active: 1,
    },
    {
      CustomerId: 6,
      StoreId: 2,
      FirstName: 'JENNIFER',
      LastName: 'DAVIS',
      Email: 'JENNIFER.DAVIS@sakilacustomer.org',
      AddressId: 10,
      Active: 1,
    },
    {
      CustomerId: 7,
      StoreId: 1,
      FirstName: 'MARIA',
      LastName: 'MILLER',
      Email: 'MARIA.MILLER@sakilacustomer.org',
      AddressId: 11,
      Active: 1,
    },
    {
      CustomerId: 8,
      StoreId: 2,
      FirstName: 'SUSAN',
      LastName: 'WILSON',
      Email: 'SUSAN.WILSON@sakilacustomer.org',
      AddressId: 12,
      Active: 1,
    },
    {
      CustomerId: 9,
      StoreId: 2,
      FirstName: 'MARGARET',
      LastName: 'MOORE',
      Email: 'MARGARET.MOORE@sakilacustomer.org',
      AddressId: 13,
      Active: 1,
    },
    {
      CustomerId: 10,
      StoreId: 1,
      FirstName: 'DOROTHY',
      LastName: 'TAYLOR',
      Email: 'DOROTHY.TAYLOR@sakilacustomer.org',
      AddressId: 14,
      Active: 1,
    },
    {
      CustomerId: 11,
      StoreId: 2,
      FirstName: 'LISA',
      LastName: 'ANDERSON',
      Email: 'LISA.ANDERSON@sakilacustomer.org',
      AddressId: 15,
      Active: 1,
    },
    {
      CustomerId: 12,
      StoreId: 1,
      FirstName: 'NANCY',
      LastName: 'THOMAS',
      Email: 'NANCY.THOMAS@sakilacustomer.org',
      AddressId: 16,
      Active: 1,
    },
    {
      CustomerId: 13,
      StoreId: 2,
      FirstName: 'KAREN',
      LastName: 'JACKSON',
      Email: 'KAREN.JACKSON@sakilacustomer.org',
      AddressId: 17,
      Active: 1,
    },
    {
      CustomerId: 14,
      StoreId: 2,
      FirstName: 'BETTY',
      LastName: 'WHITE',
      Email: 'BETTY.WHITE@sakilacustomer.org',
      AddressId: 18,
      Active: 1,
    },
    {
      CustomerId: 15,
      StoreId: 1,
      FirstName: 'HELEN',
      LastName: 'HARRIS',
      Email: 'HELEN.HARRIS@sakilacustomer.org',
      AddressId: 19,
      Active: 1,
    },
    {
      CustomerId: 16,
      StoreId: 2,
      FirstName: 'SANDRA',
      LastName: 'MARTIN',
      Email: 'SANDRA.MARTIN@sakilacustomer.org',
      AddressId: 20,
      Active: 0,
    },
    {
      CustomerId: 17,
      StoreId: 1,
      FirstName: 'DONNA',
      LastName: 'THOMPSON',
      Email: 'DONNA.THOMPSON@sakilacustomer.org',
      AddressId: 21,
      Active: 1,
    },
    {
      CustomerId: 18,
      StoreId: 2,
      FirstName: 'CAROL',
      LastName: 'GARCIA',
      Email: 'CAROL.GARCIA@sakilacustomer.org',
      AddressId: 22,
      Active: 1,
    },
    {
      CustomerId: 19,
      StoreId: 1,
      FirstName: 'RUTH',
      LastName: 'MARTINEZ',
      Email: 'RUTH.MARTINEZ@sakilacustomer.org',
      AddressId: 23,
      Active: 1,
    },
    {
      CustomerId: 20,
      StoreId: 2,
      FirstName: 'SHARON',
      LastName: 'ROBINSON',
      Email: 'SHARON.ROBINSON@sakilacustomer.org',
      AddressId: 24,
      Active: 1,
    },
    {
      CustomerId: 21,
      StoreId: 1,
      FirstName: 'MICHELLE',
      LastName: 'CLARK',
      Email: 'MICHELLE.CLARK@sakilacustomer.org',
      AddressId: 25,
      Active: 1,
    },
    {
      CustomerId: 22,
      StoreId: 1,
      FirstName: 'LAURA',
      LastName: 'RODRIGUEZ',
      Email: 'LAURA.RODRIGUEZ@sakilacustomer.org',
      AddressId: 26,
      Active: 1,
    },
    {
      CustomerId: 23,
      StoreId: 2,
      FirstName: 'SARAH',
      LastName: 'LEWIS',
      Email: 'SARAH.LEWIS@sakilacustomer.org',
      AddressId: 27,
      Active: 1,
    },
    {
      CustomerId: 24,
      StoreId: 2,
      FirstName: 'KIMBERLY',
      LastName: 'LEE',
      Email: 'KIMBERLY.LEE@sakilacustomer.org',
      AddressId: 28,
      Active: 1,
    },
    {
      CustomerId: 25,
      StoreId: 1,
      FirstName: 'DEBORAH',
      LastName: 'WALKER',
      Email: 'DEBORAH.WALKER@sakilacustomer.org',
      AddressId: 29,
      Active: 1,
    },
    {
      CustomerId: 26,
      StoreId: 2,
      FirstName: 'JESSICA',
      LastName: 'HALL',
      Email: 'JESSICA.HALL@sakilacustomer.org',
      AddressId: 30,
      Active: 1,
    },
    {
      CustomerId: 27,
      StoreId: 2,
      FirstName: 'SHIRLEY',
      LastName: 'ALLEN',
      Email: 'SHIRLEY.ALLEN@sakilacustomer.org',
      AddressId: 31,
      Active: 1,
    },
    {
      CustomerId: 28,
      StoreId: 1,
      FirstName: 'CYNTHIA',
      LastName: 'YOUNG',
      Email: 'CYNTHIA.YOUNG@sakilacustomer.org',
      AddressId: 32,
      Active: 1,
    },
    {
      CustomerId: 29,
      StoreId: 2,
      FirstName: 'ANGELA',
      LastName: 'HERNANDEZ',
      Email: 'ANGELA.HERNANDEZ@sakilacustomer.org',
      AddressId: 33,
      Active: 1,
    },
    {
      CustomerId: 30,
      StoreId: 1,
      FirstName: 'MELISSA',
      LastName: 'KING',
      Email: 'MELISSA.KING@sakilacustomer.org',
      AddressId: 34,
      Active: 1,
    },
  ],
};

export const initCustomerTable = async (context: any, base: any) => {
  const customerTable = await createTable(context, base, {
    title: 'Customer',
    table_name: 'customer',
    columns: [
      {
        title: 'CustomerId',
        column_name: 'customer_id',
        uidt: UITypes.ID,
      },
      {
        title: 'StoreId',
        column_name: 'store_id',
        uidt: UITypes.Number,
      },
      {
        title: 'FirstName',
        column_name: 'first_name',
        uidt: UITypes.SingleLineText,
      },
      {
        title: 'LastName',
        column_name: 'last_name',
        uidt: UITypes.SingleLineText,
      },
      {
        title: 'Email',
        column_name: 'email',
        uidt: UITypes.Email,
      },
      {
        title: 'AddressId',
        column_name: 'address_id',
        uidt: UITypes.Number,
      },
      {
        title: 'Active',
        column_name: 'active',
        uidt: UITypes.Checkbox,
      },
    ],
  });

  await createBulkRows(context, {
    base: base,
    table: customerTable,
    values: data.Customers,
  });

  return customerTable;
};
