/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import AmazonBedrockAi from '@noco-local-integrations/amazon-bedrock-ai';
import AsanaAuth from '@noco-local-integrations/asana-auth';
import AsanaSync from '@noco-local-integrations/asana-sync';
import AzureAi from '@noco-local-integrations/azure-ai';
import ClaudeAi from '@noco-local-integrations/claude-ai';
import ClickhouseAuth from '@noco-local-integrations/clickhouse-auth';
import DeepseekAi from '@noco-local-integrations/deepseek-ai';
import GithubAuth from '@noco-local-integrations/github-auth';
import GithubSync from '@noco-local-integrations/github-sync';
import GitlabAuth from '@noco-local-integrations/gitlab-auth';
import GitlabSync from '@noco-local-integrations/gitlab-sync';
import GoogleAi from '@noco-local-integrations/google-ai';
import GroqAi from '@noco-local-integrations/groq-ai';
import JiraAuth from '@noco-local-integrations/jira-auth';
import JiraSync from '@noco-local-integrations/jira-sync';
import LinearAuth from '@noco-local-integrations/linear-auth';
import LinearSync from '@noco-local-integrations/linear-sync';
import NocodbAi from '@noco-local-integrations/nocodb-ai';
import OpenaiAi from '@noco-local-integrations/openai-ai';
import OpenaiCompatibleAi from '@noco-local-integrations/openai-compatible-ai';

import type { IntegrationEntry } from '@noco-local-integrations/core';

export default [
  AmazonBedrockAi,
  AsanaAuth,
  AsanaSync,
  AzureAi,
  ClaudeAi,
  ClickhouseAuth,
  DeepseekAi,
  GithubAuth,
  GithubSync,
  GitlabAuth,
  GitlabSync,
  GoogleAi,
  GroqAi,
  JiraAuth,
  JiraSync,
  LinearAuth,
  LinearSync,
  NocodbAi,
  OpenaiAi,
  OpenaiCompatibleAi,
] as IntegrationEntry[];
