/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import type { FormDefinition, IntegrationsType } from 'nocodb-sdk';
import type IntegrationWrapper from '~/integrations/integration.wrapper';

import AiCommonManifest from '~/integrations/ai/ai.manifest';
import AuthCommonManifest from '~/integrations/auth/auth.manifest';
import SyncCommonManifest from '~/integrations/sync/sync.manifest';

import AiAmazonBedrockEntry from '~/integrations/ai/amazon-bedrock/entry';
import AiAmazonBedrockForm from '~/integrations/ai/amazon-bedrock/form';
import AiAmazonBedrockManifest from '~/integrations/ai/amazon-bedrock/manifest';
import AiAzureEntry from '~/integrations/ai/azure/entry';
import AiAzureForm from '~/integrations/ai/azure/form';
import AiAzureManifest from '~/integrations/ai/azure/manifest';
import AiClaudeEntry from '~/integrations/ai/claude/entry';
import AiClaudeForm from '~/integrations/ai/claude/credentials.form';
import AiClaudeManifest from '~/integrations/ai/claude/manifest';
import AiDeepseekEntry from '~/integrations/ai/deepseek/entry';
import AiDeepseekForm from '~/integrations/ai/deepseek/credentials.form';
import AiDeepseekManifest from '~/integrations/ai/deepseek/manifest';
import AiGoogleEntry from '~/integrations/ai/google/entry';
import AiGoogleForm from '~/integrations/ai/google/credentials.form';
import AiGoogleManifest from '~/integrations/ai/google/manifest';
import AiGroqEntry from '~/integrations/ai/groq/entry';
import AiGroqForm from '~/integrations/ai/groq/credentials.form';
import AiGroqManifest from '~/integrations/ai/groq/manifest';
import AiNocodbEntry from '~/integrations/ai/nocodb/entry';
import AiNocodbForm from '~/integrations/ai/nocodb/credentials.form';
import AiNocodbManifest from '~/integrations/ai/nocodb/manifest';
import AiOpenaiCompatibleEntry from '~/integrations/ai/openai-compatible/entry';
import AiOpenaiCompatibleForm from '~/integrations/ai/openai-compatible/credentials.form';
import AiOpenaiCompatibleManifest from '~/integrations/ai/openai-compatible/manifest';
import AiOpenaiEntry from '~/integrations/ai/openai/entry';
import AiOpenaiForm from '~/integrations/ai/openai/credentials.form';
import AiOpenaiManifest from '~/integrations/ai/openai/manifest';
import AuthClickhouseEntry from '~/integrations/auth/clickhouse/entry';
import AuthClickhouseForm from '~/integrations/auth/clickhouse/form';
import AuthClickhouseManifest from '~/integrations/auth/clickhouse/manifest';
import AuthGithubEntry from '~/integrations/auth/github/entry';
import AuthGithubForm from '~/integrations/auth/github/form';
import AuthGithubManifest from '~/integrations/auth/github/manifest';
import AuthGitlabEntry from '~/integrations/auth/gitlab/entry';
import AuthGitlabForm from '~/integrations/auth/gitlab/form';
import AuthGitlabManifest from '~/integrations/auth/gitlab/manifest';
import AuthNocodbEntry from '~/integrations/auth/nocodb/entry';
import AuthNocodbForm from '~/integrations/auth/nocodb/form';
import AuthNocodbManifest from '~/integrations/auth/nocodb/manifest';
import AuthRestEntry from '~/integrations/auth/rest/entry';
import AuthRestForm from '~/integrations/auth/rest/form';
import AuthRestManifest from '~/integrations/auth/rest/manifest';
import SyncClickhouseTableEntry from '~/integrations/sync/clickhouse-table/entry';
import SyncClickhouseTableForm from '~/integrations/sync/clickhouse-table/form';
import SyncClickhouseTableManifest from '~/integrations/sync/clickhouse-table/manifest';
import SyncGithubIssuesEntry from '~/integrations/sync/github-issues/entry';
import SyncGithubIssuesForm from '~/integrations/sync/github-issues/form';
import SyncGithubIssuesManifest from '~/integrations/sync/github-issues/manifest';
import SyncGitlabIssuesEntry from '~/integrations/sync/gitlab-issues/entry';
import SyncGitlabIssuesForm from '~/integrations/sync/gitlab-issues/form';
import SyncGitlabIssuesManifest from '~/integrations/sync/gitlab-issues/manifest';
import SyncUniversalRestEntry from '~/integrations/sync/universal-rest/entry';
import SyncUniversalRestForm from '~/integrations/sync/universal-rest/form';
import SyncUniversalRestManifest from '~/integrations/sync/universal-rest/manifest';

export default [
  {
    type: 'ai',
    sub_type: 'amazon-bedrock',
    wrapper: AiAmazonBedrockEntry,
    form: AiAmazonBedrockForm,
    meta: {
      ...AiCommonManifest,
      ...AiAmazonBedrockManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'azure',
    wrapper: AiAzureEntry,
    form: AiAzureForm,
    meta: {
      ...AiCommonManifest,
      ...AiAzureManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'claude',
    wrapper: AiClaudeEntry,
    form: AiClaudeForm,
    meta: {
      ...AiCommonManifest,
      ...AiClaudeManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'deepseek',
    wrapper: AiDeepseekEntry,
    form: AiDeepseekForm,
    meta: {
      ...AiCommonManifest,
      ...AiDeepseekManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'google',
    wrapper: AiGoogleEntry,
    form: AiGoogleForm,
    meta: {
      ...AiCommonManifest,
      ...AiGoogleManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'groq',
    wrapper: AiGroqEntry,
    form: AiGroqForm,
    meta: {
      ...AiCommonManifest,
      ...AiGroqManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'nocodb',
    wrapper: AiNocodbEntry,
    form: AiNocodbForm,
    meta: {
      ...AiCommonManifest,
      ...AiNocodbManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'openai-compatible',
    wrapper: AiOpenaiCompatibleEntry,
    form: AiOpenaiCompatibleForm,
    meta: {
      ...AiCommonManifest,
      ...AiOpenaiCompatibleManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'openai',
    wrapper: AiOpenaiEntry,
    form: AiOpenaiForm,
    meta: {
      ...AiCommonManifest,
      ...AiOpenaiManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'clickhouse',
    wrapper: AuthClickhouseEntry,
    form: AuthClickhouseForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthClickhouseManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'github',
    wrapper: AuthGithubEntry,
    form: AuthGithubForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthGithubManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'gitlab',
    wrapper: AuthGitlabEntry,
    form: AuthGitlabForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthGitlabManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'nocodb',
    wrapper: AuthNocodbEntry,
    form: AuthNocodbForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthNocodbManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'rest',
    wrapper: AuthRestEntry,
    form: AuthRestForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthRestManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'clickhouse-table',
    wrapper: SyncClickhouseTableEntry,
    form: SyncClickhouseTableForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncClickhouseTableManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'github-issues',
    wrapper: SyncGithubIssuesEntry,
    form: SyncGithubIssuesForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncGithubIssuesManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'gitlab-issues',
    wrapper: SyncGitlabIssuesEntry,
    form: SyncGitlabIssuesForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncGitlabIssuesManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'universal-rest',
    wrapper: SyncUniversalRestEntry,
    form: SyncUniversalRestForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncUniversalRestManifest,
    },
  },
] as {
  type: IntegrationsType;
  sub_type: string;
  form?: FormDefinition;
  wrapper?: typeof IntegrationWrapper;
  meta?: {
    title?: string;
    value?: string;
    icon?: string;
    description?: string;
    exposedEndpoints?: string[];
  };
}[];
