/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import type { FormDefinition, IntegrationsType } from 'nocodb-sdk';
import type IntegrationWrapper from '~/integrations/integration.wrapper';

import AiCommonManifest from '~/integrations/ai/ai.manifest';
import AuthCommonManifest from '~/integrations/auth/auth.manifest';
import SyncCommonManifest from '~/integrations/sync/sync.manifest';

import AiAmazonBedrockEntry from '~/integrations/ai/amazon-bedrock/amazon-bedrock.entry';
import AiAmazonBedrockForm from '~/integrations/ai/amazon-bedrock/amazon-bedrock.form';
import AiAmazonBedrockManifest from '~/integrations/ai/amazon-bedrock/amazon-bedrock.manifest';
import AiAzureEntry from '~/integrations/ai/azure/azure.entry';
import AiAzureForm from '~/integrations/ai/azure/azure.form';
import AiAzureManifest from '~/integrations/ai/azure/azure.manifest';
import AiClaudeEntry from '~/integrations/ai/claude/claude.entry';
import AiClaudeForm from '~/integrations/ai/claude/claude.form';
import AiClaudeManifest from '~/integrations/ai/claude/claude.manifest';
import AiDeepseekEntry from '~/integrations/ai/deepseek/deepseek.entry';
import AiDeepseekForm from '~/integrations/ai/deepseek/deepseek.form';
import AiDeepseekManifest from '~/integrations/ai/deepseek/deepseek.manifest';
import AiGoogleEntry from '~/integrations/ai/google/google.entry';
import AiGoogleForm from '~/integrations/ai/google/google.form';
import AiGoogleManifest from '~/integrations/ai/google/google.manifest';
import AiGroqEntry from '~/integrations/ai/groq/groq.entry';
import AiGroqForm from '~/integrations/ai/groq/groq.form';
import AiGroqManifest from '~/integrations/ai/groq/groq.manifest';
import AiNocodbEntry from '~/integrations/ai/nocodb/nocodb.entry';
import AiNocodbForm from '~/integrations/ai/nocodb/nocodb.form';
import AiNocodbManifest from '~/integrations/ai/nocodb/nocodb.manifest';
import AiOpenaiCompatibleEntry from '~/integrations/ai/openai-compatible/openai-compatible.entry';
import AiOpenaiCompatibleForm from '~/integrations/ai/openai-compatible/openai-compatible.form';
import AiOpenaiCompatibleManifest from '~/integrations/ai/openai-compatible/openai-compatible.manifest';
import AiOpenaiEntry from '~/integrations/ai/openai/openai.entry';
import AiOpenaiForm from '~/integrations/ai/openai/openai.form';
import AiOpenaiManifest from '~/integrations/ai/openai/openai.manifest';
import AuthClickhouseEntry from '~/integrations/auth/clickhouse/clickhouse.entry';
import AuthClickhouseForm from '~/integrations/auth/clickhouse/clickhouse.form';
import AuthClickhouseManifest from '~/integrations/auth/clickhouse/clickhouse.manifest';
import AuthGithubEntry from '~/integrations/auth/github/github.entry';
import AuthGithubForm from '~/integrations/auth/github/github.form';
import AuthGithubManifest from '~/integrations/auth/github/github.manifest';
import AuthGitlabEntry from '~/integrations/auth/gitlab/gitlab.entry';
import AuthGitlabForm from '~/integrations/auth/gitlab/gitlab.form';
import AuthGitlabManifest from '~/integrations/auth/gitlab/gitlab.manifest';
import AuthJiraEntry from '~/integrations/auth/jira/jira.entry';
import AuthJiraForm from '~/integrations/auth/jira/jira.form';
import AuthJiraManifest from '~/integrations/auth/jira/jira.manifest';
import AuthLinearEntry from '~/integrations/auth/linear/linear.entry';
import AuthLinearForm from '~/integrations/auth/linear/linear.form';
import AuthLinearManifest from '~/integrations/auth/linear/linear.manifest';
import AuthNocodbEntry from '~/integrations/auth/nocodb/nocodb.entry';
import AuthNocodbForm from '~/integrations/auth/nocodb/nocodb.form';
import AuthNocodbManifest from '~/integrations/auth/nocodb/nocodb.manifest';
import AuthRestEntry from '~/integrations/auth/rest/rest.entry';
import AuthRestForm from '~/integrations/auth/rest/rest.form';
import AuthRestManifest from '~/integrations/auth/rest/rest.manifest';
import AuthZendeskEntry from '~/integrations/auth/zendesk/zendesk.entry';
import AuthZendeskForm from '~/integrations/auth/zendesk/zendesk.form';
import AuthZendeskManifest from '~/integrations/auth/zendesk/zendesk.manifest';
import SyncClickhouseTableEntry from '~/integrations/sync/clickhouse-table/clickhouse-table.entry';
import SyncClickhouseTableForm from '~/integrations/sync/clickhouse-table/clickhouse-table.form';
import SyncClickhouseTableManifest from '~/integrations/sync/clickhouse-table/clickhouse-table.manifest';
import SyncGithubIssuesEntry from '~/integrations/sync/github-issues/github-issues.entry';
import SyncGithubIssuesForm from '~/integrations/sync/github-issues/github-issues.form';
import SyncGithubIssuesManifest from '~/integrations/sync/github-issues/github-issues.manifest';
import SyncGitlabIssuesEntry from '~/integrations/sync/gitlab-issues/gitlab-issues.entry';
import SyncGitlabIssuesForm from '~/integrations/sync/gitlab-issues/gitlab-issues.form';
import SyncGitlabIssuesManifest from '~/integrations/sync/gitlab-issues/gitlab-issues.manifest';
import SyncJiraIssuesEntry from '~/integrations/sync/jira-issues/jira-issues.entry';
import SyncJiraIssuesForm from '~/integrations/sync/jira-issues/jira-issues.form';
import SyncJiraIssuesManifest from '~/integrations/sync/jira-issues/jira-issues.manifest';
import SyncLinearIssuesEntry from '~/integrations/sync/linear-issues/linear-issues.entry';
import SyncLinearIssuesForm from '~/integrations/sync/linear-issues/linear-issues.form';
import SyncLinearIssuesManifest from '~/integrations/sync/linear-issues/linear-issues.manifest';
import SyncUniversalRestEntry from '~/integrations/sync/universal-rest/universal-rest.entry';
import SyncUniversalRestForm from '~/integrations/sync/universal-rest/universal-rest.form';
import SyncUniversalRestManifest from '~/integrations/sync/universal-rest/universal-rest.manifest';
import SyncZendeskTicketsEntry from '~/integrations/sync/zendesk-tickets/zendesk-tickets.entry';
import SyncZendeskTicketsForm from '~/integrations/sync/zendesk-tickets/zendesk-tickets.form';
import SyncZendeskTicketsManifest from '~/integrations/sync/zendesk-tickets/zendesk-tickets.manifest';

export default [
  {
    type: 'ai',
    sub_type: 'amazon-bedrock',
    wrapper: AiAmazonBedrockEntry,
    form: AiAmazonBedrockForm,
    meta: {
      ...AiCommonManifest,
      ...AiAmazonBedrockManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'azure',
    wrapper: AiAzureEntry,
    form: AiAzureForm,
    meta: {
      ...AiCommonManifest,
      ...AiAzureManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'claude',
    wrapper: AiClaudeEntry,
    form: AiClaudeForm,
    meta: {
      ...AiCommonManifest,
      ...AiClaudeManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'deepseek',
    wrapper: AiDeepseekEntry,
    form: AiDeepseekForm,
    meta: {
      ...AiCommonManifest,
      ...AiDeepseekManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'google',
    wrapper: AiGoogleEntry,
    form: AiGoogleForm,
    meta: {
      ...AiCommonManifest,
      ...AiGoogleManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'groq',
    wrapper: AiGroqEntry,
    form: AiGroqForm,
    meta: {
      ...AiCommonManifest,
      ...AiGroqManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'nocodb',
    wrapper: AiNocodbEntry,
    form: AiNocodbForm,
    meta: {
      ...AiCommonManifest,
      ...AiNocodbManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'openai-compatible',
    wrapper: AiOpenaiCompatibleEntry,
    form: AiOpenaiCompatibleForm,
    meta: {
      ...AiCommonManifest,
      ...AiOpenaiCompatibleManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'openai',
    wrapper: AiOpenaiEntry,
    form: AiOpenaiForm,
    meta: {
      ...AiCommonManifest,
      ...AiOpenaiManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'clickhouse',
    wrapper: AuthClickhouseEntry,
    form: AuthClickhouseForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthClickhouseManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'github',
    wrapper: AuthGithubEntry,
    form: AuthGithubForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthGithubManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'gitlab',
    wrapper: AuthGitlabEntry,
    form: AuthGitlabForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthGitlabManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'jira',
    wrapper: AuthJiraEntry,
    form: AuthJiraForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthJiraManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'linear',
    wrapper: AuthLinearEntry,
    form: AuthLinearForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthLinearManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'nocodb',
    wrapper: AuthNocodbEntry,
    form: AuthNocodbForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthNocodbManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'rest',
    wrapper: AuthRestEntry,
    form: AuthRestForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthRestManifest,
    },
  },
  {
    type: 'auth',
    sub_type: 'zendesk',
    wrapper: AuthZendeskEntry,
    form: AuthZendeskForm,
    meta: {
      ...AuthCommonManifest,
      ...AuthZendeskManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'clickhouse-table',
    wrapper: SyncClickhouseTableEntry,
    form: SyncClickhouseTableForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncClickhouseTableManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'github-issues',
    wrapper: SyncGithubIssuesEntry,
    form: SyncGithubIssuesForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncGithubIssuesManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'gitlab-issues',
    wrapper: SyncGitlabIssuesEntry,
    form: SyncGitlabIssuesForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncGitlabIssuesManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'jira-issues',
    wrapper: SyncJiraIssuesEntry,
    form: SyncJiraIssuesForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncJiraIssuesManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'linear-issues',
    wrapper: SyncLinearIssuesEntry,
    form: SyncLinearIssuesForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncLinearIssuesManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'universal-rest',
    wrapper: SyncUniversalRestEntry,
    form: SyncUniversalRestForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncUniversalRestManifest,
    },
  },
  {
    type: 'sync',
    sub_type: 'zendesk-tickets',
    wrapper: SyncZendeskTicketsEntry,
    form: SyncZendeskTicketsForm,
    meta: {
      ...SyncCommonManifest,
      ...SyncZendeskTicketsManifest,
    },
  },
] as {
  type: IntegrationsType;
  sub_type: string;
  form?: FormDefinition;
  wrapper?: typeof IntegrationWrapper;
  meta?: {
    title?: string;
    value?: string;
    icon?: string;
    description?: string;
    exposedEndpoints?: string[];
  };
}[];
