/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import type { FormDefinition, IntegrationsType } from 'nocodb-sdk';
import type IntegrationWrapper from '~/integrations/integration.wrapper';

import AiCommonManifest from '~/integrations/ai/ai.manifest';

import AiAmazonBedrockEntry from '~/integrations/ai/amazon-bedrock/entry';
import AiAmazonBedrockForm from '~/integrations/ai/amazon-bedrock/form';
import AiAmazonBedrockManifest from '~/integrations/ai/amazon-bedrock/manifest';
import AiAzureEntry from '~/integrations/ai/azure/entry';
import AiAzureForm from '~/integrations/ai/azure/form';
import AiAzureManifest from '~/integrations/ai/azure/manifest';
import AiClaudeEntry from '~/integrations/ai/claude/entry';
import AiClaudeForm from '~/integrations/ai/claude/credentials.form';
import AiClaudeManifest from '~/integrations/ai/claude/manifest';
import AiDeepseekEntry from '~/integrations/ai/deepseek/entry';
import AiDeepseekForm from '~/integrations/ai/deepseek/credentials.form';
import AiDeepseekManifest from '~/integrations/ai/deepseek/manifest';
import AiGoogleEntry from '~/integrations/ai/google/entry';
import AiGoogleForm from '~/integrations/ai/google/credentials.form';
import AiGoogleManifest from '~/integrations/ai/google/manifest';
import AiGroqEntry from '~/integrations/ai/groq/entry';
import AiGroqForm from '~/integrations/ai/groq/credentials.form';
import AiGroqManifest from '~/integrations/ai/groq/manifest';
import AiNocodbEntry from '~/integrations/ai/nocodb/entry';
import AiNocodbForm from '~/integrations/ai/nocodb/credentials.form';
import AiNocodbManifest from '~/integrations/ai/nocodb/manifest';
import AiOpenaiCompatibleEntry from '~/integrations/ai/openai-compatible/entry';
import AiOpenaiCompatibleForm from '~/integrations/ai/openai-compatible/credentials.form';
import AiOpenaiCompatibleManifest from '~/integrations/ai/openai-compatible/manifest';
import AiOpenaiEntry from '~/integrations/ai/openai/entry';
import AiOpenaiForm from '~/integrations/ai/openai/credentials.form';
import AiOpenaiManifest from '~/integrations/ai/openai/manifest';

export default [
  {
    type: 'ai',
    sub_type: 'amazon-bedrock',
    wrapper: AiAmazonBedrockEntry,
    form: AiAmazonBedrockForm,
    meta: {
      ...AiCommonManifest,
      ...AiAmazonBedrockManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'azure',
    wrapper: AiAzureEntry,
    form: AiAzureForm,
    meta: {
      ...AiCommonManifest,
      ...AiAzureManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'claude',
    wrapper: AiClaudeEntry,
    form: AiClaudeForm,
    meta: {
      ...AiCommonManifest,
      ...AiClaudeManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'deepseek',
    wrapper: AiDeepseekEntry,
    form: AiDeepseekForm,
    meta: {
      ...AiCommonManifest,
      ...AiDeepseekManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'google',
    wrapper: AiGoogleEntry,
    form: AiGoogleForm,
    meta: {
      ...AiCommonManifest,
      ...AiGoogleManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'groq',
    wrapper: AiGroqEntry,
    form: AiGroqForm,
    meta: {
      ...AiCommonManifest,
      ...AiGroqManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'nocodb',
    wrapper: AiNocodbEntry,
    form: AiNocodbForm,
    meta: {
      ...AiCommonManifest,
      ...AiNocodbManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'openai-compatible',
    wrapper: AiOpenaiCompatibleEntry,
    form: AiOpenaiCompatibleForm,
    meta: {
      ...AiCommonManifest,
      ...AiOpenaiCompatibleManifest,
    },
  },
  {
    type: 'ai',
    sub_type: 'openai',
    wrapper: AiOpenaiEntry,
    form: AiOpenaiForm,
    meta: {
      ...AiCommonManifest,
      ...AiOpenaiManifest,
    },
  },
] as {
  type: IntegrationsType;
  sub_type: string;
  form?: FormDefinition;
  wrapper?: typeof IntegrationWrapper;
  meta?: {
    title?: string;
    value?: string;
    icon?: string;
    description?: string;
    exposedEndpoints?: string[];
  };
}[];
