export default {
  'ID': {},
  'ForeignKey': {},
  'SingleLineText': {w: '150px'},
  'LongText': {w: '400px'},
  'Attachment': {},
  'Checkbox': {},
  'MultiSelect': {w: '150px'},
  'SingleSelect': {},
  'Collaborator': {},
  'Date': {},
  'Year': {},
  'Time': {},
  'PhoneNumber': {},
  'Email': {},
  'URL': {},
  'Number': {},
  'Decimal': {},
  'Currency': {},
  'Percent': {},
  'Duration': {},
  'Rating': {},
  'Formula': {},
  'Rollup': {},
  'Count': {},
  'Lookup': {},
  'DateTime': {},
  'CreateTime': {},
  'LastModifiedTime': {},
  'AutoNumber': {},
  'Barcode': {},
  'Button': {},
}
