const defaultColumns = [
  {
    ai: true,
    altered: 1,
    cdf: null,
    ck: false,
    clen: null,
    column_name: 'id',
    ct: 'int(11)',
    dt: 'int',
    dtx: 'integer',
    dtxp: '11',
    dtxs: '',
    np: 11,
    nrqd: false,
    ns: 0,
    pk: true,
    rqd: true,
    title: 'Id',
    uicn: '',
    uidt: 'ID',
    uip: '',
    un: true,
  },
  {
    ai: false,
    altered: 1,
    cdf: null,
    ck: false,
    clen: 45,
    column_name: 'title',
    ct: 'varchar(45)',
    dt: 'varchar',
    dtx: 'specificType',
    dtxp: '45',
    dtxs: '',
    np: null,
    nrqd: true,
    ns: null,
    pk: false,
    rqd: false,
    title: 'Title',
    uicn: '',
    uidt: 'SingleLineText',
    uip: '',
    un: false,
  },
  {
    ai: false,
    altered: 1,
    cdf: 'CURRENT_TIMESTAMP',
    ck: false,
    clen: 45,
    column_name: 'created_at',
    ct: 'varchar(45)',
    dt: 'timestamp',
    dtx: 'specificType',
    dtxp: '',
    dtxs: '',
    np: null,
    nrqd: true,
    ns: null,
    pk: false,
    rqd: false,
    title: 'CreatedAt',
    uicn: '',
    uidt: 'DateTime',
    uip: '',
    un: false,
  },
  {
    ai: false,
    altered: 1,
    cdf: 'CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP',
    ck: false,
    clen: 45,
    column_name: 'updated_at',
    ct: 'varchar(45)',
    dt: 'timestamp',
    dtx: 'specificType',
    dtxp: '',
    dtxs: '',
    np: null,
    nrqd: true,
    ns: null,
    pk: false,
    rqd: false,
    title: 'UpdatedAt',
    uicn: '',
    uidt: 'DateTime',
    uip: '',
    un: false,
  },
];

export { defaultColumns };
