/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import ClickhouseAuth from '@noco-local-integrations/clickhouse-auth';
import GithubAuth from '@noco-local-integrations/github-auth';
import GithubSync from '@noco-local-integrations/github-sync';
import GitlabAuth from '@noco-local-integrations/gitlab-auth';
import GitlabSync from '@noco-local-integrations/gitlab-sync';
import NocodbAi from '@noco-local-integrations/nocodb-ai';
import OpenaiAi from '@noco-local-integrations/openai-ai';

import type { IntegrationEntry } from '@noco-local-integrations/core';

export default [
  ClickhouseAuth,
  GithubAuth,
  GithubSync,
  GitlabAuth,
  GitlabSync,
  NocodbAi,
  OpenaiAi,
] as IntegrationEntry[];
