/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import AsanaAuth from '@noco-local-integrations/asana-auth';
import AsanaSync from '@noco-local-integrations/asana-sync';
import ClickhouseAuth from '@noco-local-integrations/clickhouse-auth';
import GithubAuth from '@noco-local-integrations/github-auth';
import GithubSync from '@noco-local-integrations/github-sync';
import GitlabAuth from '@noco-local-integrations/gitlab-auth';
import GitlabSync from '@noco-local-integrations/gitlab-sync';
import JiraAuth from '@noco-local-integrations/jira-auth';
import JiraSync from '@noco-local-integrations/jira-sync';
import LinearAuth from '@noco-local-integrations/linear-auth';
import LinearSync from '@noco-local-integrations/linear-sync';
import NocodbAi from '@noco-local-integrations/nocodb-ai';
import OpenaiAi from '@noco-local-integrations/openai-ai';

import type { IntegrationEntry } from '@noco-local-integrations/core';

export default [
  AsanaAuth,
  AsanaSync,
  ClickhouseAuth,
  GithubAuth,
  GithubSync,
  GitlabAuth,
  GitlabSync,
  JiraAuth,
  JiraSync,
  LinearAuth,
  LinearSync,
  NocodbAi,
  OpenaiAi,
] as IntegrationEntry[];
