/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import ClickhouseAuth from '@noco-local-integrations/clickhouse-auth';
import ClickhouseTableSync from '@noco-local-integrations/clickhouse-table-sync';
import GithubAuth from '@noco-local-integrations/github-auth';
import GithubIssuesSync from '@noco-local-integrations/github-issues-sync';
import NocodbAi from '@noco-local-integrations/nocodb-ai';
import OpenaiAi from '@noco-local-integrations/openai-ai';

import type { IntegrationEntry } from '@noco-local-integrations/core';

export default [
  ClickhouseAuth,
  ClickhouseTableSync,
  GithubAuth,
  GithubIssuesSync,
  NocodbAi,
  OpenaiAi,
] as IntegrationEntry[];
