/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import { FormDefinition, IntegrationsType } from 'nocodb-sdk';
import IntegrationWrapper from '~/integrations/integration.wrapper';

import AiCommonManifest from '~/integrations/ai/ai.manifest';

import AiClaudeEntry from '~/integrations/ai/claude/entry';
import AiClaudeForm from '~/integrations/ai/claude/credentials.form';
import AiClaudeManifest from '~/integrations/ai/claude/manifest';
import AiGroqEntry from '~/integrations/ai/groq/entry';
import AiGroqForm from '~/integrations/ai/groq/credentials.form';
import AiGroqManifest from '~/integrations/ai/groq/manifest';
import AiOpenaiEntry from '~/integrations/ai/openai/entry';
import AiOpenaiForm from '~/integrations/ai/openai/credentials.form';
import AiOpenaiManifest from '~/integrations/ai/openai/manifest';


export default [
  {
    type: 'ai',
    subType: 'claude',
    wrapper: AiClaudeEntry,
    form: AiClaudeForm,
    meta: {
      ...AiCommonManifest,
      ...AiClaudeManifest,
    },
  },
  {
    type: 'ai',
    subType: 'groq',
    wrapper: AiGroqEntry,
    form: AiGroqForm,
    meta: {
      ...AiCommonManifest,
      ...AiGroqManifest,
    },
  },
  {
    type: 'ai',
    subType: 'openai',
    wrapper: AiOpenaiEntry,
    form: AiOpenaiForm,
    meta: {
      ...AiCommonManifest,
      ...AiOpenaiManifest,
    },
  },
] as {
  type: IntegrationsType;
  subType: string;
  form?: FormDefinition;
  wrapper?: typeof IntegrationWrapper;
  meta?: {
    title?: string;
    value?: string;
    icon?: string;
    description?: string;
    exposedEndpoints?: string[];
  };
}[];
