/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import type { FormDefinition, IntegrationsType } from 'nocodb-sdk';
import type IntegrationWrapper from '~/integrations/integration.wrapper';

export default [] as {
  type: IntegrationsType;
  sub_type: string;
  form?: FormDefinition;
  wrapper?: typeof IntegrationWrapper;
  meta?: {
    title?: string;
    value?: string;
    icon?: string;
    description?: string;
    exposedEndpoints?: string[];
  };
}[];
