// https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-2017

export default {
  bigint: {},
  numeric: {},
  bit: {},
  smallint: {},
  decimal: {},
  smallmoney: {},
  int: {},
  tinyint: {},
  money: {},
  float: {},
  real: {},
  date: {},
  datetimeoffset: {},
  datetime2: {},
  smalldatetime: {},
  datetime: {},
  time: {},
  char: {},
  varchar: {},
  text: {},
  nchar: {},
  nvarchar: {},
  ntext: {},
  binary: {},
  varbinary: {},
  image: {},
  cursor: {},
  rowversion: {},
  hierarchyid: {},
  uniqueidentifier: {},
  sql_variant: {},
  xml: {},
  'Spatial Geometry Types': {},
  'Spatial Geography Types': {},
  table: {},
};
