export const defaultViews = [
  {
    ptn: 'Table-1',
    _ptn: 'Table-1',
    ptype: 'table',
    tn: 'Table-1',
    _tn: 'Table-1',
    table_meta: {
      hasNonDefaultViews: false,
    },
    id: 'vw84fn9hsxrz14b1',
    source_id: 'bmpgnvh49n8i51l',
    base_id: 'pRdVnZXPZgA',
    fk_model_id: 'mtWA9ZXvsuh',
    title: 'Table-1',
    type: 3,
    is_default: true,
    show_system_fields: null,
    lock_type: 'collaborative',
    uuid: null,
    password: null,
    show: true,
    order: 1,
    created_at: '2025-04-21 08:28:04+00:00',
    updated_at: '2025-04-21 08:28:04+00:00',
    meta: {},
    description: null,
    created_by: null,
    owned_by: null,
    fk_workspace_id: 'wv4stxso',
    attachment_mode_column_id: null,
    expanded_record_mode: 'field',
    fk_custom_url_id: null,
    view: {
      fk_view_id: 'vw84fn9hsxrz14b1',
      source_id: 'bmpgnvh49n8i51l',
      base_id: 'ptj6yehq48r8i0o',
      uuid: null,
      created_at: '2025-04-21 08:28:04+00:00',
      updated_at: '2025-04-21 08:28:04+00:00',
      meta: null,
      row_height: null,
      fk_workspace_id: 'wv4stxso',
    },
    disabled: {
      owner: false,
      creator: false,
      viewer: false,
      editor: false,
      commenter: false,
      guest: false,
    },
  },
]
