// Copy of the feature nouns and aliases in nc-gui/tele/.tele-glossary.json; nc-gui's
// licenseActivityVocabulary test fails when the two drift.
export const LICENSE_ACTIVITY_FEATURES = [
  'account',
  'actions',
  'admin',
  'agent',
  'agent-section',
  'api-token',
  'app',
  'app-factory',
  'appstore',
  'attachment',
  'audit',
  'auth',
  'automation',
  'automation-section',
  'base',
  'base-trash',
  'base-variables',
  'bookmark',
  'calendar',
  'cell',
  'chat',
  'claim',
  'command-palette',
  'comment',
  'comment-expand',
  'credits',
  'dashboard',
  'data',
  'date-dependency',
  'doc',
  'download',
  'environment',
  'erd',
  'execute',
  'extension',
  'field',
  'filter',
  'filter-pinned',
  'form-view',
  'gantt',
  'group-by',
  'import',
  'integration',
  'interface',
  'invite',
  'kanban',
  'link',
  'list',
  'lookup',
  'managed-app',
  'map',
  'marketplace',
  'mcp-connection',
  'navbar',
  'navdraw',
  'nocodb',
  'oauth-authorization',
  'oauth-client',
  'on-prem',
  'org',
  'org-environment',
  'org-team',
  'page-designer',
  'payment',
  'permissions',
  'presence',
  'quick-import',
  'record',
  'record-expand',
  'rls',
  'rollup',
  'row-color',
  'sandbox',
  'scim',
  'script',
  'section',
  'settings',
  'share',
  'shortcut',
  'sidebar',
  'signin',
  'snapshot',
  'snippet',
  'sort',
  'source',
  'summarize',
  'sync',
  'table',
  'team',
  'template',
  'theme',
  'timeline',
  'toolbar',
  'topbar',
  'tour',
  'translate',
  'ui',
  'upgrade',
  'user',
  'vault',
  'view',
  'view-section',
  'view-selector',
  'webhook',
  'white-label',
  'workflow',
  'ws',
] as const;

export const LICENSE_ACTIVITY_ALIASES: Readonly<Record<string, string>> = {
  project: 'base',
  'proj-meta': 'base',
  column: 'field',
  columns: 'field',
  fields: 'field',
  row: 'record',
  rows: 'record',
  'row-expand': 'record-expand',
  'row-expand-panel': 'record-expand',
  'expanded-form': 'record-expand',
  workspace: 'ws',
  organization: 'org',
  document: 'doc',
  documents: 'doc',
  docs: 'doc',
  cmdk: 'command-palette',
  cmdL: 'command-palette',
  cmdj: 'command-palette',
  leftSidebar: 'sidebar',
  extensions: 'extension',
  themes: 'theme',
  templates: 'template',
  scripts: 'script',
  links: 'link',
  'table-sync': 'sync',
  'sync-airtable': 'sync',
  'integration-sync': 'sync',
  extdb: 'source',
  'shared-base': 'share',
  'form-share': 'share',
  'org-user': 'org',
  users: 'user',
  member: 'user',
  members: 'user',
};
