const allowedDomains = [
  'airtable.com',
  '*.airtable.com',
  'asana.com',
  '*.asana.com',
  'atlassian.com',
  '*.atlassian.com',
  'basecamp.com',
  '*.basecamp.com',
  'cal.com',
  '*.cal.com',
  'calendly.com',
  '*.calendly.com',
  'canva.com',
  '*.canva.com',
  'clickup.com',
  '*.clickup.com',
  'coda.io',
  '*.coda.io',
  'codepen.io',
  '*.codepen.io',
  'codesandbox.io',
  '*.codesandbox.io',
  'datawrapper.de',
  '*.datawrapper.de',
  'dbdiagram.io',
  '*.dbdiagram.io',
  'descript.com',
  '*.descript.com',
  'diagrams.net',
  '*.diagrams.net',
  'draw.io',
  '*.draw.io',
  'dropbox.com',
  '*.dropbox.com',
  'figma.com',
  '*.figma.com',
  'forms.gle',
  '*.forms.gle',
  'framer.com',
  '*.framer.com',
  '*.framer.website',
  'getgrist.com',
  '*.getgrist.com',
  'gist.github.com',
  'github.com',
  '*.github.com',
  'gitbook.com',
  '*.gitbook.com',
  'gitlab.com',
  '*.gitlab.com',
  'gliffy.com',
  '*.gliffy.com',
  'google.com',
  '*.google.com',
  'instagram.com',
  '*.instagram.com',
  'invisionapp.com',
  '*.invisionapp.com',
  'jotform.com',
  '*.jotform.com',
  'jsfiddle.net',
  '*.jsfiddle.net',
  'linear.app',
  '*.linear.app',
  'loom.com',
  '*.loom.com',
  'looker.com',
  '*.looker.com',
  'lucid.co',
  '*.lucid.co',
  'lucidchart.com',
  '*.lucidchart.com',
  'make.com',
  '*.make.com',
  'marvelapp.com',
  '*.marvelapp.com',
  'metabase.com',
  '*.metabase.com',
  'mindmeister.com',
  '*.mindmeister.com',
  'miro.com',
  '*.miro.com',
  'monday.com',
  '*.monday.com',
  'mural.co',
  '*.mural.co',
  'n8n.io',
  '*.n8n.io',
  'nocodb.com',
  '*.nocodb.com',
  'notion.so',
  '*.notion.so',
  'obsidian.md',
  '*.obsidian.md',
  'penpot.app',
  '*.penpot.app',
  'pinterest.com',
  '*.pinterest.com',
  'pitch.com',
  '*.pitch.com',
  'postman.com',
  '*.postman.com',
  'powerbi.microsoft.com',
  '*.powerbi.microsoft.com',
  'prezi.com',
  '*.prezi.com',
  'replit.com',
  '*.replit.com',
  'scribehow.com',
  '*.scribehow.com',
  'sketch.com',
  '*.sketch.com',
  'slab.com',
  '*.slab.com',
  'sli.do',
  '*.sli.do',
  'slido.com',
  '*.slido.com',
  'spotify.com',
  '*.spotify.com',
  'surveymonkey.com',
  '*.surveymonkey.com',
  'swagger.io',
  '*.swagger.io',
  'tableau.com',
  '*.tableau.com',
  'tally.so',
  '*.tally.so',
  'tidycal.com',
  '*.tidycal.com',
  'tldraw.com',
  '*.tldraw.com',
  'trello.com',
  '*.trello.com',
  'typeform.com',
  '*.typeform.com',
  'val.town',
  '*.val.town',
  'vimeo.com',
  '*.vimeo.com',
  'whimsical.com',
  '*.whimsical.com',
  'youtube.com',
  '*.youtube.com',
  'youtu.be',
  '*.youtu.be',
  'zapier.com',
  '*.zapier.com',
  'zeplin.io',
  '*.zeplin.io',
]

export function isIframeUrlAllowed(url: string, customWhiteListDomains?: Array<string>) {
  let hostname

  try {
    hostname = new URL(url).hostname
  } catch {
    return false
  }

  const domains = [...allowedDomains, ...(customWhiteListDomains || [])]

  return domains.some((domain) => {
    if (domain.startsWith('*.')) {
      const baseDomain = domain.slice(2)
      return hostname === baseDomain || hostname.endsWith(`.${baseDomain}`)
    }
    return hostname === domain
  })
}
