import type { RouteLocationNormalizedLoaded, Router } from 'vue-router'
import type { OrgUserRoles, ProjectRoles, WorkspaceUserRoles } from 'nocodb-sdk'

/** Handed to a `goto` function so tour files don't call `useRoute()` from an async continuation. */
export interface TourGotoContext {
  route: RouteLocationNormalizedLoaded
  router: Router
}

/**
 * Handed to every gate predicate. They run outside component setup, where
 * `useRoute()` is unavailable — reuse the app's own helpers (`isWsHomeRoute`)
 * rather than restating a path shape that will drift.
 */
export interface TourPredicateContext {
  route: RouteLocationNormalizedLoaded
}

export type TourPredicate = (ctx: TourPredicateContext) => boolean

/** A function arm so copy can be translated — resolved at render, when i18n is ready. */
export type TourText = string | (() => string)

/**
 * `'create-base'` — a generated `data-tour` id; autocompletes, typos are errors.
 * `'selector:.nc-foo'` — raw CSS escape hatch.
 *
 * `NcTourAnchorId` is generated by `modules/tour-anchors.ts`; see
 * `tours/anchors.catalog.md`. The `selector:` prefix rather than a plain `string`
 * arm is deliberate — a `string` arm makes every value assignable and defeats the
 * typo checking.
 */
export type TourAnchor = NcTourAnchorId | `selector:${string}`

/**
 * The four runtime states from the root CLAUDE.md matrix. Note `onprem-unlicensed`
 * *shows* EE features behind upgrade badges, so visible is not usable.
 */
export type TourDeployment = 'ce' | 'onprem-unlicensed' | 'onprem-licensed' | 'cloud'

export type TourKind = 'onboarding' | 'feature'

export interface NcTourStep {
  /** Element to highlight. Omit for a centered step with no highlight. */
  anchor?: TourAnchor

  title: TourText

  /** Supports inline HTML. One or two short sentences. */
  description: TourText

  side?: 'top' | 'right' | 'bottom' | 'left'
  align?: 'start' | 'center' | 'end'

  /**
   * Go here first — this is what lets one tour span pages. A string is pushed as
   * a path; a function is awaited and navigates itself, for URLs not known
   * statically.
   */
  goto?: string | ((ctx: TourGotoContext) => void | Promise<void>)

  /** Require a click on the element instead of showing Next. */
  advanceOnClick?: boolean

  /**
   * Advance as soon as this returns true, with no Next button — for steps
   * finished by a select or a field rather than a click. Polled, so keep it
   * cheap. No component context: Pinia stores and shared composables only, as an
   * injection-state composable (`…OrThrow`) throws and the step silently sticks.
   */
  advanceWhen?: () => boolean

  /** Whether the element stays clickable. Default true. */
  allowInteraction?: boolean

  /** Skip this step when false. Evaluated once, when the tour starts. */
  when?: TourPredicate

  /** Awaited before advancing — e.g. open the drawer the next step points at. */
  onNext?: () => void | Promise<void>
}

/**
 * Everything except `manual` and `beacon` is app-initiated and governed: never
 * repeats once seen, fires at most once, and passive kinds respect a cooldown.
 */
export type TourTrigger =
  /** Only from the Help menu or a deep link. */
  | { type: 'manual' }

  /** As soon as it's eligible, wherever the user is. Reserve for onboarding. */
  | { type: 'auto'; delay?: number; when?: TourPredicate }

  /**
   * On navigating to a matching route. `path` is matched against `route.path`:
   * a string matches by prefix, a RegExp by test.
   */
  | { type: 'route'; path: string | RegExp; delay?: number; when?: TourPredicate }

  /** Delegated, so it covers elements that mount later. No cooldown — user-initiated. */
  | { type: 'click'; on: TourAnchor; delay?: number; when?: TourPredicate }

  /** Fired by `emitTourEvent(name)` from anywhere. */
  | { type: 'event'; name: string; delay?: number; when?: TourPredicate }

  /** Pulsing beacon on `anchor`; starts only if the user clicks it. */
  | { type: 'beacon'; anchor: TourAnchor }

export interface NcTour {
  /** Versioned, e.g. `pivot-widget-v1`. Keys seen-state — changing it re-shows the tour. */
  id: string

  kind: TourKind

  /** ISO date. Orders the tour list and drives the "new" marker. */
  releasedAt: string

  /** Shown in the Help menu tour list. */
  title: TourText

  audience?: {
    /**
     * Reference the SAME gate the feature uses (`useEeConfig().blockX`,
     * `isUIAllowed(...)`) — a restated rule drifts. Also decides Help-menu
     * listing, so "new users only" conditions belong on the trigger instead.
     */
    when?: TourPredicate

    /** Any one of these is enough. Omit for "any role". */
    roles?: (WorkspaceUserRoles | ProjectRoles | OrgUserRoles)[]

    deployment?: TourDeployment[]

    /** Only offer the tour on matching routes. Tested against `route.path`. */
    route?: RegExp

    betaFlag?: string
  }

  trigger: TourTrigger

  steps: NcTourStep[]
}

/** Identity function — exists for type inference in tour files. */
export function defineTour(tour: NcTour): NcTour {
  return tour
}
