{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nocodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
  {{- with include "nocodb.annotations" (dict "context" . "extraAnnotations" dict) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "nocodb.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8080
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector: {}
      {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - {}
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
