{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nocodb.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
  {{- with include "nocodb.annotations" (dict "context" . "extraAnnotations" dict) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- $sc := .Values.persistence.storageClass | default .Values.global.storageClass }}
  {{- if $sc }}
  storageClassName: {{ $sc }}
  {{- end }}
{{- end }}
