apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nocodb.fullname" . }}
  labels:
    {{- include "nocodb.selectorLabels" . | nindent 8 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeMode: Filesystem
