apiVersion: v1
kind: Service
metadata:
  name: {{ include "nocodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
  {{- with include "nocodb.annotations" (dict "context" . "extraAnnotations" .Values.service.annotations) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nocodb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
