name: "Integration Node Tests"
on:
  push:
    branches: [develop]
    paths:
      - "packages/noco-integrations/**"
      - ".github/workflows/integration-node-test.yml"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled]
    branches: [develop]
    paths:
      - "packages/noco-integrations/**"
      - ".github/workflows/integration-node-test.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-node-test:
    runs-on: [self-hosted, v4, generic]
    timeout-minutes: 10
    if: >-
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'trigger-CI') ||
      contains(github.event.pull_request.labels.*.name, 'test:integrations') ||
      !github.event.pull_request.draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Get pnpm store directory
        shell: bash
        timeout-minutes: 1
        run: |
          echo "STORE_PATH=/root/setup-pnpm/node_modules/.bin/store/v3" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: remove use-node-version line from .npmrc
        run: sed -i '/^use-node-version/d' .npmrc
      - name: Install dependencies
        run: pnpm bootstrap
      - name: Run integration node tests
        working-directory: ./packages/noco-integrations
        run: pnpm test
