name: Pre-build CE for Playwright tests

on:
  workflow_call:

jobs:
  build-ui-ce:
    runs-on: ubicloud-standard-2
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'pnpm'

      - name: Set CI env
        run: export CI=true

      - name: remove use-node-version line from .npmrc
        run: sed -i '/^use-node-version/d' .npmrc

      - name: Cache integration dists
        uses: actions/cache@v4
        with:
          path: |
            packages/noco-integrations/packages/*/dist
            packages/noco-integrations/core/dist
            packages/noco-integrations/.build-checksums.json
          key: integrations-dist-${{ hashFiles('packages/noco-integrations/packages/*/src/**', 'packages/noco-integrations/core/src/**', 'packages/noco-integrations/packages/*/package.json') }}
          restore-keys: |
            integrations-dist-
      - name: install dependencies
        run: pnpm bootstrap

      - name: Point tsconfig to CE Nuxt types
        working-directory: ./packages/nc-gui
        run: |
          sed -i 's|"extends": "./ee/.nuxt/tsconfig.json"|"extends": "./.nuxt/tsconfig.json"|' tsconfig.json

      - name: Build CE UI
        working-directory: ./packages/nc-gui
        run: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          export NUXT_PUBLIC_ENV=CI
          pnpm run build

      - name: Create build archive
        working-directory: ./packages/nc-gui
        run: |
          FILE="$(echo ${GITHUB_REPOSITORY} | sed "s,/,-,g")-${GITHUB_RUN_ID}-ce.zip"
          zip -r ${FILE} .output || echo "UI build directory does not exists" >&2
          echo "ARCHIVE_NAME=${FILE}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ARTIFACTS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ARTIFACTS_S3_SECRET_KEY }}
          aws-region: us-east-2

      - name: Upload UI build to S3
        working-directory: ./packages/nc-gui
        run: |
          aws s3 cp ${ARCHIVE_NAME} s3://nocohub-ci-artifacts/ui-builds/${ARCHIVE_NAME}
          echo "s3://nocohub-ci-artifacts/ui-builds/${ARCHIVE_NAME}"
