name: pre-build-for-playwright

on:
  workflow_call:

jobs:
  playwright:
    runs-on: ubicloud-standard-2
    timeout-minutes: 100
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'pnpm'
      - name: remove use-node-version from .npmrc
        run: sed -i '/^use-node-version/d' .npmrc
      - name: install dependencies
        run: pnpm bootstrap
      - name: build frontend (nc-gui)
        working-directory: ./packages/nc-gui
        run: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          pnpm run build
        timeout-minutes: 20
      - name: Create build archive
        working-directory: ./packages/nc-gui
        run: |
          FILE="$(echo ${GITHUB_REPOSITORY} | sed "s,/,-,g")-${GITHUB_RUN_ID}.zip"
          zip -r ${FILE} .output || echo "UI build directory does not exists" >&2
          echo "ARCHIVE_NAME=${FILE}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ARTIFACTS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ARTIFACTS_S3_SECRET_KEY }}
          aws-region: us-east-2

      - name: Upload UI build to S3
        working-directory: ./packages/nc-gui
        run: |
          aws s3 cp ${ARCHIVE_NAME} s3://nocohub-ci-artifacts/ui-builds/${ARCHIVE_NAME}
          echo "s3://nocohub-ci-artifacts/ui-builds/${ARCHIVE_NAME}"
