name: "Release: Previous Docker"


on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Previous Docker image tag"
        required: true

jobs:
  login:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker retag and push
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/nocodb-fanjam:${{ github.event.inputs.tag }}
          docker image tag ghcr.io/${{ github.repository_owner }}/nocodb-fanjam:${{ github.event.inputs.tag }} ghcr.io/${{ github.repository_owner }}/nocodb-fanjam:latest
          docker push ghcr.io/${{ github.repository_owner }}/nocodb-fanjam:latest
